### ISSUE TITLE
Freeze when opening a field with many chars

### ISSUE THREAD

**Issue by ashjas** [Kunzisoft/KeePassDX#1021]
**Describe the bug**
Loading/Unloading issue with my personal database. The issue is reproduced in my attached sample db.

**To Reproduce**
1. Open the sample db. password is testpassword
2. Open testEntry [takes a while to load]
3. Once opened, there is no way to close this view. App has to be killed.

**Expected behavior**
Loading and unloading should work.

**KeePass Database**
 - Created with: keepassdx
 - Version: kdbx v4
 - Location: local
 - Size: [e.g. 115KB]
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.10.2
 - Build: [e.g. Free]
 - Language: [e.g. English]

**Android (please complete the following information):**
 - Device: [Mi A1]
 - Version: [Android 10 ]

**Additional context**
On clicking on back on the testEntry view, i get the following errors from the logcat:

```
06-09 12:27:35.161  3728  3728 D TimeoutHelper: Record app timeout
06-09 12:27:35.207  3728  3728 D TimeoutHelper: TimeoutHelper start
06-09 12:27:35.219  3728  3728 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1146352)
06-09 12:27:35.698  3728  3728 I chatty  : uid=10182(com.kunzisoft.keepass.libre) identical 2 lines
06-09 12:27:35.877  3728  3728 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1146352)
```
This same issue was also reproducible on one of my other device Asus Zenfone Max Pro (M1)
with same above error on returning back from the opened entry view.

This is an absolute non issue on keepassdroid. It works without any delays on opening the same entry, and closing the view works without any delays.

Thanks.
rename the below file from .zip to .kdbx. Password: testpassword
[Passwords-reproduced.zip](https://github.com/Kunzisoft/KeePassDX/files/6621782/Passwords-reproduced.zip)

**Comment by J-Jamet** [comment]
From the logs you give, it seems to be a parcelable memory overflow.
Parcelables are used to manage orientation changes (which KeePassDroid does not do).
I will test the database you uploaded and see where exactly the problem comes from.

**Comment by J-Jamet** [comment]
Android Parcelables are not designed to store such a large amount of characters in a field. In what case you need so many characters? It is recommended to create an attachment file for that.
I will try to fix the problem for version 3.0.0.

**Comment by ashjas** [comment]
Oh yes, I definitely don't have an actual DB with so much data in just a single attribute.
But I do use the db in this fashion , where all my data resides in attributes.
And for one of my groups, on incremental data appends, created lots of attributes, out of which few were holding text private keys as well which can be rather large.
The issue specifically arises on opening an entry having such attributes, which are both large in size and number.

I created this dummy DB just so you can reproduce it.

Also as a general usability feedback, keepassdroid has always felt more responsive than keepassdx.
I know its not apples to apples comparison, now that keepassdx has incrementally added soo many nice features, and has deviated from keepassdroid down the line. But if Android Parcelables is the real culprit of this responsiveness difference, maybe avoiding it can result in an overall better UI experience?
But to be frank, I am just guessing here, you are a better judge if this is really doable.

Thanks for the support.

**Comment by J-Jamet** [comment]
Indeed, you are right, there are some slowdowns that I don't like either.
It's the problem of having added elements to an architecture that was already present. (Because at first KeePassDX is a fork of KeePassDroid).

I can't remove the parcelable because it solves other problems related to the information encapsulation and retention between activities and the change of orientation without using global memory.
KeePassDroid uses a lot of global variables, it's fast but it's very difficult to maintain because there are interconnections and duplications of concepts, its a bad practice. It is very difficult to add new features with the architecture of Keepassdroid. (I advise you to look at the source code to get an idea)

To solve the performance issues of KeePassDX, I need to solve deeper architecture issues, which I am currently doing for version 3.0.0.
I'm going to use the MVVM ([Model View ViewModel](https://developer.android.com/jetpack/guide)) principle to better manage the information passing between the data to be displayed and the data in the database. But it's a huge work because I have to deconstruct big parts and unfortunately a rebuild can adds bugs.
So, I take the opportunity to implement the dynamic template management, the code will be much better encapsulated and clean and there will be a system of asynchronous loading of individual data.
I've been at it for two months and I'm not done yet.

https://github.com/Kunzisoft/KeePassDX/projects/40

**Comment by ashjas** [comment]
I agree, maintaining such a project with so many features, is indeed a full-time job in itself.
The project is already in extremely good shape in current state itself.
I really appreciate all work that you do!
Best of luck.

**Comment by ashjas** [comment]
Thank you for fixing this. I just tested thus on my actual db, and it works perfect!
