### ISSUE TITLE
KeepassDX notification disappear

### ISSUE THREAD

**Issue by dmework** [Kunzisoft/KeePassDX#1025]
**Describe the bug**
KeepassDX notification disappear from notification bar when i press "close all" button

**To Reproduce**
1. Unlock Database
2. Click on 'all apps'
3. Press "close all"
4. KeepassDX notification disappear

**Expected behavior**
In version KeypassDX_2.9.20 and below when i press "close all apps" KeepassDX notification is still there

KeePassDX:
 - Version: 2.10.0 and above
 - Build: Free
 - Language: English

Thank you

**Comment by J-Jamet** [comment]
You're right, it shouldn't happen. I had replaced the foreground services by a service launched normally with a foreground parameter, it should have the same behavior but it is not the case for the display of the notification (but the service is still active).
I will update to correct this problem.

**Comment by J-Jamet** [comment]
The behavior will not be the same as in previous versions because the code has changed to solve other bugs. After the fix, the database will be closed when the notification is not visible anymore, it will be more intuitive for the user, he will just have to swipe the screen to close the database (and the "clear all" will close the database too). Is this OK for you?

**Comment by dmework** [comment]
Thanks 
Can i leave the app open even if i close all apps until the screen is off

**Comment by J-Jamet** [comment]
The notion of openness is relative.
Technically each app is always open (because the system keeps in memory the launched apps, otherwise you have to kill it but it is not necessary), and the database can be opened or not according to its own state.
When the screen is turned off, the database closes normally if the option is enabled, otherwise not.
Now, when the application is swiped from the visibility of active apps or when clearing, the database closes too.

You can test with the beta 2.10.3 present on the Play Store.
