### ISSUE TITLE
Advanced unlocking is broken

### ISSUE THREAD

**Issue by dmework** [Kunzisoft/KeePassDX#1029]
**Describe the bug**
Advanced unlocking is broken when using "device credential unlocking"in Version: 2.10.3 and 2.10.4

**Comment by J-Jamet** [comment]
Not precise enough. I just tested with this version and it works without any problem.

**Comment by dmework** [comment]
I am using a PIN as a lock did you try that
Thanks

**Comment by shadow00** [comment]
@J-Jamet I've just updated from 2.10.1 to 2.10.4 on F-Droid and QuickUnlock doesn't work at all. I'm using QuickUnlock with the pattern unlock.

When I try to open my db with QuickUnlock it prompts me for my credentials, and then it goes back to the unlock screen as if nothing happened - only now the quickunlock button is gone. The password is still there though, so opening the db with the Open button at the bottom of the screen works fine.

Switching to another app and then back to KPDX will make the quickunlock button reappear, but the password does not get saved.

**Comment by J-Jamet** [comment]
There is no Quick Unlock in KeePassDX.
https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#why-not-quick-unlock

I tested again with my configuration and on emulator and I have no problem. Can you tell me what configuration you have? (Device, Android, etc...)

**Comment by hostops** [comment]
I have the same problem with the new version. With previous version everything was working as expected.
Now, credentials just do not get stored.
When I try to store master password using advanced unlocking, it asks me for my swipe pattern, and then I can unlock using "Open" button.
The next time I try to log in, it still says "This database does not have stored credentials yet" and I can repeat the process.

I am using OnePlus One with Lineage OS and MicroG instead of google services, but I do not think this is the problem, since previous version was working just fine.

**Comment by J-Jamet** [comment]
I have an idea of the issue : 
Fixing the #1018 bug should have an impact on older versions of the API but I need to know what version of Android you are using. 

Important note: The description of a bug is important, if I test with little information (less than one description line) and it works for me, I don't go any further because I have a lot to do. The more precise you are, the better I can identify and solve the problem quickly, so don't hesitate to indicate your complete configuration at the beginning to solve the problem.

**Comment by shadow00** [comment]
Yeah sorry, I was referring to the Advanced Unlock feature.

Running KPDX 2.10.4 on a Samsung Note 9, Android 8.1

Before updating to 2.10.4, I was running 2.10.1 and everything was fine.

Let me know if you need any additional information

**Comment by hostops** [comment]
Hi!
I am using android 10 on lineage OS 17.1.
I am also using MicroG 0.2.17.204714
Application was installed using F-Droid.

**Comment by J-Jamet** [comment]
OK, Thanks, I have identified the problem, I am making a patch. It was because of the new code of #1018.
The problem is reproducible only on devices below Android R with device credential unlocking, but work well for biometric unlocking.

**Comment by hostops** [comment]
Wow, good job!
When can we expect a new release to be published?

**Comment by J-Jamet** [comment]
I would like to solve problem #1028 before building the new version. If I can't, I'll put the beta online tomorrow.

**Comment by J-Jamet** [comment]
Version 2.10.5 has been uploaded to the Play Store test channel. Tell me if it works for you?

**Comment by dmework** [comment]
I can confirm it's working now

**Comment by bushrang3r** [comment]
This issue is happening again for me.

1. Start the app and go to settings and switch on Device credential unlocking in Advanced unlocking
2. Go back to login screen, enter password, tap the top middle button to enter lock pattern, touch the first dot in the sequence to unlock and the system ui (not the keepass app) crashes and the phone screen locks. 

Keepass 3.0.0_beta02
Android 11 (Lineage 18.1)
OnePlus7T

**Comment by bushrang3r** [comment]
Oops, this may not be a Keepass problem.
I'm trying to unlock other apps (on my new phone) with pattern unlock credentials and the same system ui crash is occurring.

**Comment by bushrang3r** [comment]
I'm sorry Jeremy, 
I don't know if this bug is related to Keepass or not, so I've pasted logs below.
When I try to use the pattern lock to unlock the app, the system ui crashes. I hope you can see where the problem lies.
The bug was present for me on 3.0.0_beta02 as I stated above, and now I'm on 3.0.0 and the same bug persists. 


09-11 21:06:53.410 I/ActivityTaskManager(1313): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity bnds=[846,1132][1050,1497]} from uid 10166
09-11 21:06:53.441 I/ActivityManager(1313): Start proc 27302:com.kunzisoft.keepass.free/u0a203 for pre-top-activity {com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.FileDatabaseSelectActivity}
09-11 21:06:53.485 D/com.kunzisoft.keepass.activities.stylish.Stylish(27302): Attatching to com.kunzisoft.keepass.free
09-11 21:06:53.518 I/ActivityTaskManager(1313): START u0 {cmp=com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.PasswordActivity (has extras)} from uid 10203
09-11 21:06:53.589 D/UriUtil (27302): Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3Akeepass%2Fkeepass.kdbx, modeFlags=3, persistedTime=1631092241241}
09-11 21:06:53.643 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.644 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.652 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.652 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.713 I/ActivityTaskManager(1313): Displayed com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.PasswordActivity: +297ms
09-11 21:06:53.718 D/UriUtil (27302): Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3Akeepass%2Fkeepass.kdbx, modeFlags=3, persistedTime=1631092241241}
09-11 21:06:53.736 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.737 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.737 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.738 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.782 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.782 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.784 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.785 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:06:53.849 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 0 Status: 3
09-11 21:06:59.166 E/com.kunzisoft.keepass.biometric.AdvancedUnlockFragment(27302): Biometric authentication error. Code : 5 Error : 
09-11 21:07:02.821 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:07:02.822 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:07:02.872 D/UriUtil (27302): Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3Akeepass%2Fkeepass.kdbx, modeFlags=3, persistedTime=1631092241241}
09-11 21:07:02.920 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:07:02.920 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:07:02.921 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:07:02.922 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
09-11 21:07:02.948 D/BiometricService(1313): Package: com.kunzisoft.keepass.free Authenticator ID: 0 Modality: 2 Reported Modality: 0 Status: 3
09-11 21:07:04.233 E/com.kunzisoft.keepass.biometric.AdvancedUnlockFragment(27302): Biometric authentication error. Code : 10 Error :
