### ISSUE TITLE
Quick Unlock

### ISSUE THREAD

**Issue by hellyeahmfs** [Kunzisoft/KeePassDX#1051]
It is so annoying to fill the long Master Password everytime. It would be great to have a Quick Unlock feature where user can easily unlock the database. Like only requiring last 3 or 4 digits of the Master Password to unlock the database.
It doesn't impact Security because it gives only one chance to fill the Quick Unlock Password and if user fills wrong password then it requires Master Password to unlock the database.

**Comment by J-Jamet** [comment]
The issue has already been addressed, and alternative solutions are already available.
Same as https://github.com/Kunzisoft/KeePassDX/issues/102

It has been shown that the Quick Unlock of other applications is dangerous because the database remains open in RAM without encryption and many users do not know this.

As a reminder, the Quick Unlock password is only used to unlock the UI but will be of no use if an external program has access to the application's RAM during this mode.

Study of the code : https://github.com/Kunzisoft/KeePassDX/issues/102#issuecomment-636650198
Wiki explanation : https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#why-not-quick-unlock
