### ISSUE TITLE
Passphrase Generator

### ISSUE THREAD

**Issue by Lumenbolt** [Kunzisoft/KeePassDX#1058]
**Is your feature request related to a problem? Please describe.**
Passphrase generator is a common feature all Keepass fork (android or otherwise) have. Passphrases are much easier to remember temporarily or to type then down on to another machine. **I think this is a much-needed feature in KeepassDX.**

**Describe the solution you'd like**
Something like a built-in diceware passphrase generator would be great, with a choice of adding random characters and numbers between each word. Bitwarden has an excellent implementation of this. E.g. _Wharf-Muck-Urban6-Smooth-Rewrap-Lunar_

**Describe alternatives you've considered**
Right now I've to obtain a randomly-generated diceware passphrase from an app available in Play Store.

**Additional context**
A very basic feature a normie would expect in a password manager.

**Comment by J-Jamet** [comment]
Duplicate #218 #110

I agree that it is a feature to implement, but there is a code architecture to respect to be smooth, secure and interoperable.

I haven't implemented it yet because it requires a very specific code organization to handle each language and to load asynchronously the big libraries. It is also necessary to check the entropy generation because it can add security holes if it is predictable.
The libraries will be downloaded on-the-fly according to the user's needs (his language) and therefore requires the implementation of deployment bundles for the generation of the APK.

Glad to know that this is a very basic implementation for you but personally I wouldn't call it "very basic". The advantage of open source is that a normie can also contribute. Feel free to implement your code, I will gladly look how you made it. 

I am closing this issue because it has already been opened in other threads.
