### ISSUE TITLE
Option to view a PDF attached to an entry

### ISSUE THREAD

**Issue by Lumenbolt** [Kunzisoft/KeePassDX#1060]
**Is your feature request related to a problem? Please describe.**
I've several documents/files saved in my database that I have to open and view quite often. Whenever I tap a file attached to an entry it directs me to a file downloader. While downloading a file may be necessary when needed, downloading it just for the sake of viewing the file would mitigate the purpose of having the file saved in a secure database. 

**Describe the solution you'd like**
A way to view the file (such as a PDF or JPEG file) with a built-in reader or to temporarily cache it to view it on a third-party document/image viewer is necessary to fulfill the purpose of keeping the file protected and private. _Keepass2Android_ has options to do both.

**Describe alternatives you've considered**
No such alternative I can think of, since it seems inconvenient to manually download, view and delete the file every time I need to view it from the database.

**Comment by J-Jamet** [comment]
The functionality to view an attached image file in an entry is already implemented.
Can you tell me in which case it does not work for you? Can you upload a database where it doesn't work?

For the PDF case, I don't recommend storing PDFs because it's a content aggregator format.
The KeePass format is made to store keys in the first place, not files that weigh down the database.
The files are meant for PGP keys for example or QR images.
For content-aggregating files, I recommend using virtual hard drives.

So if it's for text info, creating a custom field is a solution. And displaying images should work.
The functionality to display flat text attachment in an entry has a higher priority than displaying PDFs.

When is storing PDFs in a KeePass database a necessity for you?

**Comment by Lumenbolt** [comment]
> The functionality to view an attached image file in an entry is already implemented.

Oh, I see. I might have not noticed in case of image files, my bad.

> Can you tell me in which case it does not work for you?

I have a few important documents I need to protect (which are PDFs) that I open quite often, hence the feature request.

> I don't recommend storing PDFs because it's a content aggregator format.

Agreed. Being a password-protected vault, having a few important documents attached to entries did help me do the job of accessing them easily. Moreover, I use Syncthing to sync the database across my devices so I don't have any issue with the bloated size of the database file.

> For content-aggregating files, I recommend using virtual hard drives.

Might consider this, thanks for the suggestion.

> The KeePass format is made to store keys in the first place, not files that weigh down the database. The files are meant for PGP keys for example or QR images.

Being a beginner to KeePass, I didn't know about the exact purpose of attaching files to an entry. I thought we could attach anything pertaining to the entry, E.g. attaching a scanned copy of a credit card along with a credit card entry.

Since PDF's aren't conventionally meant to be stored in a database, I'll close this issue since this FR seems futile.

**Comment by J-Jamet** [comment]
Technically, you can put any format you want as an attachment.
The files are serialized, encrypted and stored in the database file header to be accessible the next time you open them. The problem is that the more data there is to decrypt, the longer the algorithm takes to open a database. That's why from a functional point of view, it's better to optimize the attached files in a KeePass database.

I am aware that this is not necessarily accessible information, I would have to make a more detailed article about it in the wiki.
