### ISSUE TITLE
Enabling templates does not work

### ISSUE THREAD

**Issue by uduerholz** [Kunzisoft/KeePassDX#1062]
With the current development branch it's not possible to add a new template-based entry to an "old" database.
When you open an existing database (without templates folder) and then enable templates in the database settings, an empty templates folder is created.

**KeePassDX**
    Version: 3.0.0 (branch "develop")
    Build: Free

**Android**
    Device: Fairphone 3
    Version: Android 10

**Comment by J-Jamet** [comment]
This is normal behavior.
If a database without a template is opened, only the template folder is created and it behaves well as a template folder when adding templates inside.
Do you think it would be better to automatically add the pre-registered templates if a new template folder is created?

**Comment by uduerholz** [comment]
I think it would be better. Otherwise how can you add a template to the empty folder? Only manually?

**Comment by J-Jamet** [comment]
The purpose of the template group is normally to be able to create templates manually.

I haven't yet created the associated manual in the wiki but I have created a pseudo simplified language for this purpose. Just create an entry in this special group and add custom fields. The content of the custom field corresponds to the type of the field in the template (text, datetime, ...) and options can be added. For the moment not many options because internally converted in the plugin format (which is a disgusting format by the way) but later on more options can be added (Regex, filters, etc...)

I added pre-built templates for the new databases because it gave examples. But yes I could put them also when creating the group.

**Comment by uduerholz** [comment]
> I added pre-built templates for the new databases because it gave examples. But yes I could put them also when creating the group.

That would be nice. You know, people are lazy. ;-)

**Comment by J-Jamet** [comment]
> That would be nice. You know, people are lazy. ;-)

You're right, it's something I forget sometimes! :D

**Comment by uduerholz** [comment]
I noticed that the app also searches the recycle bin when deciding if a templates folder exists. Is this
the intended behaviour?

**Comment by J-Jamet** [comment]
In fact it is very simple, the group template has a UUID stored in the database format. No matter where it is located, if the group has the UUID described by the database, it is a template group.
Why this question? Does it cause bugs?

**Comment by uduerholz** [comment]
No, not really a bug. It just means that if you made changes to your templates and then want to restore the "default" templates, it's not enough to delete the templates folder, in addition you have to empty the recycle bin. No problem. ;-)

**Comment by J-Jamet** [comment]
Not necessarily, can also change the UUID of the group to watch for templates in the settings.

**Comment by J-Jamet** [comment]
I'll explain this in the wiki but I'm already writing the articles for the attachments.
