### ISSUE TITLE
Any method to share or copy the OTP seed without going into "edit" mode?

### ISSUE THREAD

**Issue by gitbq** [Kunzisoft/KeePassDX#1063]
I'm looking for a way to share my 2fa TOTP seed with another application. The only method I can see to do this is to "edit" the record, then manually select the seed "text" and then copy. 
I'm concerned that it is very easy to unintentionally alter the seed text string using this method.

Is there a way to copy the "seed" field with out going into edit mode?
Some OTP apps also offer the ability to share the seed via qr code like Google Authenticator and KeepassXC.

Is something like this possible?

**Comment by J-Jamet** [comment]
For the moment it is not possible because it is a very particular use during an app migration. The passphrase of a TOTP should not be easily shared by the application which must keep it secret.

The generation of the QR code (to share it) is only useful for the service that proposes its unlocking by TOTP. And a KeePass database cannot be unlocked by a TOTP token.

Therefore, it is sufficient to give high visibility to the TOTP token to unlock external services and to keep the passphrase relatively hidden.

**Comment by gitbq** [comment]
No worries. 
Thanks
