### ISSUE TITLE
Unable to unlock database

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#1067]
**Describe the bug**
Unable to unlock database.
Whether it is using advanced recognition to unlock or enter a password, an error is reported.

The problem does not appear every time.

**To Reproduce**
1. Run the application for the first time, select the database and fill in the password to unlock the database normally.
2. When the application process is killed, when the previously selected database is opened again, the unlocking will fail.
3. The database selection history recorded by KeePassDX must be cleaned up, and then the previous database must be reselected to unlock the database again.

**KeePass Database**
 - Created with: Windows KeePass 2.47 (64 Bit)
 - Version: KeePass 2-KDBX4.1
 - Location: Local Disk
 - Size: 1.73M
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 3.0.0_beta01
 - Version code: 84
 - Build: Pro
 - Language: Chinese

**Android:**
 - Device: XiaoMi Note 3
 - Version: 9.0

**Additional context**

![Screenshot_2021-08-30-19-36-43-538_com kunzisoft keepass pro](https://user-images.githubusercontent.com/20795557/131334674-c8c868e1-3955-40e9-8a27-21a76ed6da0e.jpg)

**Comment by J-Jamet** [comment]
This problem has just been fixed and comes from the URI of the key file. You just have to update the application to version 3.0.0_beta02 and reselect your key file once.
Duplicate #1066

**Comment by Vstory** [comment]
I'm sorry to have lost your time.
When posting the question, I browsed it a bit.  
Did not notice #1066

**Comment by J-Jamet** [comment]
No problem, I prefer to get feedback even if it's already processed. You never know, it could have been another problem, so on the contrary, it's a good thing. Many users don't even bother to give feedback and think that the problems will be solved magically, but in 90% of the cases, if there is a bug, it's because I didn't detect it, otherwise I would have corrected it.

So having feedback is very important in all cases. ;)
