### ISSUE TITLE
Some opinions in Layouts

### ISSUE THREAD

**Issue by patarapolw** [Kunzisoft/KeePassDX#109]
I originally [forked your project](https://github.com/patarapolw/KeePassDX-memorable-password) to put in my Password Generator, and I updated the Layout a bit.

Some opinionated decisions that may be relevant to you are:-

- [Two password generation buttons](https://github.com/patarapolw/KeePassDX-memorable-password/blob/32fbfaeb74935d054aa558a89e6bf65653192628/app/src/main/res/layout/entry_edit.xml#L149), one for Passphrase, one for PIN. Also, two separated settings / default settings.
- [Removed the Setting >> Application Settings >> Password >> Length key / Generator Option key](https://github.com/patarapolw/KeePassDX-memorable-password/blob/32fbfaeb74935d054aa558a89e6bf65653192628/app/src/main/res/xml/application_preferences.xml#L64). Actually, I make the length variable, within the range [10 ,20].

I don't know much about forking an open-source project, contributing, making my version, so I am not sure if I have done it correctly / legally. Nor do I know if I should make a Pull Request in this case.

Or, can I create an APK, or upload to Play Store?

**Comment by J-Jamet** [comment]
I have clone your repo to test the feature. It's good!

Legally it's under the GPL3 license, so you're are welcome to modify the code! ;)  

You can create an APK for the Play Store but the goal in this case is to provide a really different application of the basic application to make a long fork that you maintain in time, with changement of the name, the packages, significant features etc ... in order to make a real other application entity. (keep in mind that KeePass DX it's still in beta.)

I advise you to create a pull request, I had in mind to put tabs to choose the generator, obviously we can discuss to make the best decisions of how to integrate the functionality! :)

**Comment by J-Jamet** [comment]
As the pull request #110 is open, I close this issue.
