### ISSUE TITLE
Autofill TOTP

### ISSUE THREAD

**Issue by Gottarocket** [Kunzisoft/KeePassDX#1093]
**Is your feature request related to a problem? Please describe.**
No but would be helpful without the need to access ap everytime for TOTP
**Describe the solution you'd like**
When the credentials are autofill if there is TOTP it should prompt to autofill or copy to clipboard automatically and could be just pasted 
**Describe alternatives you've considered**
This may seem like killing feature to copy TOTP with timeout on field but if autofill is implemented for credentials TOTP would also be best

**Additional context**
For reference bitwarden does it but on pc it needs keys so either autofill prompt or copy to clipboard which can be pasted is suggested

**Comment by J-Jamet** [comment]
Duplicate https://github.com/Kunzisoft/KeePassDX/issues/553
Topic already explained: https://github.com/Kunzisoft/KeePassDX/issues/553#issuecomment-912936390
Autofill OTP can't work because form recognition is not good. And the copy in the clipboard is a hack that can only work for one element and should not be used for a 2FA because it implies that it is stored in the same database as the main credentials (so don't use TOTP in this case because it doesn't increase the account security, only complexity)
