### ISSUE TITLE
OneDrive switched to unrelated file

### ISSUE THREAD

**Issue by mwisnicki** [Kunzisoft/KeePassDX#1118]
I've been using KeePassDX for few months with a database stored on OneDrive.

Today KeePassDX tried to open totally unrelated file (some mp4 video) instead of the usual database file.

Perhaps this is caused by some issue in Storage Access Framework or OneDrive provider but KeePassDX at least seems to be aware of new filename so should probably detect this situation and request re-opening the file through file picker.

**Comment by J-Jamet** [comment]
> Today KeePassDX tried to open totally unrelated file (some mp4 video) instead of the usual database file.

In fact, KeePassDX is not able to fetch data that has not been explicitly defined by the URI of the content provider of the file manager you use.
What happened is very simple: when the database is first opened, a URI is saved in order to keep a history so that the file can be opened later.
But in your case, the OneDrive application provides another file on the same URI that was previously defined for your database.
And KeePassDX can't do anything about it, it's a bug in OneDrive.

> Perhaps this is caused by some issue in Storage Access Framework or OneDrive provider but KeePassDX at least seems to be aware of new filename so should probably detect this situation and request re-opening the file through file picker.

The name change can of course be detected. But if this is normal behavior and you have simply renamed your database file, you will have to reselect the file each time, which is a regression.
The same goes for the content, if the data has been changed, it can be quite legitimate.

For an analogy, it's like if you go to a website, put a bookmark and go again to the website from the bookmark the next day and the content of the website has changed. It's not the browser's fault, nor is it a problem with the bookmark, it's just that the data linked to the URI/URL has changed.

This behavior has already been identified and is already added to the wiki: https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by mwisnicki** [comment]
Thanks, I'll try to report it to OneDrive since it's actually a security vulnerability but I'm not getting my hopes up.

**Comment by J-Jamet** [comment]
I'm closing this issue, if you want to continue the discussion on OneDrive: https://github.com/Kunzisoft/FileSync/issues/3
