### ISSUE TITLE
The + for adding posts disapears after updates

### ISSUE THREAD

**Issue by Lekard589** [Kunzisoft/KeePassDX#1120]
The + for adding post disapears after app update from Google play. This has happened after the two latest updates (now version 3.0.2) 

If I delete the app end reinstall it the + is back again. 

**To Reproduce**

**Expected behavior**

**KeePass Database**
 - Created with: keepass 2 - kdbx3.1
 - Version: [e.g. 2]
 - Location: Remote file retrieved with GDrive app
 - Size: 6.3 kb
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 3.0.2 
 - Build: free
 - Language: Swedish

**Android (please complete the following information):**
 - Device: oneplus 8t
 - Version: oxygen os 11.0.10.10 (not rooted) 

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
The + button for adding entries and groups may disappear if : 
 - You scroll through the list of entries. The button disappears for better readability and reappears if you scroll back up.
 - Your database is manually opened in read-only mode. If you have pressed the "pen" button, your database can only be opened in read-only mode and the button will not be accessible.
 - Your database is automatically opened in read-only mode because the file provider used does not give write rights. This may be the case if it is a transition state, for example a synchronization in your file manager or if you are in a specific mode.

I have tested many times and cannot reproduce your behavior in a case not listed above.

**Comment by J-Jamet** [comment]
You do not indicate the procedure to reproduce the bug.

**Comment by J-Jamet** [comment]
No response.
