### ISSUE TITLE
Support URL / webdav

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#118]
https://keepass.info/help/v2/ioconnect.html

**Comment by SeWieland** [comment]
I would really appreciate a WebDav integration, because the synchronization via the android nextcloud client is not very user-friendly. To synchronize the database, the nextcloud app must be opened every single time.

**Comment by J-Jamet** [comment]
I understand, this is a feature that is requested multiple times. It will be done but I have to do other features before. There is really a lot of work so I have to prioritize the elements to develop. Feel free to facilitate the work with various contributions (code if you are a dev, translations or donations)

**Comment by AgenturVS** [comment]
I would also like an Integration of WebDAV, because I am using it in the moment with the other app. I loved what I saw, but I have to deinstall til then. This app gonna be perfect!

**Comment by freijon** [comment]
Maybe you can take some of the code from Keepass2Android, which supports WebDav and other cloud storage types. Of course, only open source code should be used to keep compatibility with F-Droid

**Comment by Zhaobab** [comment]
This feature could be awesome :-)

**Comment by Offerel** [comment]
One additional comment. Since it's no problem to change something on a database on Android and sync the changes immediately to a remote WebDAV is easy with third party apps like FolderSync or Synchronize Ultimate, it leads to problems the other way around.

Imagine something is changed in the database on the WebDAV Share (or any other remote storage). There is no way to trigger a sync automatically to the mobile device. If the remote storage is included in the app, the app could check before saving changes locally, for changes at the remote, which should prevent overwriting remote changes.

**Comment by Offerel** [comment]
Since missing this feature bothers me a lot, I have created the following workaround:

First, i created a  sync with the app FolderSync. Setting up the job should be straight forward, i only enabled"Instant Sync" in case the database changed locally.

After that I used Macrodroid and added a new macro. As trigger, I choose application start and used KeePassDX as application. As action I used Tasker plugin, since FolderSync has such a Plugin. I choose the created FolderSync job I created in step one.

Now it starts the sync job every time i start KeePassDX and before I unlock the database. It sync only if there is a difference in the database. If i change the database on Android it sync automatically back, since Instant Sync is enabled.

Not a perfect solution, but should help until WebDAV is built in.

**Comment by J-Jamet** [comment]
WebDAV is a network feature and I think it is better to encapsulate the components correctly so that users can choose the synchronization mode they want with KeePassDX.

The purpose is to use [SAF](https://developer.android.com/guide/topics/providers/document-provider) with its content-provider to be adaptable to all file synchronization modes.

KeePassDX is a file editor and not a file manager. It will therefore be up to the file manager app that offers the link to implement WebDAV, it is better for the security of KeePassDX.
It's the same philosophy as KeePassXC.

I have not tested the @Offerel method, but it is a good approach.
There will later be the creation of a dedicated file manager app that will manage WebDAV and others sync methods.

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by MisterY** [comment]
I agree that the password manager should not be bloated with the support for various cloud services and generally other functionality.
Ideally, there would be a simple app that links SAF with WebDAV. I'm amazed that I still can't find one.

**Comment by J-Jamet** [comment]
For those who want the WebDAV integration, I think the most promising is to look at the [Material Files](https://github.com/zhanghai/MaterialFiles) project from @zhanghai. And help him integrate this functionality. https://github.com/zhanghai/MaterialFiles/issues/191

**Comment by J-Jamet** [comment]
It is also possible to look at [rcloneExplorer](https://github.com/kaczmarkiewiczp/rcloneExplorer). I have not tested it but it seems to integrate several remote connection solutions. Please note, however, it uses APIs with code without free license.

**Comment by MisterY** [comment]
The trouble with these programs is that they have to follow providers' updates and require a lot of effort on the side of the app maintainer.
It seems that this is exactly what happened to rcloneExplorer. A bit outdated, some providers don't work at all, and no longer maintained.
The successor, https://github.com/x0b/rcx, does not seem to register as an SAF provider but only a client. Or maybe I'm missing something.
Material Files might be interesting, but only if it registers a SAF provider.
Thanks for the links!

**Comment by J-Jamet** [comment]
You are right @MisterY, the ideal would be that each cloud solution is completely incorporated into Android but this is not the case. There I just put the links that seemed to me the most promising that offer alternatives, without testing. I don't know if RCX uses SAF, we need to investigate further. 
I put great hopes in Material Files, it looks very well done and I think that with a little work, it will be perfectly adapted to the need (it allows to manage the intent ACTION_CREATE_DOCUMENT therefore already perfectly integrated for local operations)

**Comment by MisterY** [comment]
Since there seems to be no valid solution for synchronization on file change, I have resolved to using rclone and rclonesync in Termux.

It would be possible to use any sync solution, like FolderSync etc., but rclone is fairly simple and straightforward when Termux is already present.

Ideally, having a WebDAV option would be great, as that's some sort of standard. It seems that not too many app developers are interested in implementing Storage Access Framework. I've used it for the same purpose for an open source personal finance application and maintaining the file synchronization was a major source of troubles for an app that does not specialize in storage.

**Comment by J-Jamet** [comment]
> Ideally, having a WebDAV option would be great, as that's some sort of standard. It seems that not too many app developers are interested in implementing Storage Access Framework. I've used it for the same purpose for an open source personal finance application and maintaining the file synchronization was a major source of troubles for an app that does not specialize in storage.

As described [here](https://github.com/Kunzisoft/KeePassDX/issues/788#issuecomment-757461024), the best solution would be to create a dedicated application that would handle WebDAV and other protocols by offering a suitable and universal content provider (compatible with KeePassDX and many others but not directly integrated in it).
The problem is that I'm currently working on my free time and I can't manage another project like this one on top of it. Maybe I'll open a survey to ask how interested you are. Maybe I'll create it sooner than expected, but I'll have to put a funding system in place somehow.
Maybe something like: Standardized and open protocols (WebDAV) would be offered free of charge for download, while protocols and APIs linked to paid and non-free Clouds would be added by paid plugins. What do you think about it?

**Comment by Offerel** [comment]
When Keepass Desktop syncs entries, it syncs only the changes for the single entry and not the entire db. Will with such a standalone application, the same sync algorithm possible, as with desktop? Otherwise, it could be possible to loose data. For example when the same entry was changed on different backends.

**Comment by J-Jamet** [comment]
I have not yet looked at the operation of the KeePass data merge during sync because the algorithm is rather complex and the source code for this part has to be studied in detail. (https://keepass.info/help/v2/sync.html Technical details section).
But in the next version 2.9.9, KeePassDX will already recognize the file change in KeePassDX and it will be proposed to reload the database or overwrite the data (https://github.com/Kunzisoft/KeePassDX/issues/794).

Anyway, it doesn't change the way to use a separate application for this, the content-provider of the file manager can very well be made to expose an entire file or data for updates in KeePassDX, it's not a problem.

@Offerel When you say that it only synchronizes changes, you mean that on two databases in two locations only the changed data is transferred and not the entire file? Because I haven't seen code that only sends pieces of databases. Is a new small file created with the same encryption? Maybe I'm wrong, in that case, can you tell me more about the technical functioning and where in the code.

First, the separate file manager app will provide a complete encrypted file and the content will be merged according to the merge algorithm that will be integrated in KeePassDX (Issue #840). Subsequently, it is possible to expose other types of data.

**Comment by Offerel** [comment]
I have no idea how in detail the KeePass desktop sync work's. But from my understanding, it's possible to have a entry called 'example entry'. Now I can make changes to this entry on desktop and on mobile, so that the entry changes on both locations. If I now sync or merge, I will not overwrite the older entry, I will truly merge them, and not loose one or the other change.

Second, I'm not sure, how fast a change made in KeepassDX will be merged and synced to the remote backend (and with this coming available for desktop). Sure, a sync application can watch file charges and sync this as fast as possible to a remote backend, but I'm not sure how reliable this would be. If I wait some minutes between changes, my workaround from above is working fine. But we should keep an eye on this. But I have not enough knowledge to be sure, if I really get my requirements.

**Comment by J-Jamet** [comment]
The behaviors you describe are those related to the data merge I was talking about with complex algorithm to implement.
In this case, the data of the old and new file are compared and a merge in the XML is made according to certain criteria. In this case, the new file must be recovered and then decrypted in parallel with the old file, which is already planned.

I don't know what you mean technically by "as fast as possible"? If it's having a good network connection, it has nothing to do with what we're talking about! :D But if there are techniques for sending encrypted database parts, it will be interesting to understand the technical functioning.

**Comment by CubicrootXYZ** [comment]
Would be interested in webdav support too, otherwise I will stick with keepass2android.

**Comment by J-Jamet** [comment]
For the data merge, issue is #840
I opened an issue in the new synchronization application https://github.com/Kunzisoft/FileSync/issues/1, if you want to continue to discuss the WebDAV subject, it is there.

So I'm closing this issue for KeePassDX.
