### ISSUE TITLE
Last database not saved

### ISSUE THREAD

**Issue by SpitfireCH83** [Kunzisoft/KeePassDX#1197]
Hi,

Everytime I open the app on my phone, I have to manually choose the database in my phone's folder. I'm using a Huawai P30 Pro on Android. Never had the issue with other keepass apps. So I might have to go back to another, app, even if I like the features of KeePassDX better.

**Comment by J-Jamet** [comment]
Your issue is not specific enough and does not indicate the basic information to process it. Please fill in the bug template correctly. 
https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

> Everytime I open the app on my phone, I have to manually choose the database in my phone's folder.

Pretty sure I've explained it in the wiki and repeated it in lots of other issues, but I'm sure you've read it and your case is special but it must be explained correctly.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

> Never had the issue with other keepass apps. So I might have to go back to another, app, even if I like the features of KeePassDX better.

The issues are filled in correctly by other users, so I am forced to deal with other issues before yours even though I like you.
