### ISSUE TITLE
Autofill TOTP

### ISSUE THREAD

**Issue by kedricpon** [Kunzisoft/KeePassDX#1208]
I have enabled `Autofill` and `Clipboard Notifications` but I don't get any notification or autofill for the TOTP. It doesn't work on `App` and `Browser`. My browser is Firefox on android

It should have a notification or autofill right, most likely I have done something wrong because I'm kinda dumb

**KeePass Database**
 - Created with: [Windows KeePass 2.6.6]
 - Version: [e.g. 2]
 - Sync: Synced with Syncthing on Linux, Windows and Android
 - Size: about 90kb
 - Contains attachment: Yes

**KeePassDX**
 - Version: 3.0.4
 - Build: Free
 - Language: English

**Android (please complete the following information):**

I'm kind of new to writing this kind of post, so I just follow the example
 - Device: Vivo Y15

**Additional context**
 - Browser for Autofill: Firefox

**Comment by J-Jamet** [comment]
Autofill OTP -> duplicate https://github.com/Kunzisoft/KeePassDX/issues/553

Cliploboard notification OTP -> This feature allows you to display a notification when you access an entry. I just tested and it works well

**Comment by kedricpon** [comment]
Sorry for bothering you, but I couldn't figure out how to get this feature
working. I enabled Clipboard Notifications and Autofill. tq

**Comment by J-Jamet** [comment]
> Sorry for bothering you, but I couldn't figure out how to get this feature
working.

Neither do I, that's the whole problem that is described in this comment : https://github.com/Kunzisoft/KeePassDX/issues/553#issuecomment-912936390.

> I enabled Clipboard Notifications and Autofill. tq

I understood the first time. The autofill OTP is not easily done because many OTP forms are different. I don't know any application that has implemented it.

The notification works well when you view an entry, but honestly I don't recommend using it, you might as well click directly on the generated OTP token in the entry list. The setting "Settings - Appearance - Show OTP token" must be activated.

**Comment by kedricpon** [comment]
Can't you make that it will send a notification after autofill? Because if
you think about it, going back in the app and copying the TOTP is tedious
and kinda diminish the advantages of having autofill. I know I didn't pay
or donate, so I probably should'n't be asking for anything. Tq

**Comment by J-Jamet** [comment]
No I can't, I think you didn't read very well (or at all) the threads I linked. So thank you for reading them.

[https://github.com/Kunzisoft/KeePassDX/issues/553#issuecomment-912936390](https://github.com/Kunzisoft/KeePassDX/issues/553#issuecomment-912936390)

**Comment by J-Jamet** [comment]
Adding a TOTP notification after an autofill doesn't make sense. The point of a TOTP is to use a second factor, so you need at least two separate databases: 
 - one to fill the username/password fields of a service
 - another one to generate the TOTP token
Otherwise if it's the same database, it's like having two locks on a door and putting both keys on the same key ring, no interest and no point in using a second factor.

So if you want to use autofill on the second base, the password will be empty so you will have to fill fields with empty elements and make a hack to launch a TOTP notification. So we might as well not do autofill at all if we use a notification. It is easier to copy the token directly by opening the database.

**Comment by kedricpon** [comment]
I never looked at it like that, I usually have OTP autofilled with
KeePassXC. I think OTP is an extra layer when there is a breach.

**Comment by J-Jamet** [comment]
Yes, of course, it's always good to increase our security level. That is not the point here.

**Comment by kedricpon** [comment]
Yea thts why i use a open source password manager. At first i used last
pass but they changed tht you can't use more than one device if you don't
pay, of course this is bad because I am very young and don't make money.

Then i found keepass xc and i been using it for couple months now

I actually recently got interested in open source and stuff.

**Comment by J-Jamet** [comment]
This is a very good thing. It's a spirit of sharing above all, but it's like everything else, there are abuses, so we must inform people about the philosophy and the licenses that are linked to it. The most interesting thing is to learn and look at the source code, to share knowledge and values. In security, I think it's now essential that the code is open, it allows everyone to check the implementation and to fill the gaps.

**Comment by kedricpon** [comment]
Yes open source (in my opinion) is much more secure than closed source
software. Even though I love open source software, sometimes I can't just
not use close source software. Of course, if there's a way to use open
source software I will.
