### ISSUE TITLE
improve save credential flow

### ISSUE THREAD

**Issue by sheikh-azharuddin** [Kunzisoft/KeePassDX#1216]
**Is your feature request related to a problem? Please describe.**
Currently after clicking save the app is redirecting through multiple flows/screens to save the credentials

**Describe the solution you'd like**

When entered username and password in a website, post login keepass is showing a prompt to save the credentials however I feel the flow is lengthy on clicking save... On clicking save it is taking to the app...
1.the first page shown is select database this is not required if a single database file present..
2.next comes the biometric authentication (expected), post this it shows the homescreen of the app which might confuse a user because the user was redirected to save credential not to view existing ones
 3.next one need to click the + and click add entry
4. Verify and save

So you see too many clicks and screens involved..so why not on clicking save it ask for biometric authentication on the same app Page screen like other apps are doing instead of taking to the keepaas app? So on clicking save it should ask biometric authentication and then show a popup to confirm the details and edit if required , on clicking save it should save in the background...no need to take user to the keepass app.
This will help to give a immersive and friendly flow

**Comment by J-Jamet** [comment]
KeePassDX needs to know in which database you want to save the autofill data. For that, you have to choose the database. If you have only one database, you just have to bookmark it with the star to skip the file selection screen.

Unlike other password management applications, there is no server and authentication to connect to a remote machine with a single account, so you have to select the database file for data registration. The biometric unlock is only a help to fill in the password and initialize the file decryption method.

The data save is already done in the background, you can see it if you have a lot of encryption rounds. Once the entry is selected, the program returns to the form and performs the save from the background service.

> no need to take user to the keepass app

How do you want to indicate where to save the data without opening the application?

**Comment by sheikh-azharuddin** [comment]
On clicking save maybe it will show a popup prompt with dropdown list to select the database and edit other form fields if required

The actual flow is quite long...let me prepare a video then

**Comment by sheikh-azharuddin** [comment]
Ok I compared it with bitwarden..it is taking to the app and asking biometric authentication same as keepass but next screen coming is directly add item screen with all data prefilled

Here in keepass post biometric authentication it is taking to homescreen and then user need to click add item button...even in that screen title is not prefilled..one has to fill that and click save

So i feel this intermediate homescreen can be removed

**Comment by J-Jamet** [comment]
The registration button from autofill cannot be changed as it is part of the autofill service of the system. 
https://developer.android.com/guide/topics/text/autofill-services#save

**Comment by J-Jamet** [comment]
To sum up:
 - Do not ask for the location of the entry creation, so I guess save to the root group. People who want to select an existing entry or another location should also be able to do it, so it should be an option in the settings.
 - Automatically fill in the title. Which data do you want to fill in? For a website, truncate the url to keep the domain and for an application the package name?

**Comment by J-Jamet** [comment]
Normally the fields you have filled in, like the password and username are already pre-filled in registration mode, otherwise it's a bug to be fixed.

**Comment by sheikh-azharuddin** [comment]
> To sum up:
> 
>     * Do not ask for the location of the entry creation, so I guess save to the root group. People who want to select an existing entry or another location should also be able to do it, so it should be an option in the settings.
> 
>     * Automatically fill in the title. Which data do you want to fill in? For a website, truncate the url to keep the domain and for an application the package name?

For the first one maybe you can add one dropdown selection button( to choose the location )to the add item screen this will remove one step to go to the home screen

For title not necessarily but yes it can be prefilled with the domain name anyway user can edit

**Comment by J-Jamet** [comment]
> For the first one maybe you can add one dropdown selection button( to choose the location )to the add item screen this will remove one step to go to the home screen

I don't understand this. What is the "add item screen"? there is only the group screen that allows to see the entries and groups inside the current group. I don't understand the point of adding a dropdown menu in addition to the add button.

**Comment by sheikh-azharuddin** [comment]
Add item in bitwarden and add entry in keepass..
Add item screen in bitwarden has the option to select the folder/group whereas in keepass add entry menu there is no option to select the folder or group..

When save button is clicked from browser bitwarden is taking user directly to the add item screen whereas in keepass it is taking to the homescreen where one needs to click add entry thus adding another screen with 2 extra clicks!

Try both please and check the behaviour when it giving the prompt to save the credential.

I tried to capture video but coming blank

**Comment by J-Jamet** [comment]
> Add item in bitwarden and add entry in keepass..

I do it all the time.

>  in keepass add entry menu there is no option to select the folder or group..

The "add" button adds an entry or a group to the current location in KeePassDX. So, it is completely possible **and necessary** to choose its location.
Bitwarden uses a tag system they call folder to group items of the same type into a linear storage but not a tree. It's not real folders since it is not possible to put folders in folders, am I wrong?

So having to select a location in KeePassDX adds a click, I understand that. That's why I suggested above to save a new entry in a default folder that we would set in the settings.

For the other click, as I also explained, KeePassDX cannot use a server-based authentication system so we have to open a database file specifically.

Thank you for proposing viable technical solutions, other than comparing two applications that do not work in the same way because they do not have the same original purpose.

**Comment by sheikh-azharuddin** [comment]
Thanks for being so open and responsive..I am closing this case

**Comment by J-Jamet** [comment]
No problem. I understand that some behaviors are simpler on other applications but the implementation choices are not the same. I think it is possible to choose a default group but it should be done in a subtle way because users would never go to the settings to activate this option.
So maybe with an information bar that would be used to give tips.

**Comment by J-Jamet** [comment]
That's a good question, I honestly don't know. I would need some sample code to see if the launchers have special permissions and how the icon packs are stored but I think they are just icons uploaded to the launcher space so it's like making icon plugins.

The main problem for me is the number of icons, because there will be more and more and I don't want to favor big services by choosing the most popular ones and not the new ones which can be very legitimate too.

And the more there are, the more maintenance it requires. From memory, there were more than 2000 icons during my tests with SVGs, it made Android studio crash even if they are small files. In addition, we have to make an efficient search system which is much more complicated to do with Android than in javascript with Angular.
