### ISSUE TITLE
Dropbox does not update the cache of the provided file

### ISSUE THREAD

**Issue by taifu** [Kunzisoft/KeePassDX#1235]
I use Dropbox to share kbdx file.
I change a password notes on Linux with KeepassXC.
I open the file on Android with KeepassDX Pro (but same with KeepassDX) and I see the older version of the notes.
I open the same file with Keepass2Android and I see the updated version of the notes so this is NOT a problem of Dropbox syncing or whatever else.
I uninstalled and reinstalled KeepassDX Pro and KeepassDX, clearing all data, ecc. but I keep seeing the older version of that notes.

**Comment by J-Jamet** [comment]
> I open the file on Android with KeepassDX Pro (but same with KeepassDX) and I see the older version of the notes.
I open the same file with Keepass2Android and I see the updated version of the notes so this is NOT a problem of Dropbox syncing or whatever else.

I don't understand why you are so adamant about your assumption since it is Dropbox that provides the file data, so it is indeed Dropbox app that is at fault.
The fact that KeePass2Android keeps an internal cache of the file in the app and uses the Dropbox API obviously bypasses the Dropbox app problem.

The problem has already been explained, the Dropbox application cache does not update and provides the KeePassDX application with an old version of files. Please read carefully the wiki and the related issues: 

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
https://github.com/Kunzisoft/KeePassDX/issues/840
https://github.com/Kunzisoft/KeePassDX/issues/342

> I uninstalled and reinstalled KeepassDX Pro and KeepassDX, clearing all data, ecc. but I keep seeing the older version of that notes.

You said it yourself, deleting applications and caches from KeePassDX does not solve the problem, so it is indeed an external problem. If you delete the Dropbox application cache and uninstall it, then reinstall it and reselect the file, it will magically work (computer magic is always tricky :D).

**Comment by taifu** [comment]
> I don't understand why you are so adamant about your assumption since it is Dropbox that provides the file data, so it is indeed Dropbox app that is at fault. The fact that KeePass2Android keeps an internal cache of the file in the app and uses the Dropbox API obviously bypasses the Dropbox app problem.

I was so adamant because I was wrong :-)

> You said it yourself, deleting applications and caches from KeePassDX does not solve the problem, so it is indeed an external problem. If you delete the Dropbox application cache and uninstall it, then reinstall it and reselect the file, it will magically work (computer magic is always tricky :D).

Yep! You are right. Thank you very much.

**Comment by J-Jamet** [comment]
Thank you for your support ;)
