### ISSUE TITLE
Better beta testing before release

### ISSUE THREAD

**Issue by Bugaddr** [Kunzisoft/KeePassDX#1241]
**Is your feature request related to a problem? Please describe.**
Not really a feature-related-to-problem but a suggestion,.

**Describe the solution you'd like**
Formation of beta testing team and better pre-release security, for example before every release cycle we can provide a beta release for whatever new features were added so that large error and glitches can be mitigated/addressed by beta testers before final product reaching end use.

**Describe alternatives you've considered**
Maybe extensive automated testing can be done.

**Comment by J-Jamet** [comment]
I do not understand the question, 
There is already the beta present on the Play Store. What you describe is already present, do you really believe that I put in production without testing?

If you want to set up a dedicated test team, you will have to find some friends because I can't already pay myself on this project while I am doing the design, the realization, the development, the tests and the deployment.

If you want to add unit tests, I'm waiting for your pull requests. ;)

**Comment by Bugaddr** [comment]
> I do not understand the question, There is already the beta present on the Play Store. What you describe is already present, do you really believe that I put in production without testing?
> 
> If you want to set up a dedicated test team, you will have to find some friends because I can't already pay myself on this project while I am doing the design, the realization, the development, the tests and the deployment.
> 
> If you want to add unit tests, I'm waiting for your pull requests. ;)

Thats actually good, sorry for being unaware about beta testing on playstore (i dont use any google service). I want to ask if its possible in some way to make testing more usefull (in the sense better communication with testers) like we can use matrix/irc/telegram room's for better connecting with testers and to get immediate response regarding tests. Also i knew that automated testing cost money but still that was just one of alternative that we will not considering currently.

**Comment by J-Jamet** [comment]
I don't really see the point if there are too few people who normally give feedback. On the Play Store I have very little feedback on the features that have just been implemented, even though that's what the beta is for.
I don't know who's going to be interested in going through live messaging for that kind of thing, especially since it complicates the ticket tracking.

**Comment by Bugaddr** [comment]
> I don't really see the point if there are too few people who normally give feedback. On the Play Store I have very little feedback on the features that have just been implemented, even though that's what the beta is for. I don't know who's going to be interested in going through live messaging for that kind of thing, especially since it complicates the ticket tracking.

Yes, that sounds good. Well can you please confirm which versions (version number) you are releasing as beta on playstore. And if those are diffrent versions than what we are able to see on fdroid and github release then is there any possiblity to get them here. 
Thanks

**Comment by Bugaddr** [comment]
> I already tried to put beta versions on F-Droid but users don't want recommended test versions (which is normal).#1080
> 
> So for the moment, I can't make a TAG in the code to indicate a beta version because it would cause an automatic compilation of the code by F-Droid. Currently, after a fix in the "release/[version]" branch, I simply change the versionCode of the Manifest to increase the version and compile to a beta.
> 
> As there is no TAG, I can't make a downloadable package on github so I can only propose an external folder where I will upload each beta manually.

Cool that sounds good, i am closing this issue by quoting this message as conclusion.
