### ISSUE TITLE
Deafult Keyfile option

### ISSUE THREAD

**Issue by muchowsky** [Kunzisoft/KeePassDX#1295]
Hey,

I thought it would be nice to have option to set up default keyfile for every new db.
I had a problem with many conflict files on my cloud 
KeePassDX doesn't refresh database every time i access it so it can generate conflicts while syncing database to cloud and because of that is is easier for me to access database from my sync app but every time i have to access newer version of my db this way i have to add my keyfile and it's really annoying
I would really appreciate it if you add it to your app

**Comment by J-Jamet** [comment]
> I thought it would be nice to have option to set up default keyfile for every new db.

It is already possible to put a key file for each database created or when changing credentials.

> I had a problem with many conflict files on my cloud

In this case, you have to check with the Cloud service that manages the synchronization.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

> KeePassDX doesn't refresh database every time i access it

Of course it does, KeePassDX can only load data that the URI sends to it and cannot create data from scratch because there is no cache once the database is locked.

> so it can generate conflicts while syncing database to cloud and because of that is is easier for me to access database from my sync app but every time i have to access newer version of my db this way i have to add my keyfile and it's really annoying

Here too, you have to check with the Cloud service that manages the synchronization.

Settings - App settings - Remember keyfile locations

> I would really appreciate it if you add it to your app

This issue should be in [FileSync](https://github.com/Kunzisoft/FileSync) app
