### ISSUE TITLE
Add automatic synchronization to WebDAV or other cloud server

### ISSUE THREAD

**Issue by Squarehead365** [Kunzisoft/KeePassDX#1300]
Hello. I love this program, and use it on a daily basis. But i encounter one problem. 

This is offline password manager, and it doesn't stored on any server, so you have to backup your password database manually to your own server. But here's the problem 

The database always changing when you create, change, or delete passwords. And to keep it updated you need to manually backup the datebase to your cloud each time you change something in it. And this is difficult, and you can forget to backup your file, because its fully manually. 

But another keepass fork named Authpass has automatic synchronization feature, which automatically backup your password database, and i be grateful if you add this feature to keepasDX, because its my favorite fork and i don't want change it to another

Thanks

**Comment by J-Jamet** [comment]
> This is offline password manager, and it doesn't stored on any server, so you have to backup your password database manually to your own server. But here's the problem

You haven't read the documentation, nor the other issues.

An editor only needs access to the content of the file and does not need to know if it is stored online, in a cloud or locally.

Keepassdx can very well access online content if the file provider has access to online content.

Please read : 

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

https://github.com/Kunzisoft/KeePassDX/issues/342

https://github.com/Kunzisoft/KeePassDX/issues/840

> The database always changing when you create, change, or delete passwords. And to keep it updated you need to manually backup the datebase to your cloud each time you change something in it. And this is difficult, and you can forget to backup your file, because its fully manually.

Nothing prevents you from using a well-made cloud sync application that does it automatically. (The problem is that there are not many of them)

> But another keepass fork named Authpass has automatic synchronization feature, which automatically backup your password database, and i be grateful if you add this feature to keepasDX, because its my favorite fork and i don't want change it to another

I won't add a cloud API in KeePassDX (nor Internet permission) which is not made for that because it would become a file editor.
https://github.com/Kunzisoft/FileSync

The Filesync application will be made for this purpose.
https://github.com/Kunzisoft/FileSync

I appreciate that you like KeePassDX but the functionality you are asking for requires a new application dedicated to synchronization.

**Comment by J-Jamet** [comment]
If you want to discuss it, we can do it on a thread of the Filesync project.

**Comment by Squarehead365** [comment]
Thanks for answering me, i fully understand you. 

You can close this tread
