### ISSUE TITLE
Remove select shared info for Magikeyboard

### ISSUE THREAD

**Issue by Dees7** [Kunzisoft/KeePassDX#1304]
**Describe the bug**

In  beta version 3.4.2 MagicKeyboard doesn't select item after click. Only show item as if it openned directly in app.

**To Reproduce**

1. Go to any imput form
2. Switch Keyboard onto MagicKeyboard. 
3. Click "key" to select Item. And Unlock Database.
4. Find Item and click it
5. It openned to view (with history\lock\etc buttons in the bottom) 

**Expected behavior**

After 4. go  to back app and type login\pass

**KeePass Database**

 - Created with: Windows KeePassXC 2.7.1
 - Version: 2
 - Location: local
 - Size: 15M
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.4.1
 - Build: Free
 - Language: Russian

**Android:**

 - Device: Xiaomi T9
 - Version: MIUI 12.0.5
 - Android 10

**Comment by J-Jamet** [comment]
Wiki : https://github.com/Kunzisoft/KeePassDX/wiki/Magikeyboard

Point 2 : Check that the setting Settings → Form filling → Magikeyboard settings → Select shared info is enabled, otherwise the information will be searched but not returned to the Magikeyboard.

Several people have already thought it was a bug. I will probably remove the setting and make it the default.
It was present because it allows you to search without filling the keyboard but I don't think many users use this feature.
