### ISSUE TITLE
KeePassDX Pro renamed? 

### ISSUE THREAD

**Issue by shneoh** [Kunzisoft/KeePassDX#1317]
I wish to use the app only realized it is gone!  May I know what's happening?

**Comment by J-Jamet** [comment]
Linked to : #1257 
 
I realize that too many people are lost since the switch from KeePassDX Pro to Contributor Pro.

This change was made to facilitate the deployment of the application which was done in 2 times initially. This was very time consuming. And also allows to unlock content on other applications in the future.

You just need to install Contributor Pro next to KeePassDX to have access to KeePassDX Pro.

But maybe I will rename the application again to KeePro to make it more like the old one, I would like your opinion on the name.

**Comment by anonymous-user** [comment]
You could rename it to something like KeePassDX Pro Unlocker.

**Comment by J-Jamet** [comment]
> You could rename it to something like KeePassDX Pro Unlocker.

OK for me, It is surely less disturbing indeed.

**Comment by J-Jamet** [comment]
The only problem is that the name is truncated in the icon selection

**Comment by shneoh** [comment]
Finally I realized myself the KeePassDX will show in PRO version with the Contribute App together.  I have removed the non-PRO version just to keep my mobile clean, after I reinstalled the KeePassDX and I able to get back what I suppose to have.

Yes, this is kinda confusing and chaos to users like me.  The App concerns a high-secured APP category and suddently it disappeared from my mobile and showing a never seen UI.  I admit I am totally freakout at the moment.

I would suggest **the naming actually isn't that important** but you should have some way to **mention the changes and get all user informed**.  I did search through everywhere but can't get any idea then only come over here to log a bug report.  :(

Anyway, case close to my part.
