### ISSUE TITLE
Timeout configuration does not work

### ISSUE THREAD

**Issue by rutmay** [Kunzisoft/KeePassDX#1330]
If the app is in the background for a few seconds, I see the password prompt again,
even if I disable the timeout completely.

**To Reproduce**

1. open database
2. switch to another app
3. back to keepassDX
4. password prompt again. Sometimes this even happens when I'm busy with the app

**Expected behavior**

database should remain unlocked for as long as I specify in configuration

**KeePass Database**

 - Created with: Windows KeePass XC 2.7.1
 - Version: [e.g. 2]
 - Location: local, sync with syncthing
 - File provider
 - Size: 28 kB
 - Contains attachment: no

**KeePassDX:**

 - Version: 3.3.2
 - Build: libre
 - Language: german

**Android:**

 - Device: Gigaset 4
 - Version: Android 11

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
Can you update the application to its latest version (actually 3.4.4) and retest?

Are you also sure that you have not defined the other timeouts of the application?
`Settings -> App settings -> Timeout`
`Settings -> Form filling -> Magikeyboard settings -> Timeout`
`Settings -> Form filling -> Clipboard timeout`

The lock is of course triggered when only one of these timeouts expires.
https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-did-the-app-lock-before-the-timeout-duration-has-elapsed

I just checked and I don't have a problem. Otherwise, do you also have a battery optimizer?

Linked to https://github.com/Kunzisoft/KeePassDX/issues/1322

**Comment by rutmay** [comment]
After deinstallation and reinstall with the latest version everything works fine, thanks a lot!
Just wonder why it didn't update itself.
