### ISSUE TITLE
Touch /input not working

### ISSUE THREAD

**Issue by Robin-Sch** [Kunzisoft/KeePassDX#1367]
**Describe the bug**

Scrolling or pressing buttons in the app does nothing, like my finger isn't detected. I already tried force closing and also tried clearing the cache but neither fixed it. Now I'm stuck at the home screen and can't open my database.
I don't think it's a problem with my database since it does work with keepassxc (on my PC) and other keepass android app(s).

**To Reproduce**

I have no idea how this happened, but it suddenly just broke. Clicking on any button or scrolling does nothing at all.

**Expected behavior**

The button and scrolling should work

**KeePass Database**

 - Created with: KeepassXC (latest?)
 - Version: 2
 - Location: File system
 - File provider: I have no idea what this is
 - Size: 60kb
 - Contains attachment: no

**KeePassDX:**

 - Version: 3.4.5
 - Build: F-droid?
 - Language: English

**Android:**

 - Device: Samsung
 - Version: lineageOS (android 11)

**Comment by Robin-Sch** [comment]
It was because of the app "dimmer", which lowers the brightness of my screen using an overlay. I think that overlay caused the issue and disabled the input for keepassdx (but for other apps it works fine).

**Comment by FractalU** [comment]
@Robin-Sch I'm experiencing the exact same issue except I use `Night Owl`, which reduces blue light on night, instead of `dimmer`. All apps I use work with `Night Owl` except `KeepassDX`. Only the touch input isn't responding. Everything else with `KeePassDX` seems to work perfectly fine including the keyboard input for the master password. It looks like this issue has something to do with the modern UI that KeePassDX utilizes. I'm not familiar with this UI at all. For me, it's too early to close this issue, because there is definitely something not right with this UI.

I'm using android 9 from Sony Xperia XZ1 Compact.

**Comment by J-Jamet** [comment]
There's simply a protection feature that prevents foreground applications from capturing events, thus preventing fraudulent applications from reading sensitive information. You can disable it in screenshot mode.

**Comment by J-Jamet** [comment]
In this case, I don't know. The protection obviously works (and therefore prevents tap) if there's an overlay on top of KeePassDX, I don't know the apps you're describing but switching KeePassDX to screenshot mode temporarily disables this protection, if it doesn't work, there must be an other sort of overlay on your Android OS.

**Comment by FractalU** [comment]
@J-Jamet I tested this with another app called `Red Moon` which produces the same issue. This app is available on f-droid but not on google play store.

Red Moon App
https://f-droid.org/en/packages/com.jmstudios.redmoon/

This app requires the advanced permission `Display over other apps` to be enabled. The advanced permission `Modify system settings` is disabled. The `Night Owl` app I described earlier has both these permissions enabled.

I would suggest you to just download the `Red Moon` app from f-droid and test the touch behavior on KeePassDX with screenshot mode yourself while this app is running in background. You can later uninstall this app.

**Comment by J-Jamet** [comment]
Yes, it's normal for this kind of application not to work, as it adds an overlay over the entire screen surface. It's the system that has to manage the screen's colorimetry, and in this case it's the addition of a semi-transparent view on top of the other apps.
As I said, if you want it to work with KeePassDX, set it to screenshot mode.

**Comment by FractalU** [comment]
I say it again. It doesn't work with the screenshot mode enabled on my system. Maybe the issue is specific on my system where KeePassDX doesn't work with touch even if the screenshot mode is enabled. I wanted you to try it out to see whether you can confirm if the screenshot mode is an issue or not. Conceptually, KeePassDX shouldn't work with touch if there is an overlay e.g. blue light filter and it should work if the scrreenshot mode is enabled. Is this really true? Because that's not what I experienced.

**Comment by J-Jamet** [comment]
OK, I've just tested it, it doesn't work with screenshot mode.

**Comment by J-Jamet** [comment]
Here I've confused FLAG_SECURE with filterTouchesWhenObscured implementation but it doesn't change the tapjacking problem : https://developer.android.com/topic/security/risks/tapjacking
I assume that if an application is knowingly on top of another, it can capture events, and this would be a security flaw.

**Comment by FractalU** [comment]
Yeah, I have to turn off `Night Owl` or `Red Moon` whenever I use KeePassDX. There is no other secure way around the tapjacking problem. It's not a big deal for me. At least I know the issue and the fact that screenshot mode was buggy. I'm not gonna use the screenshot mode anyways. I hope that if somebody else stumbles across this issue, then that person has an easier way of knowing what's going on.

**Comment by J-Jamet** [comment]
Screenshot mode is not buggy, It does allow you to take screenshots. I just confused two elements when I mentioned it.
