### ISSUE TITLE
Remove the possibility to create TOTPs

### ISSUE THREAD

**Issue by rebyra** [Kunzisoft/KeePassDX#1384]
KeepassDX is an amazing password manager. However, the possibility to create a TOTP within a password manager kinda ruin the idea of two factor authentication. If an a malicious actor unlock the database not only he will have access to all the password but also to all the TOTPs.

Users should be encouraged to use a completely dedicated app only for TOTPs Luke Aegis.

This is clearly security over usabilty and convenience. I don't know how to feel about it.

**Comment by ouzowtf** [comment]
You don't have to use this feature, you don't get forced. So why should it be removed for everybody?

**Comment by J-Jamet** [comment]
It is possible to use KeePassDX only to generate OTP tokens and it is recommanded to create two databases, one for passwords and the other for OTP generation.

It is written in the wiki since a long time : https://github.com/Kunzisoft/KeePassDX/wiki/OTP#configuration

This is one of the reasons why I don't want to automatically put the TOTP token in the clipboard when the autofill is filled in. https://github.com/Kunzisoft/KeePassDX/issues/553
Removing a feature would be a regression, if you don't want to use it just don't click on the button.
