### ISSUE TITLE
Database doesn't open, says "stream closed"

### ISSUE THREAD

**Issue by thornjad** [Kunzisoft/KeePassDX#140]
On a fresh install of KeePassDX, I tried connecting to my database via https, and when I try to unlock it, it does nothing except display "stream closed". The same database works on other KeePass applications without issue (such as Keepass2Android).

I tried connecting to a database on my phone, and it worked, but I want to use the network version.

I installed through F-Droid on OxygenOS 5.0.3, based on Android 8.0.0

**Comment by J-Jamet** [comment]
Thanks for the feedback, unfortunately remote connections and sync are not yet implemented in the code. It is obviously planned but the developments are not finished, I can not yet compete with KeePassDroid which has years of existence whereas I am there only for a few months! ;) But I will do my best to optimize and implement as soon as possible!

**Comment by thornjad** [comment]
Oh sure, no problem! I didn't realize how young this project is! 

In the meantime, then, may I suggest disallowing network addresses to be entered? Or just prompting a popup saying something like "coming soon"?

**Comment by J-Jamet** [comment]
You're right, I'll put a warning if I don't have time to do it before the next release. Thank you for the suggestion.

**Comment by GuyFromMars365** [comment]
@J-Jamet Have you considered collaborating with Brian Pellin of KeePassDroid? I love to see the functionality of his app, combined with your UI

**Comment by J-Jamet** [comment]
@GuyFromMars365 KeePass DX is a [fork](https://help.github.com/articles/fork-a-repo/) of KeePassDroid, so all KeePassDroid features are in KeePass DX since the first beta. I created this fork because I wanted to correct the architecture of the code, correct the bugs, add the material design and add features that were not present in KeePassDroid. KeePassDroid updates are also very slow so I wanted to speed things up as I wanted. Obviously I had asked Brian Pellin to reuse his work.

**Comment by GuyFromMars365** [comment]
@J-Jamet Your earlier comment made it sound like you started from scratch, but that is great to hear. I bought pro to support the project! I would like to see the copy paste function in the notification bar, like in KeyPassDroid. And I am looking forward to support for accessing databases in the cloud.

**Comment by J-Jamet** [comment]
@GuyFromMars365 Sorry, it was a mistake, I mean keepass2android that uses a different technology. Thank you for buying the pro version, it is very appreciated, I try to do the best to add the features! ;)

**Comment by GuyFromMars365** [comment]
Would you consider Talking with Brian Pellin of KeyPassDroid?

**Comment by thornjad** [comment]
@GuyFromMars365 What would you want them to talk about?

**Comment by GuyFromMars365** [comment]
Collaborating together. Two are better than one, because they can cover
more ground. And, frankly, some devs get burnt out over time (Tasker
original's dev, Chain Fire, etc.). Ultimately, I wished there was one
official KeePass app for android, but since there isn't, it would be nice
to see less fracturing and more unification.

For this I would gladly pay.

On Aug 1, 2018 9:25 AM, "Jade Thornton" <notifications@github.com> wrote:

@GuyFromMars365 <https://github.com/GuyFromMars365> What would you want
them to talk about?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Kunzisoft/KeePassDX/issues/140#issuecomment-409593627>,
or mute the thread

**Comment by J-Jamet** [comment]
A message has been added saying that the link is not recognized.
