### ISSUE TITLE
Cannot open keepass file with keepassdx when using open with: app

### ISSUE THREAD

**Issue by Spitskool42** [Kunzisoft/KeePassDX#1408]
In the newest release (3.5.0 beta1) of keepassdx in the fdroid store the 'open with app' is not supoorted by keepassdx anymore? This still works in version 3.4.5.
I always open my .kdbx files by clicking on them (for example in a file browser) and then selecting the keepassdx app to open it dirrectly.
But when using the newest release, the app keepassdx is not selectable anymore in the list of apps to open the .kdbx file.

**To Reproduce**

1. Open a .kdbx file with a file browser.

**Expected behavior**

Not able to select the keepassdx app to open the file.

**Android:**

 - Version: lineageos 19.1

**Comment by J-Jamet** [comment]
There was a bug that detected all file types, the filter now works correctly by offering only the necessary mime-types and file extensions : https://github.com/Kunzisoft/KeePassDX/issues/1211

But since the generic mime-type `application/octet-stream` has been removed, some file managers may not detect files without extensions if the mime-type is ignored.

The default file manager `DocumentsUI` doesn't seem to handle mime-types but only file extensions.
With [`Material Files`](https://f-droid.org/en/packages/me.zhanghai.android.files/) app, there is no problem.

Can you confirm the keepass filename you are trying to detect and the file manager you are using.

**Comment by J-Jamet** [comment]
In fact it seems that the `application/x-keepass` mime-type is not recognized simply because the KeePass file header is not recognized, so can only rely on the extension.
Material Files seems to be just a bit more permissive.
So I'm thinking of doing a rollback.

**Comment by Spitskool42** [comment]
> There was a bug that detected all file types, the filter now works correctly by offering only the necessary mime-types and file extensions : #1211
> 
> But since the generic mime-type `application/octet-stream` has been removed, some file managers may not detect files without extensions if the mime-type is ignored.
> 
> The default file manager `DocumentsUI` doesn't seem to handle mime-types but only file extensions. With [`Material Files`](https://f-droid.org/en/packages/me.zhanghai.android.files/) app, there is no problem.
> 
> Can you confirm the keepass filename you are trying to detect and the file manager you are using.

Hey, thanks for the reply. Thw filename has no spaces in it.
I works on the for example total commander file brower. But not on the default lineageos File app, also not on the oxdrive app.

**Comment by Spitskool42** [comment]
https://github.com/foobnix/LibreraReader/blob/master/app/src/main/AndroidManifest.xml
Librera reader even uses mime type of */*.
