### ISSUE TITLE
Don't keep files opened with Dropbox

### ISSUE THREAD

**Issue by Yanpas** [Kunzisoft/KeePassDX#1409]
**Describe the bug**
If you open files with Dropbox filemanager they get saved to quick-open list. However if kdbx file was updated on another host - you'll get a conflict. Probably it's a bug on dropbox side.

STR:
* KeePassDX: Open databse inside dropbox folder
* KeePassDX: Close it
* Open kdbx databse on some other host and update it
* KeePassDX: Open the same database using Recent list
* KeePassDX: update it and hit save
* You get a conflict inside Dropbox

Last time KeePassDX even uploaded db file with size 0 bytes, after showing me some error. That shouldn't happen at all.

**KeePassDX:**

 - Version: 3.4.5
 - Build: [e.g. Free]
 - Language: ru

**Android:**

 - Device: Galaxy S22
 - Version: 12

**Comment by J-Jamet** [comment]
The conflict problem comes from Dropbox and has been explained in the wiki. https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

> Last time KeePassDX even uploaded db file with size 0 bytes, after showing me some error. That shouldn't happen at all.

This happens because there may be a state that prevents saving. I can't do much about it, but version 3.5.0 adds a temporary memory that prevents saving in case of an exception.

**Comment by Yanpas** [comment]
Nevertheless the problem exists, let's just don't save `dropbox` URIs in the recent list?

**Comment by J-Jamet** [comment]
Why check the URI type? If the problem is solved on the Dropbox application, or the URI id is changed, then we'll have to change the behavior in KeePassDX again, and we'll have to do it for all applications one by one, it's not an option.
The purpose of using SAF is to unify the process, the bug is not on KeePassDX side. The creation of an application that manages conflicts is already under study : https://github.com/Kunzisoft/FileSync
You can disable the URI history in the "Settings - App settings - History" section.
