### ISSUE TITLE
QuickUnlock / Advanced Unlocking

### ISSUE THREAD

**Issue by vertigo220** [Kunzisoft/KeePassDX#1417]
I have a few points/issues/suggestions/questions regarding QuickUnlock/Advanced Unlocking (QU/AU):

1) I almost immediately abandoned this app after looking through the settings and not finding such an option, as it's a requirement for me, since otherwise I'd have to type an extremely long password that requires switching the keyboard back and forth between letters and numbers and symbols every time I need to access the database, which just isn't feasible. While I 100% agree with not implementing it in an unsecure way, and am disappointed that K2A, an app I've trusted for years, apparently does so, AFAICT, for all intents and purposes, AU is essentially the same thing, and so not only do I not understand the resistance to using the term QuickUnlock, but I wonder how many users either don't use the app (and continue to use a less secure implementation in another app) or aren't making use of the AU feature simply because of the terminology used.

2) The wiki article on AU is unclear, at least to me, regarding biometric vs device credential unlocking. It says the latter is "less secure than the fingerprint because it only uses the credentials of the device and does not require user authentication in the KeyStore **_for older versions of Android._**" Does that mean it's equally secure for newer versions and, if so, which ones? I prefer _not_ to use biometric both because historically its security has been questionable and because the scanner on my phone (and pretty much every other Android device I've used with one) is a POS.

3) The wiki also says it's only recommended to use device credential unlocking if using a second factor. I use a keyfile, so I assume it's secure then, though I'm still not sure if it's as/less/more secure vs biometric even with that. It's also not clear why a second factor magically makes it ok to use this method when it's not recommended otherwise. I assume it's because someone with access to the device and the knowledge to defeat the device credential unlocking (which I assume exists due to the recommendation against using it) wouldn't know about the keyfile and so still wouldn't be able to access the database. Is that correct? If that's not the case, I'm curious what makes a keyfile so special in this case, and if it would be possible to have a separate setting for remembering the keyfile, so it won't be remembered for entering the master password but will be remembered and automatically used when using AU.

4) When unlocking with AU (at least for swipe pattern, though I assume it's the same for PIN), it should ideally automatically accept it once done, instead of requiring the user to press "Continue," similar to how the phone automatically unlocks when entering the pattern and doesn't require the user to swipe it then press continue.

5) If AU is enabled and the database has been configured with it, it should automatically prompt for the pattern/PIN/fingerprint when opening the app instead of showing the password entry screen and requiring the user to press the button at the top above the "Open the advanced unlock prompt to unlock the database" text. IOW, that prompt should be automatically displayed as if the button was pressed.

6) This has been mentioned in another issue, but just for completeness WRT AU, disabling it and requiring the master password after a customizable number of incorrect attempts is, IMO, mandatory for this feature to be truly secure.

**Comment by J-Jamet** [comment]
1. I didn't want to use the same terminology simply because it's not the same implementation. Already during the discussions to compare the two concepts it was complicated, it would have been even more incomprehensible to use the same term for two different features, even if they have the same accessibility goal. https://github.com/Kunzisoft/KeePassDX/issues/102
2. Since Android API 30, the biometric API includes the confirmation code by device credential so it uses the ability of the Android code to automatically check the access rights to the KeyStore according to the device credential.
Before that, it is an independent code that uses the KeyGuardManager (now deprecated https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/biometric/AdvancedUnlockManager.kt#L344), it is the application that did not allow access to the KeyStore. So it is more permissive, that's why custom ROMs before Android 7 can use the device credential and not the biometric unlock because there is a need for an internal certificate of the system to access it. https://github.com/Kunzisoft/KeePassDX/issues/215
So the unlocking by device credential in the old versions is therefore less secure because it does not use the system certificates to access the KeyStore keys with the use of the https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationRequired(boolean) method.
Basically, if you are using Biometric recognition and you don't get any errors, then your system's authentication checks for KeyStore are OK. Otherwise you can use device credential but it's a bit less secure (in most cases, it's because you have installed a custom OS and you trust the code of it.)
3. It depends on the method of attack but it will always be more difficult to recover two pieces of key. It's better to use a key file because it's possible to externalize this file to another storage space, in OTG for example. Or if the attacker doesn't know the file path used for the second factor hash even though he has the main code, he is blocked.
There is nothing magical, I never used this word in the wiki! :D It's always the same thing, it's a compromise between usability and security, in any case, KeePassDX is very flexible, it's up to you to define your security strategy, here they are only recommendations.
4. On my device, no need to do "continue", this behavior clearly depends on the OS of your device, I can't do anything about that.
5. This is the default behavior for a known URI, you just didn't activate the setting: `Settings - Advanced unlocking - Auto-open prompt`
6. https://github.com/Kunzisoft/KeePassDX/issues/1266 This is to be studied.

**Comment by vertigo220** [comment]
Thanks for the response, but I'm still confused on a couple of the points.

1. Valid reasoning for sure for _discussing_ it, but I still believe some change should be made in the app to make it more clear to users that there is a quick unlock function, albeit by a different name. Either AU could be referred to also as QU, there could be a reference about it under AU, there could be a QU menu item that provides a brief explanation of the issue/difference and redirects to AU, or there could be a message when running the app for the first time. As it is, it's just too easy IMO to overlook AU as a QU replacement and think the app has no such feature.
2. Bottom line is I'm trying to determine if, on newer versions of Android (and what versions those would be, though I'm guessing by your answer "newer" is 7+), using the device credentials (e.g. PIN or pattern) is as secure as biometric and, if not, how much less secure it is. I don't want to use biometric, but I also don't want the database to be less secure by not using it.
3. I understand that a key file increases security in general, and I use one for that very reason. What I don't understand is why you say in the wiki that device credentials are less secure than biometric, and so if using them a keyfile should be used. A keyfile will make either more secure than without, but it doesn't make sense why it would make an unsecure authentication method (device credentials) secure, since an attacker that can bypass the device credentials would likely have access to the keyfile, since it's typically going to be stored on the device, hence my use of the word magical, as in device credentials magically go from being unsecure to secure through its use. Just trying to understand the logic so I can decide how I should set it up.
4. -
5. You're right, I hadn't exited the app and come back, I just tested on the main screen. So it does automatically prompt for the pattern, but then that creates its own issue, since I have it set to not remember the keyfile, so when I input my pattern, it attempts to unlock the database and fails since it doesn't use the keyfile. This brings me back to one of my original questions which I think you missed, which is if it would be possible to have a separate setting for remembering the keyfile, so it won't be remembered for entering the master password but will be remembered and automatically used when using AU.

**Comment by J-Jamet** [comment]
1. It's not a quick unlock, that's what I'm saying. The quick unlock is well defined as a part of the password :  https://github.com/JanisEst/KeePassQuickUnlock#overview
But of course I don't mind adding an informative note in the education screens.
2. I don't know how to be clearer, security is a subjective matter, I just give you the technical aspects, it is then up to you to define your security strategy. For Android 7 and higher, the unlocking of the device technically uses the certificate validation of the Keystore, thus the same certificate system as the biometric unlocking. After that, is using a pattern that everyone can see by putting an eye over your shoulder less secure than a fingerprint on a mug that can be duplicated with the right hardware? It is up to you to say it according to the context.
3. It is the principle of unlocking with something that we know, that we are and that we own. The device credential is something you know that can be more easily duplicated by an external person than something you are. Multiplying factors limits an attacker's possibilities. It is possible not to store a key file on the device or simply not to register its location, which is implied. I have updated the wiki to be clearer. 
4. Indeed this is a behavior to be improved, for the moment there is no option to save the KeyFile if the automatic opening of the advanced unlock prompt is activated and KeyFile location not known. We have to open a dedicated issue for that.
