### ISSUE TITLE
Search did not work from the start

### ISSUE THREAD

**Issue by ecki** [Kunzisoft/KeePassDX#146]
After opening my first database the search did not work. After entering a word and pressing enter it showed all Main folders (instead of showing a list of hits or a not found message). I was about to give up, when it suddenly worked. I am not sure if it was simply after some time or opening the db multiple times or if it was by opening the settings screen.

In case the search index is somewhat generated in the background the searach results should at least state so that it may take some retries.

This is 2.5.0beta14-free on ChromeOS (Api Level 25)

**Comment by J-Jamet** [comment]
It was just a bug in the previous version of the  version2.5.0.0beta13 that I fixed in version 2.5.0.0beta14, I think you did the update without noticing. In any case, the search will be refactored to be more intuitive, currently it is still based on the system of the main forked project.
https://github.com/Kunzisoft/KeePassDX/issues/143
https://github.com/Kunzisoft/KeePassDX/issues/26

**Comment by ecki** [comment]
Ah yes possible update. Thanks :)
