### ISSUE TITLE
Please add wide range of crypto to make easier donations

### ISSUE THREAD

**Issue by serrq** [Kunzisoft/KeePassDX#1463]
In order to make easy process of donations it needs these crypto currencies:

• ZEC (Zcash) extremely private
• ARRR (Pirate Chain) estremely private
• XNO (Nano) extremely fast - zero fees
• SOL (Solana) extremely fast
• XLM (Stellar Lumens) fast
• LTC (Litecoin) low network fees
• BCH (Bitcoin Cash) low network fees
• DASH (Dash) fast and privacy-oriented
• XEC (eCash) fast finality and low fees

In this way users haven't to swap what they have in order to make donations. More easy.

Thank your team for this amazing project.

**Comment by J-Jamet** [comment]
There are several currencies with algorithms that I need to study, and I need to take the time to do so. :p 
In other hand, I did not put everything because I believe that not all are equal, there is a part of policy and governance. 

Also don't hesitate to look at layer 2 for fees, lightning is a good entry point for Bitcoin. For the forks of the main crypto chains, it is theoretically possible to use the same address because they use the same generation protocols ([bip32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki), [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki), [bip44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)).
For example, there is no point in generating another address for litecoin.
