### ISSUE TITLE
Data corruption after OneDrive editing

### ISSUE THREAD

**Issue by cmara2505** [Kunzisoft/KeePassDX#1471]
Hi, I'm using KeepassDX v.3.5.0Beta02
I have my password file on Onedrive and I use Keepass for PC v. 2.50 (64-bit)

Error when I update DB on KeepassDX and try to reopen both in KeepassDX and in Keepass Windows

Steps to reproduce:

My file is correctly synchronized to Android and I can open for reading using OneDrive app
I edit a single line on a password entry and save data
close DB
in OneDriveApp i see "just modified" confirming that on onedrive file is updated (is also updated on PC)
go back to OneDrive app on android and reopen file
ERROR: after password input i get message: Failed loading database. Hashes didn't match.

**KeePass Database**

 - Created with: windows KeePass 2.50
 - Version: 2
 - Location: Remote file retrieved with OneDrive app
 - File provider content://com.microsoft.skydrive.content.external/Drive/ID/1/item/RID/https://..............PassDB.kdbx?externalUriType=SendFileForViewing
 - Size: 1 Megabyte
 - Contains attachment: only a couple of small attachments

**KeePassDX:**

 - Version: 3.5.0Beta02
 - Build: Free
 - Language: Italian

**Android:**

 - Device: Galaxy A32
 - Version: Android 13 

Further info: I tried to create a new empty DB on windows keepass, and there are no issues. Because my password db is aged many years what could I do to refresh or update db?
many thanks

**Comment by J-Jamet** [comment]
I see 3 possible problems : 
 - the database has a bad formatting and it needs to be rebuilt. To do that from KeePass on PC, make an XML export and then make a new database with the XML import.
 - there is a synchronization problem in OneDrive, maybe the backup was done while the file was uploaded on the server. In this case, it is a problem of design of OneDrive, you should contact them because it is a very problematic case.
 - there is a save problem for a specific version of KeePass format not identified in KeePassDX. To check if it's really that, it's very simple, copy the file in a local folder then try to open it and save it locally.
Can you perform these tests?

**Comment by cmara2505** [comment]
Hi, sorry for delay in reply, but I had few time to test your kind solution. Now I went for first option rebuilding my DB that isn't very large (less than 1K entries).
After many tests Iwas able to edit a entry on phone and synchronize on PC, so problem was exactly bad formatting as you suggested.
I have still some doubts on process to edit DB on phone:
- open Onedrive
- tap on DB and open with KeepassDX
- edit entry
- save entry
- save DB?
- close DB
- go back to Onedrive
- not always I see file date changed, but if I reopen from Onedrive I see entry with edit, probably because DB is kept in KeepassDX cache? Anyway after some tries DB was updated on Onedrive. Really I didn't understand how this is happened :-)
I'll make some more tests next days
many thanks for your support
Carlo

**Comment by J-Jamet** [comment]
There is no cache as such in KeePassDX, only the database loaded in RAM. If there is a cache problem, it is because the OneDrive application has one. You can read the wiki for more information. https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync
