### ISSUE TITLE
Advanced device/biometric unlock doesn't work

### ISSUE THREAD

**Issue by sbajek** [Kunzisoft/KeePassDX#1477]
**Describe the bug**

It is first time I use this application, I like it a lot, however I struggle configuring quick unlock, I always need to provide full password. My understanding is that behaviour should be different from what I'm getting. There is a chance this is related to Pixel 6a device (?).

Following error appears on open database screen, when I try to use Device or Biometric unlock icon:

```
Invalid operation handle (internal Keystore code: -28 message: In KeystoreOperation::finish 
Caused by:
0: In finish: KeyMint::finish failed.
1: Error::Km(ErrorCode(-28)))
```

**To Reproduce**

1. Go to settings, advanced unlock and configure app with device or biometric unlock
2. Open database
3. Provide database password
4. Use icon on the top to enable device or biometric unlock
5. Error appears

**Expected behavior**

Database should open with device or biometric unlock enabled

**KeePass Database**

 - Created with: Windows KeePass (or keepassXC)
 - Version: 2
 - Location: Google Drive
 - File provider (`content://` URI): content://com.google.android.apps.docs.storage/document/ ...
 - Size: 6MB
 - Contains attachment: No

**KeePassDX:**

 - Version: 3.5.0 Beta01 (F-Droid)
 - Build: libre
 - Language: Polish

**Android:**

 - Device: Pixel 6a
 - Version: Android 13

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment]
It should work on the Google Pixel. Did you install a custom Rom, if so it is likely that the OS you installed does not have the secure certificates to allow the saving of symmetric keys in the Keystore of the device.
Make sure you have a secure way to unlock the device, otherwise the Keystore is not accessible either.

**Comment by sbajek** [comment]
Unfortunately, for some reason I cannot make it work. This is stock Android 13, not a custom one. Build version TQ1A.230105.001.A2, so the newest available. For Screen Lock I use Password, plus Fingerprints. Device is encrypted, bootloader is locked, noting unusual. Please let me know if I can check anything to help with troubleshooting.

Photo of this error message:

![Pixel6a](https://user-images.githubusercontent.com/46690284/212496477-a37dd049-93a7-45b7-9f4b-588f5b988732.jpg)

**Comment by J-Jamet** [comment]
KeyMint is an internal operation on your device that uses a hardware encryption chip. I think there is simply a bug in the encryption system of your dedicated chip. I don't have the Pixel6A on hand right now to test but I'll try with other phones in the same range.

**Comment by sbajek** [comment]
Thanks. Indeed, I repeated my test on my wife's S20FE with Android 13, and it worked just fine. So it _might_ be something related to Pixel 6 line, as they all share the same hardware, apart from screen and camera mainly. It would he helpful if somebody else with Pixel 6/6a/6 Pro could repeat this test to confirm/deny this theory.

**Comment by tnikolaou** [comment]
I just installed the app on my Pixel 6 and unlocking the database using biometrics works just fine for me.
I guess if it was the whole Pixel 6 line more people would have verified the issue by now.
Assuming you already tried the things that are listed in the [errors](https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#errors) section of setting up the Advanced Unlocking, did you try deleting/adding your fingerprint, disabling and setting up the screen lock again on your device?  

Do you use any banking or other financial apps with the fingerprint and have no issues?(they usually include similar functionality so keep in mind that by altering your registered fingerprint or screen lock they might require you to set the fingerprint again if you were using it).  

It is possible just as J-Jamet said that this is simply a faulty secure element or an issue in the trusted execution environment of your device and KeePassDX was the app with which you discovered it.

**Comment by sbajek** [comment]
Thanks @tnikolaou. Yes, I have multiple (including banking) apps on my phone configured to use fingerprint reader and they all seem to work just fine. That's weird, but since nobody else seems to be affected, I guess we can close this issue.

**Comment by dzebrys** [comment]
hi, maybe below would help someone. i've S7 with custom ROM, using fingerprint to unlock phone. when tried to use biometric unclock within this application it fails exactly like described in OP. Then i've checked the settings and tried the other method with DeviceUnlocking->DeviceCredentialUnlocking option enabled which auto disable BiometricUnlocking. With that i was able to unlock database using already stored fingerprint credentials.

**Comment by J-Jamet** [comment]
Custom roms generally fail to implement Keystore certificates correctly, making symmetrical key backup impossible. Biometric unlocking using a client-server system works differently, which is why other applications can work with biometric unlocking. Contact the creator of the rom you're using to ensure that the Keystore encryption certificates can be used.

**Comment by jdrch** [comment]
FWIW, I can't get biometric unlock to work on my brand new, stock, never-rooted Pixel 8 Pro, either. No matter what I do, the app asks me for the full database password, thereby rendering it extremely inconvenient to use.

**Comment by bmle33** [comment]
This issue is not closed.  Oct 2024.

**Device Information:**
OxygenOS 14.0
OnePlus 12 Unlocked Dual Sim
CPH2583
Snapdragon 8 Gen 3 Mobile Platform
16.0 GB Ram
Version Number:
CPH2583_14.0.0.840(EX01)
Baseband Version:
Q_V1_P14,Q_V1_P14
Kernel Version:
6.1.57-android14-11-o-g26041213ac6c
Hardware Version:
CPH2583_11

_What I have witnessed twice now 2 seperate devices..._
When first setup the app works fine with the phone.  Whenever they do an update to bio-metrics or device verification it forces apps to rewrite their keys.  This causes the App and Device to seem like something has changed.  It only happens after system updates to the OS.  Tried deleting the keys from app however I am thinking that something in the system needs to be purged for the app to reinstall keys.  Also try uninstalling the app and reinstalling.  This may cause the purge that you are looking for.

_My case use..._
A Cloud-drive with the Database stored and accessed by multiple devices with private keys on the devices.
This allows for SYNC all information across all devices with no way to access but with the master key.  Simple but effective.

Uninstall with Re installation did not work for me.

**Comment by jdrch** [comment]
@bmle33 Quite a few Android apps drop the previous biometric keys when the biometrics are updated. I don't recall whether KPDX does that too, but I do believe it's a security feature and not a bug. For example, an attacker could force the database's owner to change the phone's biometrics, hoping to access all their apps. This feature prevents that.

That said, key shouldn't drop due to OS updates. They certainly don't on my Galaxy Note9 or S24 Ultra, which leads me to believe this is a OnePlus issue. Have you tried asking in the OnePlus forums, subreddit, or support about the issue?
