### ISSUE TITLE
KPDX can't keep the filepath to even offline synced Dropbox files, which are regular folders? 

### ISSUE THREAD

**Issue by tristansly** [Kunzisoft/KeePassDX#1489]
I have read why Dropbox and onedrive aren't supported, but I like to use dropbox as it was when it was created, where all files are available offline on each system that is synced to my account. I use dropsync an additional app to keep the directory fully synced, why would it need to be compatible if the filename is the same every time, what is going on here? it's like we're gradually being locked out of being able to use our devices. file manager is a core part of a computer operating system, you shouldn't have to download an additional mgr, that just increases your attack surface to involve another app. I guess people are too stupid to have write access to their own phones, so we have to put up with this goose chase. KPandroid does all of this with no problem, but your UI is cleaner and simpler, easy to use while keeping necessary complexity available if needed. I prefer yours, but I have to literally hunt down the same kbdx file over and over again, even though it never moves? that's insanely frustrating. thanks

**Comment by J-Jamet** [comment]
I understand your frustration. I am too, and I get a lot of the same type of messages.

First I think it's a good thing that one application doesn't access files from other applications, it makes it a secure system. 
And it's not a question of stupidity, but a question of code implementation, Dropbox just doesn't provide the data in a perennial way like a content provider should. Instead, it forces to use their API, and KP2A uses this solution.

But to me that means forcing the hand to make a strong cohesion between a service and an app when there is another standardized better solution that is not properly implemented by the cloud app. This is not normal.

Again, a workaround to integrate the API as a plugin is planned in a dedicated file manager application, but I have to give my time to create this solution when it should be native.

Did you contact the Dropbox service and what was their response?

**Comment by J-Jamet** [comment]
As a reminder of the main question: https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by tristansly** [comment]
I guess that's where I get confused. on windows, I don't believe there's
anything special about an offline-synced folder at the os level, it's the
app monitoring the folder monitoring for changes. that shouldn't have your
app dealing with webdav issues , right?

**Comment by J-Jamet** [comment]
On windows, there is no compartmentalization of applications, programs can have access to files as they want if there are associated rights. On Android it's different, applications have a scope of permissions that allow to compartmentalize each external access, and the goal of KeePassDX is to be as secure as possible and to have the minimum of external permission.

If a file is on a local folder on Dropbox means that it is on the device in a place that is only available to Dropbox, Dropbox then provides the data streams to manipulate the file.

KeePassDX is only the editor, it doesn't even know the actual location of the file data. It only knows the metadata and data that are provided by the program that provides the file (the content provider), here Dropbox.
The right way to find this data and metadata is the URI provided by the content provider.

But, for any reason,  what happens if the content provider decides not to give access to the file data anymore? This is where your problem comes in.

You are just using a program that is not doing its job properly. It's a matter of trust with the service. You are just using a program that is not doing its job properly. It's a matter of trust with the service that provides the data, KeePassDX makes the right requests to keep a URI active, but the content provider ignores them.

**Comment by tristansly** [comment]
All of that makes sense to me, and that is what infuriated me about "Dropbox Android." I use DropSync to get around this problem because Dropbox android is the exact opposite of what I the consumer conceive of dropbox to be, offline-accessible synced folders. I am not a software engineer, my background is UX and creative tech, but DropSync is different in that it actually creates that offline, accessible, synced folder pair/set that I need. I assume that DropSync has all those permissions you are talking about not wanting to need, but I thought the point of a simpler KeePass program for Android was that it could open a KBDX archive from a file directory from the OS file browser, which from what you're saying won't exist eventually? Also, I can tell you have talked about this a lot and it is frustrating to explain it again and again, so good on you for maintaining your composure and sanity while troglodytes hurl criticism at your software/baby, and explaining it yet again with patience and grace. I ask because I think this is exactly what is infuriating me about S22 and the newer phones and OSes coming out, and apps like dropbox which pretend to be something but aren't really. Example google drive, which does not sync file folders offline on windows at least and will leave you with an empty file directory and scores of .url files linking to your now forever lost data. I'm sure it exists within Google somewhere, but to you the consumer, or student, in my case, gone forever. I was one of the lucky ones who kept BACKUPS of my supposedly offline folder backups, most of the other people in my class of 2017 University of Washington Go Animal Mascots! gone gone gone. Then they cancelled my degree major/ program so it doesn't even exist anymore. I have a diploma in a subject which no longer exists. Man, fuck whoever made that decision. Anyway, that's why I'm interested. Hope my negative experience is someone else's haha. Don't go into debt to go to college, kids. (THEY TOLD US TO GO TO COLLEGE THE COSTS BE DAMNED)
