### ISSUE TITLE
Wrong file save

### ISSUE THREAD

**Issue by Wjxfi** [Kunzisoft/KeePassDX#1520]
why is everything in the file completely deleted?!
there were all the passwords, everything, and it just disappeared

(The base was on a new flash drive)

I had everything working for a few weeks after the transfer and now the error can not determine the format of the base

And in all file managers the file size is 0 bytes!

your app is not safe!

I didn't do anything to get this error!

please help me somehow :(

**KeePass Database**

 - Created with: keepassdx
 - Version: idk
 - File provider (`content://` URI): it doesn't say
 - Size: was about 36mb, now it's completely zero.
 - Contains attachment: yes
 - Russian password on the base

**KeePassDX:**

 - Version: 3.5.0
 - Build: Free

**Android:**

 - Device: poco x3 pro
 - Version: 13.0.5

The problem is not the flash drive. It cost almost ten thousand

**Comment by J-Jamet** [comment]
> why is everything in the file completely deleted?!

Maybe another program tried to access the file at the same time and your file manager does not support simultaneous writing. You need to be more specific about the procedure you followed to get to this state.

> I had everything working for a few weeks after the transfer and now the error can not determine the format of the base
> And in all file managers the file size is 0 bytes!
> your app is not safe!

For what reason? We need a precise procedure, since then we have never encountered the problem during years of tests, so we need to know exactly how to reproduce it. Are you sure that it is not the file manager that went wrong when saving, or another application that accessed the file at the same time, or simply a bad connection of your usb key during saving?

> I didn't do anything to get this error!

It can't be magic, there must have been an action, either automatic or by user.

> please help me somehow :(

The fact that we can detect where the problem comes from (I bet on a stream stop during a save), does not mean that it is a KeePassDX issue. If the problem is indeed KeePassDX, a quick fix will be implemented, but it must already be identified.
In any case, any data lost can only be recovered from a backup, as explained in the FAQ.

**Comment by lu-ckystars** [comment]
user error most likely 🫣

**Comment by J-Jamet** [comment]
The file manager is in charge of managing the backup of data flows, query conflicts, rights management and the delivery / save of data to client applications (here KeePassDX), so it has absolutely everything to do.

Here the question is why the data in the file fell to 0 in your case, in technical terms the most likely explanation is that an exception occurred and the data stream could not be saved to the file.
In KeePassDX, if an exception is raised, the data is not sent through the stream of the content provider which prevents a faulty save (0 byte) of the file.

Maybe it's an unhandled case, in which case it should be identified (but without procedure it is difficult). What I think most likely is that the file manager did not handle an error file state and not send any exception to KeePassDX (as you say, otherwise you would have seen a message) and saved the file anyway. If this is the case, then the file is overwritten but since the error not being raised prevents saving then the file remains at 0.

This is a theory, but then the question is what error and why it is not thrown.

> I use MiX file manager, it supports what you said ... I don't know anything about it (whether it supports what you said)

I don't understand how you can say (twice) that the applications you use correctly support the unknown case without knowing how it works and without having identified the problem.

**Comment by J-Jamet** [comment]
You have not filled in the File provider section (content:// URI). Here it would already identify the file manager used, if it has disappeared, try to activate :  Settings -> App settings -> Hide broken database links
Without this, it will be difficult to have a first entry point for testing.

**Comment by J-Jamet** [comment]
duplicate  : https://github.com/Kunzisoft/KeePassDX/issues/1666
