### ISSUE TITLE
KeePassDX database on android cell phone lost

### ISSUE THREAD

**Issue by MaZoR82** [Kunzisoft/KeePassDX#1536]
Hey there,

I used to put in my passwords into KeePassDX on my android phone. I did not log in for some time and when I now tried to get to my database, it would not show up at all. Also the search on my cell phone for the .kbdx file did not return any results. 

Does somebody know what to do here?

Thanks so much and my best!!

**Comment by J-Jamet** [comment]
> Does somebody know what to do here?

Give more context, because no one can guess what your device is, the versions of applications and software use, without a valid procedure to reproduce your problem. Here a file loss is perhaps due to a cleaner on your system, which deletes unused files after some time, or if they are in a Download folder for example. In any case, no update can be applied on KeePassDX to solve this kind of problem.

**Comment by MaZoR82** [comment]
Hi J-Jamet, that is probably hard to list here. Still, your response was very helpful as I recall that sometimes apps "clean" unused files so I guess that this is what happened. Fortunately, it's no big loss as I was able to change passwords to new ones that are in my new database that I will take better care of. Thanks so much and my best!
