### ISSUE TITLE
Add an auto-update / search for new updates for the github release apk's (if not already done)

### ISSUE THREAD

**Issue by notmentaloutlaw** [Kunzisoft/KeePassDX#1543]
Hello I hope you are doing well,

Some projects have a feature where it searches for updates / auto-updates the app without the user needing to go to github and download the latest update each time. For keepassdx this would be essential as any important security related updates can be notified to each user and the update process is very simple (for those who use the github apks). I understand that f-droid / google play store has this feature however for the people who just want to use the github release and have your release for the apk directly this would be a really helpful feature.

Kind regards,

**Comment by J-Jamet** [comment]
I am not aware that github had an APK deployment system for personal phones. Do you have a link to the documentation for this feature?

**Comment by notmentaloutlaw** [comment]
I think I wrote my description incorrectly. For example, molly (an android application) fetches this file https://github.com/mollyim/fdroid/blob/master/repo/index-v1.json. And then downloads the apks, and the logic of the auto updating feature is in https://github.com/mollyim/mollyim-android/blob/main/app/src/main/java/org/thoughtcrime/securesms/jobs/UpdateApkJob.java. I am not sure exactly how this works but it does allow me to download the apk from github and then let it auto update itself.

**Comment by J-Jamet** [comment]
Basically, the download system you describe is based on in-app code, but there are several cons to that: 
 - It requires internet permissions that I don't want to integrate in KeePassDX for security reasons
 - It also requires maintaining the update code, as it is strongly linked to a single download source
 - I don't see a significant advantage to using an integrated download solution rather than F-Droid but will require a significant development time
For me, this feature is not worth it, there are already deployment applications (F-Droid and Play Store) that are dedicated to managing updates, so the interest is very limited.

**Comment by notmentaloutlaw** [comment]
I understand that, thanks for your input. It would do more harm than good to give the app internet access. For now I think I will just update it manually.
