### ISSUE TITLE
Exception on copy

### ISSUE THREAD

**Issue by lvluozixuemengyanyan** [Kunzisoft/KeePassDX#1550]
Mobile phone brand：vivo X90
System Version：Android13

Problem Description：
Long press and hold the screen to copy the account or note, and it will flash back to the database selection interface.

Hope：Fix this bug

**Comment by J-Jamet** [comment]
I can't reproduce this bug, can you make a video with the screenshot mode enabled? I think the problem is with your OS, I know some users had crashes with some version of Xiaomi. Do you have a crash report to submit?

**Comment by lvluozixuemengyanyan** [comment]
Uploading Screenrecording_20230423_174449.mp4…

**Comment by lvluozixuemengyanyan** [comment]
Due to app restrictions, it is not possible to record videos within the software. The recorded videos are all black screen, but this issue has not been resolved yet. Each time you press and hold the copy content, it will flash back to the database selection interface

**Comment by J-Jamet** [comment]
I'm assuming that the problem is with the OS, as this has been verified several times, so update the manufacturer's overlay.

**Comment by cat0x1f** [comment]
Due to my limited proficiency in English, the information provided below has been translated by ChatGPT.

I have successfully reproduced a particular issue on a Vivo phone running Android 14. Upon performing a long-press on a text box within the application, it results in a crash, reverting to the password vault's unlock screen.

KeePassDX version: 4.0.5. I have already reported this issue to Vivo; however, I also hope that you can directly address and resolve it.


https://github.com/Kunzisoft/KeePassDX/assets/72690879/c1542c4b-a744-4709-a853-a7a8d8b082d1
