### ISSUE TITLE
Onedrive corrupts files after moving an entry to another folder

### ISSUE THREAD

**Issue by aisbergde** [Kunzisoft/KeePassDX#1561]
**Describe the bug**

I moved some topics to another folder, using cut and past. KeePassDX saved the file automatically.

The file is located on OneDrive. Then I tried to reopen the file, but it is corrupted. It can't also be opened using another KeePass App.

OneDrive has a version history and it should be possible to restore an older version. But on Android it is not possible to access the file history. And trying to use the web access on a smartphone is not possible, it is redirected to the android app. I will need desktop PC access to restore an older file. This would be a major issue if on the road only using Android devices.

**To Reproduce**

cut an item in the root folder
insert it into another folder
optional: do the same thing for some more items
check somehow, if the file is still OK. For example note file size before and after this operation

**Expected behavior**

database files should never be corrupted, when something is saved. Only a proper version should be saved. And until this isn't successful, it should be possible to restore the previous version.

Maybe the app should keep the old file or a copy of the old file, then save a new version, then check if the new version is valid and only in this case switch the new version against the old version. It should always be possible to have a non currupted version.

**KeePass Database**

 - Created with: decades ago on Windows [e.g Windows KeePass 2.42]
 - Version: latest, can't check because corrupted now
 - Location: onedrive
 - File provider
content://com.microsoft.skydrive.content.external/Drive/ID/1/Item/RID/xxxxxxxxxxxxxxxx/Stream/1/Property/ggoertz.kdbx?externalUriType=SendFileForViewing
 - Size: now it is 9.5 MB, Maybe it was bigger, but I don't know
 - Contains attachment: no

**KeePassDX:**

 - Version: 3.5.1
 - Build: Free
 - Language: German

**Android:**

 - Device: Poco M4 Pro
 - Version: 12

**Additional context**

**Comment by J-Jamet** [comment]
I will repeat it even though it has already been written many, many times. KeePassDX is only a file editor, try to see it as a more complex notepad. By its nature, it only sends data to the file manager which takes care of backups and synchronizations.

Here you use Onedrive (a very bad choice [as you can see)](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#file-manager-application), so OneDrive is in charge of detecting if a file is backable, checking the status of the file and its location and correctly managing the writing.
If there is an error, Onedrive is also responsible for raising an error by throwing an exception which is caught by KeePassDX.

KeePassDX on its side, keeps a clean version of the database in memory until the file manager explicitly validates that the save was successful, otherwise a red error banner appears and nothing is modified. This is a normal security feature that has been properly implemented and tested.

But if the file manager has been created without any real verification or respect of the standards and a validation message is sent even if there is a file error, then guess what happens next.

Once again, KeePassDX does its job well at this level, and nothing more can be done here except workarounds with [FileSync](https://github.com/Kunzisoft/FileSync/issues/3). If you want to keep the OneDrive service, contact them so they can do their job properly.

**Comment by aisbergde** [comment]
Maybe, OneDrive is a (very) bad choice, but I need a way to synchronize KeePass database on different devices. And OneDrive has versions, so in case of issues I can restore an older version. In this specific case, I was able to restore the previous version. But this is not possible on android, only using a desktop PC, via the web frontend. And the web frontend can't be used on Android, if the OneDrive app is installed. I agree, OneDrive is the main issue.

Currently, I have no better idea, what to use instead of OneDrive. Maybe Google Drive would work better?

Maybe an option could be implemented, to create a named copy with timestamp in the name before saving any changes? This will create a lot of copies, but at least it would be possible to open one of them in case of issue. If a specific naming system would be used, old copies could be deleted automatically.

I understand, this should normally do the "file manager". But it doesn't help to know this if the "file manger" did not save a proper version and I have no access to a working KeePass database on the Android device because of the file manager issues.

**Comment by J-Jamet** [comment]
> Maybe an option could be implemented, to create a named copy with timestamp in the name before saving any changes? 

KeePassDX cannot create files by itself. It can only send data to a channel that is opened by the application that manages the files by a URI. As I said, it is only an editor.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#how-it-works
