### ISSUE TITLE
Email notification of login +/- two factor authentication

### ISSUE THREAD

**Issue by patarapolw** [Kunzisoft/KeePassDX#157]
Nowadays, I tend to think that fingerprint, or even password, is not that secure. The new security is notification of login, to ask, is that you?

Not to mention at having only one master password could be a security leak.

About 2FA, I think it is not really that helpful if it is on the same device (I installed Keepass DX on my phone), but it could be a useful security option for some.

**Comment by J-Jamet** [comment]
Email authentication is only useful for servers because there is a client / server relationship. Here the database is managed entirely by the client and is not linked to a basic network entity, so authentication by email is not feasible.

Authentication by 2 factors is done with a password AND a key file. You can generate your key file as you wish. Later, there will be the addition of Challenge-Response.
