### ISSUE TITLE
Option to set other template as default

### ISSUE THREAD

**Issue by orbitneon** [Kunzisoft/KeePassDX#1578]
Right now new entries always opens on the "Standard" template.

When clicked "new entry button" we want to land on the template WE choose.

We want ability to change the default.

**Comment by J-Jamet** [comment]
If you want to change the template, it's done dynamically simply by selecting the one you want from the drop-down list once the entry has been created.

Selecting a default template could be added in settings. But first, we have to define a standard format for templates, so that it's normalized between KeePass apps. At present, the default is simply the KeePass program fields without plug-ins. 

_(when you say "WE" do you mean you share your github account with other people? You shouldn't do that, it's not very safe. :D)_

**Comment by J-Jamet** [comment]
Understand that the standard is the official KeePass format. There are normally no templates in the KeePass format; here, it's simply the implementation of a plugin that isn't standardized and needs to be redone. If you don't want to use the standard, you'll have compatibility problems with other KeePass applications.
