### ISSUE TITLE
Saving database with YubiKey breaks plugin key

### ISSUE THREAD

**Issue by j-lakeman** [Kunzisoft/KeePassDX#1616]
**Describe the bug**

saving database with YubiKey as second factor enabled breaks browser integration of database for KeePassXC

**To Reproduce**

1. create database with KeePassXC with YubiKey as second factor
2. sync database to every device needed using Nextcloud
3. pair several pcs with the KeePassXC browser extension
4. save database with KeePassDX after making any change
5. open database with KeePassXC on desktop
6. browser integration is broken, _Key_ field empty, see below screenshot:

![Screenshot from 2023-07-16 07-05-54](https://github.com/Kunzisoft/KeePassDX/assets/101660243/73c71292-96f9-443d-a2d0-12ace4e5b2a7)

**Expected behavior**

browser integration should not be broken

**KeePass Database**

 - Created with: KeePassXC
 - Version: 2.7.4
 - Location: Nextcloud
 - File provider (`content://` URI): `content://org.nextcloud.documents/document/xxxxxxxxx`
 - Size: about 0.4 MB
 - Contains attachment: files embedded in the database

**KeePassDX:**

 - Version: 3.5.1
 - Build: libre
 - Language: English

**Android:**

 - Device: Samsung Galaxy S7 / SM-G930F / herolte: https://en.wikipedia.org/wiki/Samsung_Galaxy_S7
 - Version: LineageOS 19 / Android 12

**Additional context**

Same problem happened with https://github.com/PhilippC/keepass2android syncing through their embedded WebDAV integration.

**Comment by J-Jamet** [comment]
Non-reproducible.
I've just tested with several devices and I have no problem with the database after saving from KeePassDX.

I don't think the problem lies with the app because : 
 - The engine is different between KeePassDX and KeePass2Android, so I don't see why there would be the problem on both apps at the same time.
 - Plugin keys remain available in the database without any problem.
 - Your problem has nothing to do with a Yubikey, it's an unlock mode, it doesn't affect the integrity of a database.

![Screenshot from 2023-08-28 18-58-11](https://github.com/Kunzisoft/KeePassDX/assets/19224038/3377b5c9-81eb-4d9b-98f5-c14ae6b7bc2f)

It's possible that the problem is due to synchronization, so I'll leave you to look into this.
