### ISSUE TITLE
How I can upgrading my database to v4.1 (kdbx) without losing anything?

### ISSUE THREAD

**Issue by serrq** [Kunzisoft/KeePassDX#1660]
I just want push a button. Super easy method. I am not a developer.

**Comment by shuvashish76** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/956#issuecomment-822612207
See **Migration Phase** of the linked documentation.
BTW @J-Jamet I think it should be mentioned in [FAQ](https://github.com/Kunzisoft/KeePassDX/wiki/FAQ) for users.

**Comment by shuvashish76** [comment]
It has to fulfill one of the condition only, for me I used the 1st condition and it worked so never checked other conditions.

Simply add tag to a **group**, save the database and it should automatically update to v4.1.
Make sure
1. It has to be a "Group"
2. That group should contains a "tag" (_type something in the tags field, hit enter to assign a tag_)
![2023-10-11_11-42](https://github.com/Kunzisoft/KeePassDX/assets/48226312/2c71e726-ad84-494d-9c9c-c81de9db596d)

Close this issue if it updated to v4.1 successfully, also change this issue title ~v4~v4.1 so that others can find it easily in future, thanks.
