### ISSUE TITLE
Invalid key blob (internal Keystore code -33)

### ISSUE THREAD

**Issue by 0xShkk** [Kunzisoft/KeePassDX#1670]
**Describe the bug**

Since the newest Samsung update to OneUI 5.1 on Android 13 I receive this error mentioned in the titel when trying to open a DB file with biometric methods like fingerprint unlock. 

**To Reproduce**

Try to set biometric unlock on new databases or try to open an existing one with pre-configured biometric unlock.

**KeePass Database**

 - Created with: KeePassDX 

**KeePassDX:**

 - Version: 4.0.2
 - Build: Free
 - Language: German

**Android:**

 - Device: GalaxyS21
 - Version: Android 13 / OneUi 5.1

**Comment by piouPiouM** [comment]
Hi :wave:, I'm experiencing the same issue

**KeePass Database**

 - Created with: KeePassXC
 - Location: internal file system
 - Size: 2.79Mo
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.2 (Pro)
 - Build: Free
 - Language: French

**Android:**

 - Device: GalaxyS21+
 - Version: Android 13 / OneUI 5.1 (Up to date)

**Additional context**

The issue is reproduced after deleting the biometric link. Since I can no longer create it, the application acts as if I didn't enter my database password and prompts me to enter it before pressing the biometric unlock button.

**Comment by Jolsty** [comment]
Same issue here, samsung s21+, just updated today to one ui 5.1 and it's causing me a lot of problems.

**Comment by Jolsty** [comment]
> Same issue here, samsung s21+, just updated today to one ui 5.1 and it's causing me a lot of problems.

Update:  I managed to fix by clearing all app data and cache. This will reset your settings so maybe you can export your data before doing this

**Comment by 0xShkk** [comment]
> > Same issue here, samsung s21+, just updated today to one ui 5.1 and it's causing me a lot of problems.
> 
> Update:  I managed to fix by clearing all app data and cache. This will reset your settings so maybe you can export your data before doing this 

Can confirm this works. Thanks for the fix mate

**Comment by piouPiouM** [comment]
I managed to fix the problem by following these steps:

1. Open KeepassDX
2. Cancel database opening
3. Go to _Settings_
4. Got to _Device unlocking_
5. Click on _Delete encryption keys_
6. Quit KeepassDX
