### ISSUE TITLE
keyboard issues while writing new entries

### ISSUE THREAD

**Issue by dmework** [Kunzisoft/KeePassDX#1686]
**Describe the bug**

Issue 1:

when I want to write capital characters an select CAPS it write just one chracter and change back same issue while writing numbers

Issue 2:

when I want to delete multiple characters fast it doesn't work I have to delete one character at a time

**Comment by Oliveinparis** [comment]
Please provide the keepassDX version, what phone you are using, what ROM? Because I can't recreate the issue on KeepassDX version 3.5.1 on android 14 CalyxOS.

It's probably an issue with your keyboard and the app reacting differently? Are you using any custom keyboards? Try switching to the systems default to check if the issue still continues.

I am not a developer or owner of this project. Just a hobbyist.

**Comment by J-Jamet** [comment]
The problem must come from #https://github.com/Kunzisoft/KeePassDX/issues/1490 on some devices. I'll do a rollback and find another implementation solution.

@Oliveinparis  is right, @dmework  please fill in the bug report correctly.

**Comment by Oliveinparis** [comment]
> Please provide the keepassDX version, what phone you are using, what ROM? Because I can't recreate the issue on KeepassDX version 3.5.1 on android 14 CalyxOS.
> 
> It's probably an issue with your keyboard and the app reacting differently? Are you using any custom keyboards? Try switching to the systems default to check if the issue still continues.
> 
> I am not a developer or owner of this project. Just a hobbyist.

Tested it on keepassDX version 4.0.4 and also no issues.

**Comment by dmework** [comment]
fixed now in KEEPASSDX version 4.0.5
thank you
