### ISSUE TITLE
Magikeyboard settings strings not translatable in Weblate

### ISSUE THREAD

**Issue by comradekingu** [Kunzisoft/KeePassDX#171]
App Settings → Form filling → Magikeyboard settings

**Comment by J-Jamet** [comment]
It's translatable in magikeyboard module _/magikeyboard/src/main/res/values/string.xml_
It's not added to Weblate because only strings from the app module are added. The solution is to open a ticket for the admin of https://hosted.weblate.org and add strings for each new module (
which will be long) or host weblate on a private server which can be expensive.
