### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by mariush444** [Kunzisoft/KeePassDX#1717]
Virustotal reports trojan in the latest apk

https://www.virustotal.com/gui/file/ba611a38e8a1a49a7f8606b65c5ca4bf4c859f76f0e0daaa6292671d5cf51eb6

**Comment by J-Jamet** [comment]
It's a false positive.

https://www.reddit.com/r/antivirus/comments/17b9c1f/i_dont_know_if_my_phone_is_infected_or_not/

**Comment by mariush444** [comment]
Do you really thing that VT is missleading and don't see difference between files for Win and Andro?

If there is no problem with your then just report it to VT and they verify and change the status. I've done with my apk and now it's OK.

Please, notice that fdroid version is clear.

**Comment by J-Jamet** [comment]
Both free and libre apk were created at the same time on the same device, under the same conditions with github code. I don't see how this can't be a false positive, especially since this is a only a single report from TrendMicro-Housecall and no one else.

> Do you really thing that VT is missleading

Yes, why not?

> If there is no problem with your then just report it to VT and they verify and change the status.

They're checks on hundreds of automatic antivirus programs, so I'm not going to do the after-sales service for them to reassure you. But contact them, I have no problem with that. ;)
