### ISSUE TITLE
Request: Google Drive Sync

### ISSUE THREAD

**Issue by fancsali** [Kunzisoft/KeePassDX#172]
Syncing to Google Drive (and other cloud providers) would make this app a really useful part of the KeePass ecosystem.

**Comment by J-Jamet** [comment]
Linked to https://github.com/Kunzisoft/KeePassDX/issues/100

Real-time synchronization will be developped to display updated items after a first opening, I have to put a real-time update system of the XML DOM containing the data and it's not so simple.

It is up to the file manager to manage the file update with remote servers, which can integrate remote connections. I'm thinking of modifying an existing file manager (like https://github.com/1hakr/AnExplorer) if you really want built-in solutions, but in reality no one is using all existing drives at the same time so I find it better to install 1-by-1 remote access clients.

For those who compare to KeePass2Android, I will not include the APIs of all drives and clouds directly in KeePass DX, because it goes against the encapsulation and all that I learned in programming, I prefer to split the elements to let each application do what it needs to do and avoid network security issues.
More explanations in reddit discussion : https://www.reddit.com/r/linux/comments/8gvcpi/keepassdx_a_new_keepass_client_for_android/

**Comment by Matzeee** [comment]
Syncing with google drive works for me simply by choosing an existing file in my google drive!

It is offered when I open the left menu in the file manager that shows up when I choose to open an existing file. Just as if it was a local file.

Maybe one could point out this option, even though it is not realtime sync?

During a quick test, this worked better than using syncthing.

The only downside is that the filename becomes a cryptic code. And only a fragment of it is shown in the "last opened" box.

Keepass2Android shows the name of the db instead the filename. Maybe you could add an option to show this instead the filename or both?

**Comment by kins-dev** [comment]
> The only downside is that the filename becomes a cryptic code. And only a fragment of it is shown in the "last opened" box.

Well, not exactly.  Encoded into the name is a file revision.  If you edit on another platform, in some cases the filename can change.  This then obviously invalidates the recently opened list and any keys stored with biometric data.  As long as you only modify via KeePassDX and use the others as read only you're fine.  Not really an ideal situation.

**Comment by J-Jamet** [comment]
Generalized in #840 and will use File Sync app https://github.com/Kunzisoft/FileSync. I'm closing this issue.
