### ISSUE TITLE
Database file disappeared

### ISSUE THREAD

**Issue by cornsailing** [Kunzisoft/KeePassDX#1757]
Hello, I am a user of KeePassDX, and I have encountered a serious problem while using it. I hope you can help me solve it.

I am using KeePassDX version 4.0.5, and my Android device is Xiaomi 10, with system version MIUI12.5.8 stable version.

This morning I opened KeePassDX and found that my database file was gone, and the software was blank. I searched for files with .kdbx and .kdb extensions in the file manager of my phone, but I did not find my database file. I don’t know what happened, and I am very worried about whether my password data is lost.

I tried the following methods, but none of them worked:

- Restart the phone, reopen KeePassDX, and still can’t see my database file. 

- Check the recycle bin of the phone, and did not find my database file. 

- Use data recovery software to scan the internal storage space of the phone, and did not find my database file. 

Can you help me get my database file back? This is very important to me, I have a lot of important password data stored in it. If you need more information, please tell me, I will provide it as soon as possible. Thank you for developing such an excellent application, I hope you can solve this problem as soon as possible, thank you for your patience and cooperation.

**Comment by shuvashish76** [comment]
Where you stored your database exactly? Any system cleaner app you use?

I'm afraid nothing can be done here as KPDX is just a keepass database editor, it has no functionality to delete files from the device storage.
In general you should always keep backup copy of your database & store them in safely e.g SDcard, cloud storage etc.

**Comment by J-Jamet** [comment]
I agree with the assumptions of @shuvashish76 
Xiaomi products often come with apps that delete files, telling you that this will free up memory. 
In any case, you should make a copy of your database file : https://github.com/Kunzisoft/KeePassDX/wiki/Backup#keepass-database-backup

**Comment by nhwCoder** [comment]
I have a very similar issue, but I think the file is just not displayed and was not deleted.

[TITLE]  Cant see (all) *.kdbx file(s) in KeePassDX file-dialog (using button 'Open available database')

I use KeePassDX 4.05 downloaded from Google Play Store on and a Lenovo Tab P12 (newest systemupdates newest Android 13).
When I use the Google Files app to open the folder \Internal Storage\Documents" I can see my *.kdbx file.
When I use KeePassDX file-dialog (when using button 'Open available database') i CAN NOT see my *.kdbx file.
PS: I copied the *.kdbx file from Win11 (newest updates) via USB-C cab le to the Android device.

Maybe an internal implemented file-filter is the issue (like it was for https://github.com/Kunzisoft/KeePassDX/issues/1408 filtering some mime-types).

@shuvashish76  Please try to use the native Google "Files" app and open the folder, likely you will see your *.kdbx file is still there and not deleted. Can you confirm?

@KeePassDX-team Can you confirm this?

**Comment by nhwCoder** [comment]
When I move the same *.kdbx file to folder Downloads then KeePassDX file-dialog (when using button 'Open available database') CAN SEE and open this *.kdbx file.

There this file has the FileType "File (BIN)".

Good luck & Thanks in advance for bug-fixing the open-file dialog

**Comment by J-Jamet** [comment]
The KeePassDX application's file display is not restricted at all, and it is normally possible to open any file with any extension. Your problem stems from the file manager you're using.

**Comment by botkero** [comment]
I have a similar problem. I have a Pixel 8 Pro with the latest Android (15). Today I noticed that I can't open my database.

![image](https://github.com/user-attachments/assets/98a74fcd-422a-47e4-81d6-923b1cb82fb5)

I can't find any kdbx file with the Google File Manager. When I plug my device into Windows, I find 2, but they are older.

I'm afraid that I didn't work with KeePassDX on a copy of the actual database and that copy may have been in the cache area of my phone and is now deleted.

Could my guess be correct?

**Comment by J-Jamet** [comment]
Yes, it's possible, you have to be careful about the location of the file linked to the URI.

**Comment by botkero** [comment]
> Yes, it's possible, you have to be careful about the location of the file linked to the URI.

Wouldn't it be possible for KeePassDX to check this (dont know if it out of scope) and warn the user if necessary? It may be an edge case, but perhaps worthwhile for the user experience.

**Comment by c0ntr-all** [comment]
I ran into exactly the same problem: after using this KeepassDX, the database file disappeared. I can't find it anywhere, either through recovery of deleted data, or in any other way. Having stumbled upon this topic, I can say with more confidence that you need to use KeepassDX very carefully. Most likely, it's about him...

**Comment by SGSStore7** [comment]
I encountered what appears to be the same failure mode described in this issue, on Xiaomi device, on September 2, 2026.

In my case the database was a local file in internal storage:

"/storage/emulated/0/KeePass/keepass.kdbx"

There was no cloud provider involved, and Syncthing was not installed/configured for this database at the time of the incident.

I had been using the database normally with KeePassDX. When I opened KeePassDX, the recent database entry was shown in red / inaccessible. I then checked the filesystem and found that the "KeePass" directory still existed, but the ".kdbx" file itself was completely gone.

I do not have a reproduction and I am not claiming that KeePassDX itself necessarily deleted the file. I am reporting this because the symptom is extremely similar to #1757 and because I was able to perform additional diagnostics before making significant changes to the device.

Diagnostics performed over ADB:

- "/storage/emulated/0/KeePass" still exists but is empty.
- A case-insensitive filesystem search for ".kdbx", ".bak", and ".tmp" did not find the missing database.
- I scanned accessible shared-storage files by KDBX magic signature ("03 d9 a2 9a 67 fb 4b b5"), including "Android/media" and relevant application directories. The only KDBX discovered was an unrelated test database in "/Download/Passwords.kdbx".
- Files by Google trash contained no copy.
- MediaStore was queried while explicitly including trashed items. It contained the "KeePass" directory and the unrelated test database, but there was no record for "keepass.kdbx", including no "is_trashed=1" record.
- The phone also has Xiaomi File Manager and Fossify File Manager installed. I cannot determine which file provider or component, if any, was involved in the deletion.
- The filesystem backing "/data" is F2FS with discard enabled, so after discovering the loss I stopped installing recovery applications or performing unnecessary writes.

This was the first time I have observed the problem, so unfortunately I cannot provide reproduction steps.

The especially concerning part is that this was not merely a revoked SAF URI: ADB confirmed that the underlying local database file itself was no longer present.

I had a previous backup, so most of the database can be recovered, but credentials created after that backup were lost.

Given the similarity to this report, I wanted to document a second Xiaomi case rather than assume it was an isolated accidental deletion.

If there are specific KeePassDX logs, Android provider logs, or filesystem events that would be useful to capture if this ever happens again, please let me know and I can configure logging in advance.

This incident also strongly reinforces the usefulness of the automatic local backup / backup-before-save feature being tracked in #2601. A versioned local snapshot created after successful saves would substantially limit the impact of this class of failure even when the underlying cause is outside KeePassDX.

**Comment by J-Jamet** [comment]
@SGSStore7 Thank you for your detailed feedback. And indeed it is a very weird coincidence whether it is twice on the same type of phone.
Unfortunately, KeePassDX logs are not going to do much because they can't detect external changes to the program, they only detect a change with the URI link.

I really recommend installing [Anemo](https://f-droid.org/en/packages/exe.bbllw8.anemo/), this is a good solution to keep a file in a private location. If you think that shared space is not a safe place for your file and think than an external application can delete it, then choose a safe place.

I am aware of the need for a well-designed file manager that allows both to keep a private file in the application and easily synchronized. I'm working on it, but I had to rethink the app because my first approach was too complex for an MVP so maybe I'm going to make a fork.

In all cases, thank you for your analysis. My first assumption would be that the problem comes from a background service that does cleaning on the device, maybe it deletes files after a given time if it is in the Download folder for example.
