### ISSUE TITLE
Autofill Android O

### ISSUE THREAD

**Issue by gggomg** [Kunzisoft/KeePassDX#176]
Good day, is it possible to implement AutoFill based on Android O api for browser integration (Firefox/Chrome/Brave/Edge/etc) to exclude necessity for changing keyboards to enter credentials on sites? 
Thank you for attention and your hard work for community.

**Comment by J-Jamet** [comment]
The autofill is present but it is necessary to improve the algorithm of recognition of the forms for the various navigators. It may take a long time to develop because each browser and form should be tested, it would be necessary to make a table with what works or not and improve the code accordingly.
The "https://github.com/googlesamples/android-AutofillFramework" project can serve as a reference to greatly improve the recognition at first.
If someone can merge source codes it would be great! ;)

Linked to https://github.com/Kunzisoft/KeePassDX/issues/62

**Comment by eji30** [comment]
Agree with browser integration. It's very important that not only will it be visible in apps, but also in the browser.

**Comment by J-Jamet** [comment]
I opened a [wiki page](https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill) for autofill (it will be updated later), other issues are open on the subject, I close this ticket.
