### ISSUE TITLE
PCloud URI gets broken after refresh

### ISSUE THREAD

**Issue by Tripp1e** [Kunzisoft/KeePassDX#1861]
**Describe the bug**

The Database.kdbx cannot be opened due to

Permission Denial: opening provider com.pcloud.content.PCloudDocumentProvider from ProcessRecor....

after having it open and then closing the KeePassDX App.
All Solutions and Workarounds in the Wiki have been tried but they are either non-viable (like constantly having to reselect the file) or did not work.

A possible fix could be setting the path to /storage/5315-3157/database.kdbx which was found out by searching with mix-explorer. However this is not possible with DocumentsUI.

**To Reproduce**

1. Click Open existing Vault
2. Click PCloud Icon
3. Select database.kdbx
4. Open Database with Password
5. Close KeyPassDX Application
6. Open KeyPassDX Application after some time
7. Database cannot be opened.
 > 7.5 Name does not say Database.kdbx, but /documents/{random string}

**Expected behavior**

7. Database opens like normal

**KeePass Database**

 - Created with: [Windows KeePass 2.42]
 - Version: [?]
 - Location: [PCloud root]
 - File provider (`content://` URI): [content://com.pcloud.pcloud.documents]
 - Size: [189kb]
 - Contains attachment: [Yes]

**KeePassDX:**

 - Version: [4.0.6]
 - Build: [Pro]
 - Language: [English]

**Android:**

 - Device: [Redmi Note 10 Pro]
 - Version: [LineageOS 21]

**Additional context**

**Comment by J-Jamet** [comment]
Unfortunately this type of problem cannot be solved from KeePassDX. If you've read the wiki, you'll understand that it's the PCloud application's file provider that breaks the link and raises the exception.

There are three solutions: 
- Reselect the file. I don't know why you say it's unviable, on a computer you do it all the time to select a file from its location.
- Contact the PCloud application developers to change the behavior of the URI channel so that it doesn't close automatically.
- Design an application that contains the PCloud API and better manages exposed URIs -> https://github.com/Kunzisoft/FileSync/issues/6
