### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Grkrz** [Kunzisoft/KeePassDX#1876]
Hi 
Apology for writing here but I could not find the info anywhere.
I am not sure what the below function/option does exactly.

App settings > general> delete password >
"Deletes the password entered after a connection attempt to a database."

**Comment by aaron-randreth** [comment]
Hello ^^

This option is used when you unlock a database. If it is checked, the master password field will reset when you click on the "unlock" button. Meaning you have to type the full password again if you mistyped some part of it. 

When you enter the correct password, this doesn't change anything. 

If you often have typos in your password, having it unchecked allows you to correct the typing instead of typing the password from scratch.
