### ISSUE TITLE
Fingerprint doesn't work on Sony 1 VI (XQ-EC72)

### ISSUE THREAD

**Issue by Gireev** [Kunzisoft/KeePassDX#1892]
**Describe the bug**

I am unable to unlock the database using the fingerprint feature.

**To Reproduce**

1. Open KeepassDX
2. The fingerprint button displays "unavailable."
3. Tap the "unavailable" button.
4. Toasts appears: "Type password and then click the button."
5. Begin typing the password.
6. A toast notification appears: "System error (internal Keystore code: 4, message: system/security..."

**Expected behavior**

The database should unlock using the fingerprint feature.

**KeePass Database**

 - Created with: [Windows KeePassXC 2.7.*]
 - Location: [/storage/emulated/0/Download/Keepass/databasename]

**KeePassDX:**

 - Version: [4.0.8]
 - Build: [Free]
 - Language: [English]

**Android:**

 - Device: [Sony Xperia 1 VI XQ-EC72]
 - Version: [14]
 - Phone Firmware: [69.0.A.2.38]

**Additional info**
I went to "Device Unlocking" and deleted the encryption keys, then reinstalled the app. I am unsure if this is a bug with KeePass or an issue with the phone's software. It start to happen after some software updates and updates of Keepass. Other apps which using fingerprint works fines.

**Comment by J-Jamet** [comment]
It seems that some systems break their keystore after an update. Try rebooting your phone or contact SONY.

**Comment by elvis-chien** [comment]
I have the same device and get the same issue occasionally. Here are some findings:
1. The issue happens only after my phone prompts me to use pin instead of fingerprint to unlock for security reasons 2 or 3 days after I restart it. Other apps don't have the same issue.
2. When the issue happens, it can be fixed by restarting the phone and I can use fingerprint to unlock the database without a problem until my phone prompts me to use pin to unlock again.

**Comment by J-Jamet** [comment]
This is undoubtedly a problem with your OS. I can't solve the problem from the KeePassDX code.
