### ISSUE TITLE
Buffer database instead of downloading

### ISSUE THREAD

**Issue by MichiFr** [Kunzisoft/KeePassDX#1912]
**Is your feature request related to a problem? Please describe.**
No! 

**Describe the solution you'd like**
Each time KeePassDX opens my database it reloads the DB from my NAS again and again.
To be precise it reloads when the KeePassDX decided to close before somehow. I'm using a WebDAV storage for the database file. 

So, I'm would like KeePassDX to buffer the database locally and reloading it only when necessary, comparing e.g. the modification date time, local buffered file compared with remote one. Modifications should be merged into either the database which is newest and reupload again to remote storage. 

Keepass2Android does something similar. This way it does not always have to redownload the database completely. 

In my case the database is large and the whole download and decryption takes some time.

**Comment by pstorch** [comment]
A local buffer/cache would be nice. Also in case of problems. 
I sync my keepass file via Nextcloud. Due to a bug in the Nextcloud client I had to reinstall it.
But then my keepass file was not accessible anymore and I could not login to Nextcloud anymore. Had to use a workaround via the PC.
A cached version would solve this kind of issue easily. A warning could indicate, that the file might be outdated and not sync able at the moment.

**Comment by J-Jamet** [comment]
I'll say it again, KeePassDX is just a file editor. If the synchronization application you're using doesn't have a cache, get another one. It will of course be added to the FileSync project.

**Comment by MichiFr** [comment]
Sorry, but this comment is ridiculous!

Since when is a file system responsible for caching? This is somehow outdated point of view and not everybody uses OneDrive or similar services for storing their files.

Still there are more and more users which save there files on NAS, away from the big player. 

Why would Keepass or Strongbox on iOS offer such a feature and do not rely on the native API pr 3rd party services for buffering?

Because buffering is program logic and not the task of the underlying API alone. Buffering/caching is used for situations when there is no connection to the source. That's it. 

But, hey anyway, you are the boss here and I still like KeepassDX because of its clean UI. 

Nevertheless, there are some missing features that would feature complete KPDX.

**Comment by J-Jamet** [comment]
> Sorry, but this comment is ridiculous!

It's not ridiculous, the debate has already taken place, and that's what the FileSync application is for : https://github.com/Kunzisoft/KeePassDX/discussions/1525#discussioncomment-6596739

> Since when is a file system responsible for caching?

Not a file system, the app sync you use.

> Why would Keepass or Strongbox on iOS offer such a feature and do not rely on the native API pr 3rd party services for buffering?

They're not on Android, and don't have the philosophy of separating application layers.

> Because buffering is program logic and not the task of the underlying API alone. Buffering/caching is used for situations when there is no connection to the source. That's it.

I understand, and KeePassDX wasn't designed for this, it just reads the data from the data stream provided by the URI of the file provider.

> But, hey anyway, you are the boss here and I still like KeepassDX because of its clean UI.

The UI will remain clean thanks to these choices.

> Nevertheless, there are some missing features that would feature complete KPDX.

That's why I separate synchronization functionalities by application layer.
