### ISSUE TITLE
XXE in PwDatabaseV4

### ISSUE THREAD

**Issue by prodigysml** [Kunzisoft/KeePassDX#200]
# The Issue
An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred:
https://github.com/Kunzisoft/KeePassDX/blob/ff6b0eee6c616675bdff853adeb6cb9fd02f2819/app/src/main/java/com/kunzisoft/keepass/database/PwDatabaseV4.java#L444-L446

# Remediation
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet

**Comment by J-Jamet** [comment]
Thank you for this security reply. I will look at the solutions to make a patch. Do you have an example of a kdbx file with a link that will defeat the XML parser?

**Comment by nightbritenitelite** [comment]
Throwaway account, but wanted to put some info out there.

### Overview
KeePassDX (as of now) does not have the required permissions for internet access (not sure about localhost - that is potentially another attack vector if KeePassDX does open itself up in any way over localhost of course).

**As a Side Note:**
I don't have the time right now to create a test KDBX file, but I do know that with the way KeePassDX is handling XML via the DBF (Document Builder Factory), it is in-fact vulnerable to XXE (XML External Entity) processing attacks.

### Hypothetical DOS Attack Example
One such attack would be Denial of Service attack where the app would crash upon attempting to parse a KDBX file. The attack would assume that:
- The attacker has exploited a security whole within the attack vector, which not only includes KeePassDX but everything involving the KDBX file's device storage, device-to-device transferring, all types of access, etc.)
- Using this security whole, the attacker modifies the KDBX file to include something like the following:
```
...
<!DOCTYPE foo [
<!ELEMENT foo ANY >
<!ENTITY xxe SYSTEM "file:///dev/block/loop0">]><foo>&xxe;</foo>
...
```
By referencing a device (/dev/*) that is inaccessible to non-root apps, an exception will be thrown in KeePassDX, causing the app to either crash (if unhandled).

This is just one of many potential attacks and attack vectors that XXE processing allows for.

### Patching the Exploit:
The Android Developer documentation for the [XMLConstants](https://developer.android.com/reference/javax/xml/XMLConstants) class only exposes one feature that we can turn off to prevent this attack. **However**, let it be noted that I have not tested to see if this feature was implemented correctly in the Android SDK. It _is_ possible that the DocumentBuilderFactory's XML parser is not implemented correctly, and that it will still be vulnerable to an XXE-processing exploit, but while possible, it's _improbable_ for this to be the case as it has been implemented since SDK Level 1.

Saying this, I highly suggest that this is checked (or has been checked) before fully accepting the following solution. I also suggest researching more about this before you implement a fix for it and accept the fix as a fully-secure solution.

Nevertheless, here is the solution to be implemented for ALL database versions and their respective classes. The code may need to be refactored and an additional class added to handle this without needing to think about it when supporting future database versions, but this decision is left up to the community.

**The Solution:**
You should use [DocumentBuilderFactory's setFeature(...)](https://developer.android.com/reference/kotlin/javax/xml/parsers/DocumentBuilderFactory#setfeature) to disable XXE processing features like such:
```
DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();

// Disable certain unsecure XML-Parsing DocumentBuilderFactory features
try {
    dbf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
} catch (ParserConfigurationException) { } // Do something!

// The rest is used like normal...
DocumentBuilder db = dbf.newDocumentBuilder(); 
Document doc = db.parse(keyInputStream); 
```

Websites to look at:
[Android Developer's Reference: DocumentBuilderFactory](https://developer.android.com/reference/kotlin/javax/xml/parsers/DocumentBuilderFactory)
[OWASP XXE General Info](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing)
[OWASP XXE Prevention Cheat Sheet](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#General_Guidance)
["XXE defence(les)s in JDK XML parsers"](https://www.blackhat.com/docs/us-15/materials/us-15-Wang-FileCry-The-New-Age-Of-XXE-java-wp.pdf)

**Comment by J-Jamet** [comment]
FEATURE_SECURE_PROCESSING points to unavailable file http://javax.xml.XMLConstants/feature/secure-processing

Can the file be recovered somewhere else?

**Comment by J-Jamet** [comment]
The suggested fix was added a long time ago. There is no reason for the XML to point to an external entity and even if it does (because added by another application, so already had access to the encrypted content before) there is no way to access it from the app that doesn't have permissions.
