### ISSUE TITLE
Uninstall content provider lost fingerprint and recent path to database

### ISSUE THREAD

**Issue by FluidSpirit** [Kunzisoft/KeePassDX#219]
My recent folders now display like this /document/primary:keepass/keepass.kdbx  , it recognizes that it has fingerprint related to it but when tries to auth says "File not found.  Try reopening it from your content provider" .   I try to open it via the open file dialog and it doesnt recognzie that it has fingerprint turned on.   The worst of all is i cant find the master password and i am on a non-rootable Verizon Pixel 2XL.

History: 

I was accessing my database through default /keepass/keeepass.kdbx  

I setup NextCloud so that i could sync the file between devices.   It didnt work as well as i hoped so i uninstlaled nextcloud And this immediately happened.  I reinstalled nextclloud and it unfortuanetly did not help.  

Any ideas would  help, 
I tried to adb shell in and mess with the preferences.xml using run-as to change the recent paths manjually but the app is non-debuggable and i cant seem to figure out how to do it.

**Comment by J-Jamet** [comment]
Hello, KeePass DX uses the content provider of your phone that uses the default file manager. If your file manager loses connection (the link) to the file, KeePass DX will no longer be able to find the file because it keeps in memory the link of the content provider. The fingerprint is only a quick help to open your database, you must in all cases know the main keys (main password / key file). KeePass DX does not use any root feature.
The synchronization of open files is not yet done because you have to manage the writing of several sources at the same time.
In your case, you must open the .kdbx file manually with the master password and reassign a fingerprint.
