### ISSUE TITLE
Fingerprint dialogue blocks locked phone fingerprint recognition 

### ISSUE THREAD

**Issue by JohnVeness** [Kunzisoft/KeePassDX#221]
If:
- a database is locked, e.g. due to a timeout, or if the "Screen lock (Lock the database when the screen is off)" setting is enabled
- and if KeePass DX is the current application
- and if the phone display is then turned off, e.g. with phone power button or timeout

it isn't possible to unlock the phone with a fingerprint. The phone doesn't respond to an offered finger at all, as if it doesn't notice it. I have to use my PIN/pattern instead.

As the same happens with Keepass2Android, I assumed this was just the way things were, and foreground apps somehow blocked the fingerprint sensor.

But I have since used the Signal app, which can also be locked and require a fingerprint, but having that as the foreground app when locking the phone does *not* prevent the phone being unlocked by fingerprint.

Hopefully this can be fixed in Keepass DX.

Many thanks for this app.

**Comment by J-Jamet** [comment]
Thank you for the feedback.
Fingerprint recognition is really not an easy feature to implement because it depends on devices, I will try to reproduce your problem to correct it when I refactor the code of fingerprints. I'm redoing the timeout, these changes may be beneficial for this bug. Thank you in any case for this detailed return, it is very appreciated for development.

**Comment by J-Jamet** [comment]
I completely redid the fingerprint system, it should now work with the S10 +, tell me if it's ok with the version 2.5.0.0beta23?

**Comment by JohnVeness** [comment]
Thanks. Annoyingly, this problem seems to already no longer occur for me. This is with 2.5.0.0beta22 from F-Droid. Possibly the change is that I have upgraded the version of Android on my phone since first reporting the issue.
