### ISSUE TITLE
Check whether recently opened files exist earlier

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#251]
## STR

1. Open some files/DBs.
2. Delete these/move these on file system level.
3. Open KeePassDX again.
4. Click on one of these in the suggested list.

## What happens

I am presented with password/keyfile entering form.

Only after I click "open" it tells me that the file cannot be found.

## What should happen

It should directly check whether the file still exists. If not, it should show an error and possibly also delete it (don't know whether automatic deletion is the best way, however, [so I've asked here](https://ux.stackexchange.com/questions/125061/should-non-existant-files-in-a-recently-used-files-list-be-deleted-without-user))

It could also already check the whole list when opening the app though… :smile:

**Comment by J-Jamet** [comment]
Since version 2.5beta30, there is better recognition of existing files. They are hidden by default in the "Recent Databases" list. The links are not deleted because it is always possible for the user to recreate the link from his file manager. In this case the fingerprint will work again. It is possible to view and delete them by activating the setting (displays a red icon).
