### ISSUE TITLE
Opening speed / Key transformations

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#278]
Before KeePassDX i use since a long time Keepass2Android. When i open my database with KP2A it takes more than 15 seconds to decrypt the database and present me all the entry's. But if i open the same database KeePassDX its decrypted a lot faster (short as 1 second).

Is there any reason for this difference?

BTW: Argon2, 5 iterations, 350MB memory

**Comment by J-Jamet** [comment]
This is normal, the Argon 2 decryptor is not implemented in the same way on KeePass DX and KeePass2Android.
KeePass DX uses code made in C that is optimized for the device while KeePass2Android uses a mono interpreter for deciphering on Android.

**Comment by Offerel** [comment]
I understand. Many thx for clarifying.

**Comment by ouzowtf** [comment]
Just to inform: KP2A will have a better Argon2 performance soon too (see https://github.com/PhilippC/keepass2android/pull/872)

**Comment by J-Jamet** [comment]
That's fine. KeePass DX is not in direct competition with KeePass2Android because it is also open source, if the application is more adapted to your needs you can stay on it.

**Comment by ouzowtf** [comment]
The intention behind my comment was not to say that one is better than the other. Currently I use both KP2A (Webdav, QR-Code plugin) and Keypass DX (looks more modern/polished).

**Comment by J-Jamet** [comment]
I see! :D In any case, the information is relevant, so thank you. I prefer to work on a derivative because it is not the same technology used but it is true that for a user it must be confusing to use multiple applications. KeePass DX has flaws but improving it allows me to learn a lot and check each piece of code (I also prefer to completely leave it offline for the moment because for me online opens security holes, I try to find a solution for the webdav with a separate file manager.)
