### ISSUE TITLE
Could not read database

### ISSUE THREAD

**Issue by alowe67** [Kunzisoft/KeePassDX#284]
Cannot read previously open database on android

**Comment by J-Jamet** [comment]
It's not precise enough. What is the error message? What kind of device? What Android version number? Encryption? Are there any attached files in the database? I've solved issues in development that can corrupt a database, such as a low timeout, or an attached file backup, but I can not handle specific cases without information.

**Comment by alowe67** [comment]
Error message = could not read database
Keepass Dx Pro version =2.5.0.0beta18
Android version = 9
Device = Note9
Encryption = .kdbx AES
Attached files?
The file was downloaded from google drive directly to the device I have also tried linking. 
The .kdbx file was previously opening and no changes were made.

**Comment by Wilker-a** [comment]
this error usually happens when the application fails to read the database.

in the best case, you're simply typing the wrong password or giving a different version of the keyfile that you've set.  
in the worst case, forgotten password, or the original keyfile or loaded database is corrupted.

if neither of these are the cases and it still opens somewhere else, that info should be relevant to mention.

**Comment by J-Jamet** [comment]
The new version prevents the timeout from closing the base during the recording, so there should be no more worries at this level. As @Wilker-a  says, I guess it's a forgotten password if the application can not be opened with another application. Without further information, I can not solve the problem. I close the ticket.
