### ISSUE TITLE
Unable to open database (no errors displayed)

### ISSUE THREAD

**Issue by easthighNerd** [Kunzisoft/KeePassDX#285]
Both on my Nexus 6P (LineageOS 15.1) and Pixel 2 XL (Android 9), I am unable to open my database. It gives the normal messages as if it was opening it, then it brings it right back to do it again.

I have tried clearing cache and data, reinstalling the app, deleting the database and copying it back on (key file as well), and nothing is working on either device. Database opens fine on multiple PCs.

Running latest available version from F-Droid as of writing.

---

Steps to reproduce:
- Open app
- Attempt to load database by either entering password manually or using fingerprint (both while also supplying a key file)

Expected behavior: Password database loads

Actual behavior: Database fails to load without any errors and returns user to unlock database screen

**Comment by J-Jamet** [comment]
Thank you for the feedback, I'm debugging this problem because I noticed it on the version 4.4 of Android. I have not yet identified exactly this issue but it seems that some systems erases the share memory between activities at the end of loading. Which is problematic in our case. I try to do my best to find a solution.

**Comment by J-Jamet** [comment]
The new version should solve the problem
