### ISSUE TITLE
Please change the way fingerprints work

### ISSUE THREAD

**Issue by underlineGalaxy** [Kunzisoft/KeePassDX#322]
I tend to only use fingerprint to log in, generally forgetting the passwords that I put (because thats the whole point of password generators anyway).

So recently I came kn with a flaw with this system: I accidentally typed on the password field and put my fingerprint and... lost all my acess to that database because I store that wrong password. Now I gotta reset all my passwords.

Here are a few suggestions:
- Make it so I can store a fingerprint as a password, like normal passwords and keys
- Make so a fingerprint is only stored IF the password is correct

I think those will solve the issue to those who are more fortunate than me.

**Comment by J-Jamet** [comment]
The master password should not be forgotten, the fingerprint simply allows to go faster but uses the master password internally.
I am implementing the new version of the Biometric API in develop branch and it requires a new workflow, you will not be able to accidentally scan a fingerprint.
I will try to improve the code to save the values in the keystore only if the database opens after the scan.

**Comment by ebenwight** [comment]
In Version 2.5.0 beta 22 (installed from the Play Store, running on a Galaxy S10 ) the behavior of the fingerprint registration interface is problematic. When creating a new database and assigning a password to it any click on the password checkbox or in the password text field causes the fingerprint registration modal to pop up.

In addition to that, when unlocking the new database for the first time the authentication screen also displays a message stating that the database does not yet have a password even though one has been registered.

I'm including this here because it seems closely related to the issue @underlineGalaxy  experienced. However, given that this issue is already in review this may be more appropriately moved into an issue of its own.


**Creating the new db:**  

![Screenshot_20190905-221012_KeePass DX](https://user-images.githubusercontent.com/11949702/64402909-59300080-d02b-11e9-827c-6e32d61626ba.jpg)


**First accessing of the new db:**

![Screenshot_20190905-221103_KeePass DX](https://user-images.githubusercontent.com/11949702/64402917-5cc38780-d02b-11e9-8696-eaf9b9f33043.jpg)

**Note that in this screenshot only a single character has been entered (circled in yellow) into the password field when unlocking the newly createdddb for the first time yet the prompt to register a fingerprint has already appeared.**

![Screenshot_20190905-221154_KeePass DX](https://user-images.githubusercontent.com/11949702/64402923-60efa500-d02b-11e9-86e7-55fcdafba5e3.jpg)

**Comment by J-Jamet** [comment]
I completely redid the fingerprint system, it should now work with the S10 +, tell me if it's ok with the version 2.5.0.0beta23?

**Comment by ebenwight** [comment]
Shall  I reply directly (email) or on the issue itself?

Eben Wight
eben.wight@gmail.com

**Comment by ebenwight** [comment]
~~Shall  I reply directly (email) or on the issue itself?~~  
Nevermind , email replies generate their own comments apparently. 


Re:expected app performance:
I am happy to say that with the beta23 release the biometrics registration and unlock functionality works as expected.

I only tested with password as the master key for the did not use keyfile, but fingerprints were registered by typing in the correct password and then hitting the option to register one. An uncircumcised password generates an appropriate error message, and no password entered disables the button to register a fingerprint. 

I'd say that meets my definition of fixed.

**Comment by underlineGalaxy** [comment]
@ebenwight but does it still register the fingerprint if I type the wrong password?

**Comment by J-Jamet** [comment]
No ;)
