### ISSUE TITLE
Could not read database

### ISSUE THREAD

**Issue by stysk1** [Kunzisoft/KeePassDX#343]
Issue experienced from latest 9/14/2019 update that is not allowing the play store application to read a database created from the app. Possible duplicate of #312 so I'll have to retrieve logs once I'm able to.

Initially, the database was no longer shown in the history and I had to go to the Backups folder to pull in the database and restore it. This led to a never ending decrypting of the database that eventually stopped (when I was sleeping) and did not read successfully. Now the app refuses to read the database and all of my passwords are completely inaccessible.

**EDIT**: Discovered that the update purged all the recent databases and while trying to manually look for them and opening them, only unlocking them via password worked. This error came up when using the fingerprint scanner.

Some useful information:
![Android Info](https://user-images.githubusercontent.com/14318765/65517714-2e5dfd00-deb1-11e9-82f6-7ccaa3249625.png)

![Not loading database](https://user-images.githubusercontent.com/14318765/65517866-62392280-deb1-11e9-9278-3a6c335fc16c.png)

**Comment by J-Jamet** [comment]
Thanks for your feedback.
I completely redo the workflow and backup mode of database history and fingerprints.
It is therefore necessary to resume your original files and redo the fingerprint links for each database.
_Note that the application does not backup database file and I'm assuming the backup folder you are talking about was created by you to make a manual backup of the original file._
If you succeed in reading your database, I close the ticket because it is just a configuration problem.
