### ISSUE TITLE
Group/Folder passwords and encryption while database is already opened

### ISSUE THREAD

**Issue by Wilker-a** [Kunzisoft/KeePassDX#355]
some entries may seem to have more importance than others, which brings us to be more protective about these than other accounts, but separating into different files may be inconvenient.

what if folders/groups could have separate encryptions? so you have to both decrypt the database _and_ the group you wish to access woth another password that is set up

maybe groups, subgroups and entries could be encrypted by default while the database is already opened, which could possibly reduce memory usage and improve security in exchange for loading time?

what do you think? :3

**Comment by J-Jamet** [comment]
A database file is encrypted entirety, it uses an XML formalism internally. If you want to use several encryption algorithms for input / groups, you need to create an extra file for these nodes. It's exactly the same as creating multiple database files.

When your database is open, the nodes are stored in temporary internal memory and are deleted when you close the database. If you want to change the loading time, you have to encapsulate the nodes in a new file and decrease the number of iterations of the derivation key. There is no quick fix for that.

Adding an additional encryption mode to specific entries is of no interest in my opinion because it amounts to integrating one database file into another, which would make it even more difficult to decrypt the host database for no benefit.
