### ISSUE TITLE
Fingerprint not working on Lenovo Tab 4

### ISSUE THREAD

**Issue by ygoe** [Kunzisoft/KeePassDX#379]
I'm using the fingerprint unlock on my Sony Xperia Z5 compact without any issues. But on the Lenovo Tab 4 8 Plus, nothing happens. I'm also not completely sure what the workflow is. It seems to have changed a few times in past versions. All in all, it's very unintuitive. There's no clear instructions on the screen about what I should do to get what result. I'm sitting in front of the selected database and the password prompt. Should I enter the password first, then put my finger on the sensor? Should I push some button? If I push the fingerprint icon, sometimes a dialog opens, sometimes not. Anyway, when I lock the databse and open the app again, I always have to enter the password. Putting the finger on the sensor never does anything.

Android 8.1, KeePassDX 2.5.0.0beta23

**Comment by J-Jamet** [comment]
The fingerprinting workflow was changed only once because the new google biometric API did not support the old workflow.
If it works with your other device but not with your Lenovo it may be just a bug.  I can not test everything because I do not have every device.
I put a built in tuto in the app, but if it is not useful and you do not find it intuitive, I will simply remove it and put a link to a wiki article, I will not have to maintain this part.
It is necessary to push the button to link a biometric recognition to a credential and it is necessary to push the button to read your biometric. (Pressing the button activates the prompt of your device which allows to recognize your fingerprint or your face.)
Currently there is a bug that prevents the activation of the prompt the second time on some devices #363.

**Comment by J-Jamet** [comment]
Is the bug fixed for you with the new version 2.5.0.0beta24?

**Comment by J-Jamet** [comment]
Without feedback I close the ticket
