### ISSUE TITLE
[Warning Security] possible to take multiple screenshot during master password typing

### ISSUE THREAD

**Issue by borrougagnou** [Kunzisoft/KeePassDX#410]
Hello,
I discover some "thing" dangerous:

Creating app who can take multiple screenshot can reveal master password + also Key file...

![Screenshot_20191219-203907](https://user-images.githubusercontent.com/10796546/71204143-b3359880-229f-11ea-9fdc-860330298fc1.jpg)

I don't know why, for each update, I have impression the security weakens...

Keep the database open when you change app isn't secure... why add 5 mins by default ?

Soooo thats all :/

**Comment by J-Jamet** [comment]
- This is not a bug but an improvement. Even if I agree that it is necessary to do it, it is already planned in the next update -> https://github.com/Kunzisoft/KeePassDX/issues/232

- "I don't know why, for each update, I have impression the security weakens..." Tell me why in the code because I can't resolve assumptions !

- You can close the application before changing the app. Just activate the "App settings -> Press 'back' to lock" feature.

- 5 minutes is a good average because the timer updates only when you change the screen. If an entry is changed, typing all fields in 10 seconds is difficult, but you can change it in the options.
