### ISSUE TITLE
KeePassXC compatibility

### ISSUE THREAD

**Issue by rugk** [Kunzisoft/KeePassDX#42]
The new version of [KeePassXC](https://github.com/keepassxreboot/keepassxc) has been released and it features some optional changes of the key file, mostly encryption-related. v2.3.0 now supports "KDBX 4.0, Argon2 and ChaCha20".

So is this app already compatible or does it need to be adjusted?
In any case, I'd advice you to advertise your app also with "KeePassXC compatible" (in Readme, app description, etc.) so users know they can use it with KeePassXC.

**Comment by J-Jamet** [comment]
It need to be adjusted, some settings can't work for now with this new database format and I need to refactor some old code to make it compatible.
I'll add compatibility in the description when it will be refactored.

**Comment by rugk** [comment]
Hmm, but is it possible to open a database, at least?

The tickets you linked, only apply to some specific cases, like creating a database with Argon2. It would, however, e.g. already be good if you could open and edit Argon2 databases.

**Comment by gerardo-junior** [comment]
+1

**Comment by J-Jamet** [comment]
Normally, the Argon2 database can be opened and edited, the algorithm is in the code. But before making any adjustments, I need to refactor all the code of the parser and make the tests. I can't say that it works effectively. (Chacha20 I think not). It wad created in the main project forked.

It works with C and JNI code, and the parser code does not separate the concepts (so not so easy). So I have to separate each concept, then I can manage the options and parameters of each algorithm.
That's why I linked it to other problems.

I try to be quick to solve all the other worries before doing this big piece.
