### ISSUE TITLE
How is 2FA implemented?

### ISSUE THREAD

**Issue by ErbDroid** [Kunzisoft/KeePassDX#430]
I apologise if I missed it, but it says this app does 2FA? I cannot find this, where is it? If not please add this feature, thank you for this amazing app it is really appreciated!

**Comment by Wilker-a** [comment]
if you got it via the F-Droid platform, enable suggestions for unstable releases. if otherwise you got it via the Play Store platform, iirc there is an option for enabling beta releases there on the app page.

**Comment by Wilker-a** [comment]
including here as a separate comment (because notifications)

there should be an option to "Setup One-Time Password" while on the Edit screen.

@J-Jamet this function doesn't seem obvious enough to find. maybe another location should be better. may i suggest you to move to a place right beside the Generate Password button? maybe as the form of an icon? the one of the padlock with the square should be better than the clock, i guess. what do you think? :3

**Comment by J-Jamet** [comment]
@ErbDroid You can register an OTP key (HOTP or TOTP) when editing an entry (only in a V2 database). This will generate a token for the connection with 2FA to the service associated with your entry. 2FA is also used when opening the KeePass database (by using Password AND KeyFile). 

@Wilker-a I am thinking of modifying the interface but it is not very urgent at the moment. Can you indicate which icon visually?

**Comment by Wilker-a** [comment]
@J-Jamet this one :3
![(the image of the icon) a rectangle with a padlock over it leaning to the top-right.](https://user-images.githubusercontent.com/10854855/72248615-81d69100-35ef-11ea-99d8-980abea12291.png)

i thought of this one because of the rectangle remembering a new text field and stuff, and because it is already in the app, so there woudn't be much of a need to look for more icons to include

**Comment by J-Jamet** [comment]
I recreated the interface in the latest version of the application with education screens. Also created an icon specifically for the OTP. It's more accessible. https://github.com/Kunzisoft/KeePassDX/blob/master/art/ic_otp.svg
