### ISSUE TITLE
allow swipe typing when unlocking database

### ISSUE THREAD

**Issue by davebrny** [Kunzisoft/KeePassDX#441]
currently swipe typing is disable when entering your master password (with the keyboard im using anyway, swiftkey). it would make long passphrases a lot easier to input if you could swipe. you also wouldnt have to be as accurate.

i timed myself swiping "correct horse battery staple" and it was almost twice as fast as typing it out normally with 1 hand

**Comment by lukengda** [comment]
This looks to me like a feature request for your keyboard.

It is normal that you can't use feature typing on a password entry field. I tried it with two browsers and two keyboard implementations that have gesture typing. All 4 combinations didn't allow to swipe on <input type=password> fields.

If we would implement a workaround here, more problems would arise like auto complete suggesting you the next parts of your password because it would no longer detect the purpose of the password field.

But I am not the maintainer nor a professional Android developer, just my 2 cents...

**Comment by J-Jamet** [comment]
@davebrny  I agree with @lukengda , this is a feature that is not related to KeePassDX.
