### ISSUE TITLE
Prevent keepassDX from reusing characters on password generator

### ISSUE THREAD

**Issue by Ilithy** [Kunzisoft/KeePassDX#446]
Hi Sir;
_First of all, thank you for your work on KeepassDX._ 

In the password generator, is it possible to add an option to prevent keepassDX from reusing the same characters more than once?

~This would improve the strength of the generated passwords, and make them much more complicated to decrypt.~

Thank you very much.

**Comment by J-Jamet** [comment]
I will add functionality when I work on the password generator. (Add Diceware feature, etc ...)

**Comment by Ilithy** [comment]
I understand that; thank you for your attention to my request.

Respectfully.

**Comment by DPTJKKVH** [comment]
This feature will be useful for password policies that disallow reusing characters or having the same character repeated right after another.

**However** this option won't make passwords more secure! Quite the opposite: If an attacker knows that you won't use the same character more than once the pool of potential characters to try deacreases the longer your password gets.

I try to make an example:
Everyone knows how a brute force attack works. Now lets imagine my brute force device is at _gJ7!_ and currently interating the fifth character. If I know that you won't reuse characters I can configure my brute force script in a that it won't try g J 7 and ! again until those are rotated out.

I this does decrease the time and ressources required to brute force your password and it gets more efficient the longer your password gets. So it works directly against the purpose of longer passwords.

Of course it will never fully eliminate the benefit of a longer password but it does noticeably decrease security, not improve it.

Also it limits the maximum length of the passwort to the size of the character set used. But that is only an issue if you want to use a very long password for some reason.

So all I want to say is: I am pro adding this feature because some password requirements are stupid but please never advertise this as a feature that increases security.

**Comment by Ilithy** [comment]
This decreases resistance to attacks only if the attacker thinks you have done so, and even then, using a very wide range of unique characters (for example, the extended ascii has more than 100 unique characters, if I'm not mistaken), it will take a considerable amount of time to successfully test all possible combinations, don't you think?

**Comment by DPTJKKVH** [comment]
All I said is that it won't **increase** the strength of the password, contrary to what was suggested in your first post, and thus it shouldn't be advertised as such in the user interface.

I never said it would be insecure, especially with longer passwords.

There are very legitimate use cases for your suggestion, like unfortunately designed password policies. So it's a feature worth adding but we should explain to only use it if strictly necessary.

**Comment by J-Jamet** [comment]
> So all I want to say is: I am pro adding this feature because some password requirements are stupid but please never advertise this as a feature that increases security.

I completely agree and it was never my intention to promote this feature, in the idea it would take a global Regex system to handle this kind of case for forms with weird criteria. Honestly, I have not yet thought about this subject which is not urgent at all, we should rather ask the services concerned to remove these criteria.

**Comment by J-Jamet** [comment]
I close this issue, I have not seen any form with this kind of criteria. If it is the case they must be rare and it is up to them to change their password verification.
