### ISSUE TITLE
Shortcut to copy password

### ISSUE THREAD

**Issue by Evidlo** [Kunzisoft/KeePassDX#47]
This application seems to have the same deficiency as KeePassDroid in that it takes far too many clicks to copy a password (click on entry > click pulldown > click copy).

I propose that long-pressing an entry automatically copy the password to the clipboard.

**Comment by J-Jamet** [comment]
It's planned but not priority, another request like this one was made to me in the comments of the Play Store. I'm doing things step by step, the copy button has been added next to each name, password, and additional fields in the latest version, it's now as fast as a long click.
Another things, I don't understand the "click pulldown', it's a swipe because you have many fields in one entry ?

**Comment by J-Jamet** [comment]
Adding code for the copy in the clipboard is dangerous, the current copy features are fast enough. Linked to #https://github.com/Kunzisoft/KeePassDX/issues/139
