### ISSUE TITLE
Clarify wiki questions

### ISSUE THREAD

**Issue by comradekingu** [Kunzisoft/KeePassDX#474]
Reworked the wiki. Some issues remain.

1. FAQ says KeePassDX is beta, though I think it isn't anymore?

2. It also says all versions are the same (except for themes)
However, [OTP](https://github.com/Kunzisoft/KeePassDX/wiki/OTP) says 
"This special algorithm has been implemented in KeePassDX and is configurable in the Pro version"

3. Seems the example also relies on Google Authenticator/ Google OAuth, and doesn't recommend a better client/alternative.

**Comment by J-Jamet** [comment]
1. Always in Beta, will soon be in Release Candidate, but as it affects sensitive data, I prefer to be sure that the bugs do not cause any significant problems.
2. It was a functionality that had been requested but the algorithm does not respect open source standards. So all versions can generate steam tokens but libre and free versions cannot configure it directly from the dialog box.
3. What example would you see? because it is only to illustrate.
