### ISSUE TITLE
Adding a new fingerprint displays an error

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#488]
**Describe the bug**
After entering a new fingerprint in the system, the biometric key prompts that it cannot be read.

**To Reproduce**
very funny.
[KeePassDX - Advanced-Unlocking](https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking)
- 1.According to the wiki, I successfully unlocked the database using biometric authentication in KeePassDX.;
- 2.Then, I created a new fingerprint in the system fingerprint.Then go to KeePassDX to unlock the database with biometrics, indicating that the biometric key cannot be read.Prompt need to delete all biometric keys and re-enter;

Next is the point.

- 3.Enter the password directly to unlock the database, then open KeePassDX settings;
- 4.Go to Advanced Unlock and choose to delete the encryption key;
- 5.Exit KeePassDX and try biometric unlock again with the database just now.Biometrics work fine.

** Keepass Database **
 - Created with: KeePassDX 2.5beta28
 - Version: do not know
 - Location: Phone storage
 - Size: 1.31Kb
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.5beta28
 - Build: Free
 - Language: Chinese

**Android (please complete the following information):**
 - Device: XiaoMi Note 3
 - Version: 9

**Comment by J-Jamet** [comment]
Thanks for the feedback, I can't reproduce your problem on your device.
My first impression tells me that there are writing problems in the KeyStore of your device. (Maybe a problem with Xiaomi Note 3)
If someone has the same model, a return if the problem is reproducible would be nice.
I think the keystore didn't have time to assimilate the new fingerprint and you tried to delete the keys but it failed which had another operation in progress.
And once he finished saving your fingerprint, it could be used.
(this is only a guess)
What I can do on my side is just add an error message if the fingerprint keys can't be deleted but that's all.

**Comment by Vstory** [comment]
The problem has been resolved.I will update the reason later.

**Comment by Vstory** [comment]
> Thanks for the feedback, I can't reproduce your problem on your device.
> My first impression tells me that there are writing problems in the KeyStore of your device. (Maybe a problem with Xiaomi Note 3)
> If someone has the same model, another feedback if the problem is reproducible would be nice.
> I think the keystore didn't have time to assimilate the new fingerprint and you tried to delete the keys but it failed which had another operation in progress.
> And once he finished saving your fingerprint, it could be used.
> (this is only a guess)
> What I can do on my side is just add an error message if the fingerprint keys can't be deleted but that's all.
> 
> Another little thing, why do you say it's very funny?


4.Go to Advanced Unlock and choose to delete the encryption key;
5.Exit KeePassDX and try biometric unlock again with the database just now.Biometrics work fine.

Because of this.
