### ISSUE TITLE
Is an external KeePass parser used?

### ISSUE THREAD

**Issue by mobilekosmos** [Kunzisoft/KeePassDX#512]
Is this project based on an open source keepass library like https://github.com/cternes/openkeepass or similar?

**Comment by J-Jamet** [comment]
The project directly integrates the code which makes it possible to decode KeePass files. Originally, the code came from KeePassDroid (fork), but I completely refactored and redesigned the parser and the decoders to be much more flexible and to avoid as many bugs as possible. The most difficult was to encapsulate the components to manage all the versions because the formats are not the same (kdb - kdbx - 1/4). You can see the full parser directly in the projects.
Do you need the parser for another project?

**Comment by mobilekosmos** [comment]
We use that mentioned library which is actually deprecated and also doesn't support v4 so I'm searching for an open source alternative.

**Comment by J-Jamet** [comment]
So it's for which project because we could combine our efforts if they are complementary.
