### ISSUE TITLE
Recycle bin (as group) cannot be deleted

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [Kunzisoft/KeePassDX#517]
**To Reproduce**
1. go to "Database settings" -> "Recycle bin usage"

2. deactivate and activate this option "Recycle bin usage" several times.

Now multiple "Recycle Bin" are created as a group in the database and the user cannot delete this group.

**Keepass Database**
 - Created with: [KeePassDX 2.5RC1]
 - Version: [2]
 - Location: [Internal storage/Download]
 - Size: [7 KB]
 - Contains attachment: [No]

**KeePassDX:**
 - Version: [2.5RC1]
 - Build: [Free]
 - Language: [English]

**Android (please complete the following information):**
 - Device: [Galaxy S10 - Exynos]
 - Version: [Android 10]

**Comment by J-Jamet** [comment]
This is not a bug.
When the option is deactivated, the RecycleBin folder referenced is dereferenced and transformed into a standard group to not lose the information.
When the option is activated, a new RecycleBinreferenced folder is created, because there was none before.
You are just confused because the groups have the same name, but only one is referenced, others can be renamed or deleted.

**Comment by KPSH7AmcSRcfCqdJ** [comment]
Thank you for the help. :)

Other question the option "Don't search through backup entries"

does not work immediately but when the database is closed and reopened. then this option becomes active.

normal?  can you change it so that it is active immediately if the user activates it without closing the database?

Here something different:

This option only works for Recycle bin if I have activated Recycle bin.  If I create a group myself with "Recycle bin" then it does not work.

**Comment by J-Jamet** [comment]
> This option only works for Recycle bin if I have activated Recycle bin. If I create a group myself with "Recycle bin" then it does not work.

This is normal, because when you create a group with a name (any) it is a normal group. And not a reference from the application's recycle bin. It is not the name that is important but the internal reference.

> Other question the option "Don't search through backup entries" does not work immediately but when the database is closed and reopened. then this option becomes active. normal? can you change it so that it is active immediately if the user activates it without closing the database?

This is normal in the sense that indexes are created when loading the database. I could improve this point but it would require a lot of work for little benefit. Especially if it is configured once, users generally do not change it anymore.

**Comment by KPSH7AmcSRcfCqdJ** [comment]
"This is normal in the sense that indexes are created when loading the database. I could improve this point but it would require a lot of work for little benefit. Especially if it is configured once, users generally do not change it anymore."

maybe you can add a note, that the option is only active after reopening the database if the user activates it. I used the search immediately after activation and wondered why it didn't work immediately.  :D

**Comment by J-Jamet** [comment]
OK ;) -> https://github.com/Kunzisoft/KeePassDX/issues/521
