### ISSUE TITLE
Ask to save new credentials in apps and browsers 

### ISSUE THREAD

**Issue by matesurano** [Kunzisoft/KeePassDX#524]
**Describe the solution you'd like**
Every time any new credentials (username/password) is entered in apps and browsers,  keepass dx should ask(if already not in database)if we want to save it.

Most of the other password managers like bitwarden, Samsung pass, dashlane do this.
App Version : 2.5RC1
Android version 9(pie)
Device: Samsung Galaxy s8.

**Comment by J-Jamet** [comment]
Are you talking about registering a new account or providing credentials once the account is created?

**Comment by matesurano** [comment]
Example: i go to Yahoo login page and type in username and password (no autofill prompt cause credentials are not saved in keepass dx). After login in or say in the next step KeePassDX  asks me if i want to save the credentials in keepass dx(yes/no). Similarly it can be (i am not sure) during(or after) a new account creation also. Many password managers do this e.g. Dashlane.

**Comment by J-Jamet** [comment]
Okay, this functionality will be done in a second step. I must already manage the identifiers which are known. But once this code is completed, I can study how the registration of new items works.

**Comment by matesurano** [comment]
Thanks. 🙏

**Comment by J-Jamet** [comment]
I studied a possible way and I have to make a new workflow which does not conflict with read only. I intend to make a button to switch on the fly between "selection mode" and "recording mode".

**Comment by nishp77** [comment]
@J-Jamet  I'm new to this project is there a documentation?? so I could follow up and contribute to the project

**Comment by J-Jamet** [comment]
There is no technical documentation at the moment. You have to look at the sources, if you don't understand something you can ask. Otherwise there is the github wiki for global information.

As the current project indicates, I am working on this functionality. Git branch : [Autofill_Save](https://github.com/Kunzisoft/KeePassDX/tree/feature/Autofill_Save)

**Comment by J-Jamet** [comment]
For the feature advancement: 

I still have to save new entries in selection mode. But the registration from the autofill is ready.
For registering a `WebDomain` in an entry: 

- if the URL field is empty, it will be filled with the URI: `[scheme]://[webdomain]` provided by the browser.

- If the URL field is not empty, a new custom WebDomain field will be created so as not to conflict with the already existing URL (or WebDomain[n] with n an increment to allow multiple autofill with the same entry).

For the application Id, it will be saved in a custom `ApplicationId` field (or ApplicationId[n] with n an increment).
Note that the customized fields are only available for KDBX databases (not KDB bases) therefore registration will be limited for the old databases.

It will also be necessary to manage the conflicts of the read-only mode but I am rather happy with the progress.

**Comment by strongbox-mark** [comment]
Hi @J-Jamet - Strongbox (an iOS KeePass client) dev here... just got notification of this from @hokonch...

We (KeePassXC, myself and a few others) have been trying to sort of standardize a little the extensions to the KeePass format across clients so that everyone's databases work basically the same on different clients.

One of the changes is "Alternative URLs". I wonder if this applies here? I might be misunderstanding the context here but if KeePassDX is looking for a method to store Alternative/Additional URLs for an entry it would be awesome if we could all use the same format/scheme. 

Is this something you think would work for KeePassDX? 

Kudos on the app by the way! Would be great to have you on board at https://github.com/keepassxreboot/keepassxc/issues/4317

**Comment by J-Jamet** [comment]
> if KeePassDX is looking for a method to store Alternative/Additional URLs for an entry it would be awesome if we could all use the same format/scheme.

Yes of course, harmonization is a good thing. I had to change the name of the new URL fields because there was the prefix `KP2A_` if the database warned of KeePass2Android, which is not a good generic nomenclature, but a new harmonized name would be good.

> Is this something you think would work for KeePassDX?

I linkify links on the fly when they're already there, and I search globally, so that's okay with that.
There might be a link duplication for newly registered items, but that's not a huge bug.

> Kudos on the app by the way! Would be great to have you on board at keepassxreboot/keepassxc#4317

Thanks for the link, I'll look at the conversation in more detail.
