### ISSUE TITLE
Optional In-App Keyboard

### ISSUE THREAD

**Issue by trymeouteh** [Kunzisoft/KeePassDX#528]
I think it will be a good security feature to have a built in keyboard within the app. This can be good for adding or editing the database but especially for unlocking a databases. A Built in keyboard can prevent keyloggers from stealing the passwords to your databases.

**Comment by J-Jamet** [comment]
There is already a keyboard linked to the entries in KeePassDX. For me, there is no interest in adding a standard keyboard. It will add maintenance and bugs for no benefit. The question to ask yourself is why you don't trust your default keyboard. If it is not open source, I understand, but in this case, directly downloaded an open source keyboard without keyloguer, you will have your functionality.

**Comment by trymeouteh** [comment]
You make valid points. The reason I suggested this is because I assume even with a open source keyboard your phone can still get malware and the Android ROM could be key logging you even if your keyboard is open source.

**Comment by trymeouteh** [comment]
It will be a keyboard that does not act like a android keyboard. When you use this keyboard it will not popup your android keyboard, but use the buttons in the app as a keyboard sono keylogger will know your typing.

**Comment by J-Jamet** [comment]
> It will be a keyboard that does not act like a android keyboard.

I did not understand. I don't know what you mean. The goal is to press keys that will display letters from views that send commands to the edittext. So a Android Keyboard.

If the sound of the keys on your keyboard is problematic, disable sound in your keyboard setting.

Your solution is a bit like air guitar to play the guitar. It's visually pretty but the interest is limited. Otherwise you make a pull request, or you explain to me technically the method you have in mind.

**Comment by trymeouteh** [comment]
I imagine keylogging malware will detect your keyboard app and log the keys you enter. But if you create a keyboard in the KeePassDX app which is not a "keyboard app". Many apps have a PIN to unlock it. When you enter these PINs, it does not have your keyboard app popup for you to enter the PIN. Instead the app has the numpad built into the app which is used to enter the PIN. The numpad is built into the app allowing malware keyloggers to not know what numbers you press to unlock the app.

Same idea for KeePassDX for unlocking a database, instead of using the android keyboard app, there will be a keyboard within the app to prevent keyloggers getting your passwords for unlocking your database.

**Comment by J-Jamet** [comment]
> I imagine keylogging malware will detect your keyboard app and log the keys you enter.

How? because concretely and technically, there is no difference between an Android keyboard in a separate application and a keyboard built into KeePassDX (only two different packages), both use the [InputConnection](https://developer.android.com/reference/android/view/inputmethod/InputConnection) class to communicate the elements.
I understand what you mean but it will not protect more in Android architecture, if the keylogger wants to detect text in an editText, it's the same thing in both cases because the methods used are the same if it is a built-in keyboard or not. Here you only tell me theories, tell me more concrete hack cases!

Concrete cases I have in mind is the recognition of views by the accessibility service. In this case, it's even better not to integrate a static keyboard because it will be harder for the keylogger to recognize specifically the input keys in KeePassDX if a different keyboard is used by each user.

In KeePassDX there is no PIN yet, it may be used in the future to replace fingerprint recognition but it does not replace KeePass passwords. (See https://github.com/Kunzisoft/KeePassDX/issues/152)

**Comment by trymeouteh** [comment]
I am not a Android developer so what I was saying was my understanding of a possible threat which could read your database password and I thought by creating a in-app keyboard, this will mitigate it.

**Comment by J-Jamet** [comment]
Of course, I understand. It is important to have debates too, but I must simply base myself on the facts. I'm not going to spend 3 weeks developing on a guess. Thank you for the debate in any case, it is always useful.
