### ISSUE TITLE
"Failed to verify padding during decryption" error while opening a database

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#546]
The error is reported by a user who uses a databaseV1.

Edit : At the moment, the error is not reproducible on my side, if someone has the problem on a database without sensitive data, please upload it! Thank you :)

**Comment by J-Jamet** [comment]
I have no other specific feedback on this issue and I cannot reproduce it. So it is possible that this is an external problem. If the problem appears for someone, you can leave a comment. I will re-open the issue.

**Comment by jlavre** [comment]
Hi,
I had the same problem. 
I think the problem started as follow; I opened an kdbx file in KeePassDX and under preferences enabled the "garbage" function.
I saved it an copied the file to another device and got the error message as stated in the headline.
To overcome the issue, I deactivated the garbage bin on the device I still could open the file in, copied it to the device I had the error on. Then the problem was solved. 

I am using a Galaxy Tab and a Galaxy S10.

**Comment by J-Jamet** [comment]
Thanks for the feedback, I have tried activating and deactivating the RecycleBin and cannot reproduce the problem. I think it must be from a bad file copy between two devices. If not, we need to identify precisely what is causing this problem.
By being able to reproduce it every time.

**Comment by J-Jamet** [comment]
https://sourceforge.net/p/keepass/discussion/329220/thread/7bf6742d/

**Comment by jlavre** [comment]
Hello,

Thank you for looking into the problem. 
I have tried to reproduce the problem, without any sucess.

Anyway, thanks for a great program. Today, this app is far better than any competitor out there. It is really user friendly and has great user interface.

**Comment by J-Jamet** [comment]
The exception can be thrown when a bad credential is entered for a v1 database or when the database is corrupted.

As this file is only binary, the stream cannot read information that is trying to be decrypted. (And I can't put a better exception because I don't know why the data can't be read)

You must then use a backup of your database or use the correct credentials. It is highly recommended to migrate your database to KDBX format (with KeePass2 or KeePassXC)

**Comment by gitfineon** [comment]
Oh, bad luck for me! I generated the password for a messenger backup with KeePassDX, after backup creation I copied everything via USB to my Linux notebook and finally turned the device off and reflashed it. So it is my fault, that I've missed to check kdbx on my notebook, but I didn't expect that to happen, because copying was fine.

Now opening the kdbx file with KeePassDX results in a red banner with the error:
`Could not load your database. java.io.IOException:javax.crypto.BadPaddingException: Failed to verify padding durin...`
Opening the same file with KeePassXC also shows a red banner with:
`Error while reading the database: No root group`
Also 'keepassxc-cli export' fails with the same message

The password is definitely correct and another password results in the "invalid credentials" message

I'm wondering why extraction is not possible with valid password, shouldn't that work no matter how corrupted the inner xml content is? Anything I can try to get the corrupted xml?
