### ISSUE TITLE
Change app language

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [Kunzisoft/KeePassDX#563]
Hello,

is it possible to change the app language without changing the system language? Similar to KeePass on Windows?

### Version

KeePassDX 2.5
https://github.com/Kunzisoft/KeePassDX/releases/tag/2.5

**Comment by J-Jamet** [comment]
For the moment not, this requires a lot of work because it is necessary to make a language manager for each text.

**Comment by SeerLite** [comment]
+1, I'd love to have this option, especially since translations aren't 100% complete and sometimes I have no idea what an option means or the inconsistency just throws me off.

I've also been contributing some lacking text on [Hosted Weblate](https://hosted.weblate.org/projects/keepass-dx/), but that process isn't instantaneous and I'd like to have a "stable" option in the meantime.

**Comment by J-Jamet** [comment]
This is a duplication of #386, I am closing this issue.
