### ISSUE TITLE
Force re-enter master key after awhile when using biometric auth

### ISSUE THREAD

**Issue by oksjd** [Kunzisoft/KeePassDX#566]
Now it's time to give up teaching my dad to use a password manager. The first time, I set up this with fingerprint auth on his phone, and said, "you need to remember this master key, no one will be able to help you if the key is lost". He promised not to forget. Yet after several months the fingerprint auth key was mysteriously gone. "How am I supposed to remember such a thing!" He cried.

I tried to help him setting up a new database after resetting all those passwords. Promised not to lose the master key. Today, it happened again. Cried the same sentence. I give up.

Clear master key from key storage and force re-enter after a period of time, say 72 hours. Just like how the fingerprint auth on lock screen.

**Comment by J-Jamet** [comment]
Yes I think it is a good idea to ask for it again after a set time.

**Comment by J-Jamet** [comment]
Basically this will use the [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) to automatically delete keys, but it's much less accurate than an [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager) for new devices that have restrictions. (For example, if we define 1 hour for deletion, it can be effectively deleted after 2 hours or 3 hours when the phone wants to wake up to not use any battery.) However, the AlarmManager will not restart when the device is restarted.

Otherwise we can use a service (which will temporarily store the keys, so very accurate and will work after restart), but it will be active all the time, will require the display of a permanent notification and will use the battery.

So it is necessary to choose which solution adopted, it is not obvious.

**Comment by J-Jamet** [comment]
Using the WorkManager with the invalidation of keys in the keystore [https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setKeyValidityEnd(java.util.Date)](keyValidityEnd) is a good compromise and makes it possible to no longer use the keys in all cases.
