### ISSUE TITLE
How to create a new database?

### ISSUE THREAD

**Issue by vishalnandagopal** [Kunzisoft/KeePassDX#568]
How do I create a new database with this app? I looked all over the app, can't find it. I'm either too dumb, or is the app only for viewing and editing already created databases?
Thanks!

**Comment by J-Jamet** [comment]
As indicated in the [wiki](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#why-disparate-compatibility), you must have a file manager compatible with the Intent [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT) action, if this is not the case, several solutions are available to you:

- You may just have to deactivate the default file manager of your device, in this case, just reactivate it.
- You can download a file manager compatible with this feature, I recommend: [Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files/). The majority of other managers do not implement this action (for unknown reasons), they must think that it is not necessary for them because it is already implemented in the default app.
- The version of your device is below KitKat (4.4), in this case, it is recommended to update Android to 4.4 or higher. If you cannot and you are motivated, you can create a manager compatible with the ACTION_CREATE_DOCUMENT action for these obsolete versions. This can be difficult because Storage Access Framework was introduced in API 19.

There are no plans to implement direct access to device files for security reasons and to respect the encapsulation of the components.
KeePassDX detects if a compatible file manager can be used and deactivates the button if it is not.

**Comment by vishalnandagopal** [comment]
I already use material files. But I can't see any button or toggle to create a new database in KeepassDX app. It only shows open existing database.

Do I just create a file and give it a  .kdbx extension with Material Files?

**Comment by J-Jamet** [comment]
> I already use material files. But I can't see any button or toggle to create a new database in KeepassDX app. It only shows open existing database.

In this case, it may be a recognition bug. Can you tell me which version of Android you are using?

> Do I just create a file and give it a .kdbx extension with Material Files?

It will not work, because the file must have an internal structure formatted to accommodate a database.

**Comment by vishalnandagopal** [comment]
Android 10. 

I can see only open existing database at the bottom of the app.

**Comment by J-Jamet** [comment]
Indeed, it seems that Material Files no longer react to the intent. I will do more tests and ask the creator of the application.

**Comment by J-Jamet** [comment]
Indeed, the file creation functionality is not available in Material Files -> https://github.com/zhanghai/MaterialFiles/issues/299

You must therefore use another manager for creation. I will test those in the wiki and add a new column to the table to indicate the compatibility of the creation.

**Comment by vishalnandagopal** [comment]
The new default android file manager works for creating a file. I couldn't find it on the play store, but it came pre-installed on my stock Android 10.

App ID for reference -  com.android.documentsui

Shall I close this? Or leave it to you?
