### ISSUE TITLE
Improve magikeyboard with "normal" keys

### ISSUE THREAD

**Issue by newhinton** [Kunzisoft/KeePassDX#581]
**Is your feature request related to a problem? Please describe.**
When selecting the magikeyboard to enter a password, the user can switch to keepass dx with clicking the key-icon. That opens the app. After that, the user has to switch to the normal keyboard, select a password, and switch back to the magikeyboard. This can be quite tedious.

**Describe the solution you'd like**
Assuming the magikeyboard is open, and the database locked:

When the user clicks the key-icon, the next time the keyboard is opened, it should show a basic ascii keyboard. That allows the user to enter the searchterm without switching the keyboard. After then selecting a password, it should display the current layout so that it can be entered.

This removes the requirement to switch keyboards back and forth. 

**Describe alternatives you've considered**
None, since most require elevated permissions

**Comment by techvanity** [comment]
I am also voting for this feature. Please include a full qwerty keyboard. Check the keepass2android as an example.

In addition to the use case mentioned by OP, another reason I would like to have qwerty keys in magikeyboard is to type the master password! I use Gboard as my main keyboard but I do not trust google for my master password.

**Comment by J-Jamet** [comment]
The integration of a full keyboard will not be done in KeePassDX because it will require too much maintenance and it would be necessary to manage all the languages. Personally, I am French, and I use the azerty keyboards.
I think we need to focus on the means to switch between keyboards. So we can use the one we want without limitation.
I haven't studied the switch from other keyboards to Magikeyboard yet, but it needs to be done: 

https://github.com/Kunzisoft/KeePassDX/issues/311
https://github.com/Kunzisoft/KeePassDX/issues/625
https://github.com/Kunzisoft/KeePassDX/issues/528

**Comment by jeremiah-miller** [comment]
This may be an ignorant question since I'm not much of an android dev, but apps can display stuff over other apps right? Can an app displaying over another app input text to the app "beneath" it? Then when a password is selected, instead of having to mess around with switching back and forth between keyboards, you could just paste from the temporary popup type window

**Comment by J-Jamet** [comment]
> but apps can display stuff over other apps right?

In very specific cases, often system permissions are required.

> Can an app displaying over another app input text to the app "beneath" it?

This is possible if it is integrated as root in the system, in fact, your OS must be corrupted to not be detected. A simple separate application is easily visible in normal case.

> Then when a password is selected, instead of having to mess around with switching back and forth between keyboards, you could just paste from the temporary popup type window

A popup is difficult to display. If you are talking about autofill, the service is managed by the system and it must be activated manually by the user so not possible at this level. Otherwise it would require other even more restrictive solutions than changing the keyboard.

> And if the floating window can't directly type text, maybe it could just have buttons to copy attributes so you can copy/paste stuff without needing to switch back and forth between apps?

Notifications to copy to clipboard are already available. The problem is that the clipboard is shared by all apps.
