### ISSUE TITLE
Unexpected autofill popup in Firefox Preview

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#583]
It appears in Firefox Preview (org.mozilla.fenix) when you tap at address field.
![Screenshot_2020-06-06-11-40-16-247_org mozilla fenix](https://user-images.githubusercontent.com/744888/83940517-66ae2d00-a7ed-11ea-8c7f-c993cee9bf4d.jpg)

**Comment by J-Jamet** [comment]
Indeed, sorry for the bug, it is related to the one I just opened.  https://github.com/Kunzisoft/KeePassDX/issues/582

We just don't want the popup to appear here, it is due to the change of algorithm in https://github.com/Kunzisoft/KeePassDX/issues/529

I will try to solve the problem for the next version, which I will release very quickly.
