### ISSUE TITLE
Share Web domain issues

### ISSUE THREAD

**Issue by auanasgheps** [Kunzisoft/KeePassDX#584]
**Describe the bug**
Hi, I am testing the new Share web domain feature and I found some issues.

When using the Share Feature from a Chromium-based browser to KPDX, there are some matching issues. If your DB does not have the exact protocol and FQDN, no entry is found.

**To Reproduce**
Scenario 1
1. In an entry, configure the URL field only entering the website name. E.g. `reddit.com`
2. Navigate to `reddit.com/login` and use the Share feature to KeepassDX.
3. Observe the App searches for `www.reddit.com` and no results are found

Scenario 2
1. In an entry, configure the URL field only entering the website name. E.g. `adobe.com`
2. Navigate to `adobe.com` and then click Sign-in.
3. The website becomes `auth.services.adobe.com`
4. Use the Share feature to KeepassDX.
5. Observe the App searches for `auth.services.adobe.com` and no results are found

**Expected behavior**
I expect the app to look only for the top domain, like `adobe.com` and `reddit.com`. This is what many password managers do by default, and Keepass2Android does too.

Maybe this behavior coule be controlled by the user, similarly to what **Kee** extension offers on Keepass desktop, but I understand this could become very tricky.

**Keepass Database**
 - Created with: oh man I can't remember it's an old DB
 - Version: KDBX 3.1
 - Location: Remote File on Google Drive, but retrieved via the system File Manager 
 - Size: 500 Kb
 - Contains attachment: I don't think so

**KeePassDX (please complete the following information):**
 - Version: 2.6
 - Build: Free, PlayStore
 - Language: Italian

**Android (please complete the following information):**
 - Device: Galaxy S9+
 - Version: 10

**Additional context**
 - Browser: Brave (no autofill avaiable, using Share feature)

**Comment by J-Jamet** [comment]
I just tested and without entering the base, we can see that KeePass2Android also searches on "www.reddit.com", but the match on this program must be different.
What I don't really like, there may be subdomains to a website and not having the same authentication system.
As you suggest, the best is to add a setting that will indicate whether we want to search without a subdomain or not. I will assume that a top domain is characterized by Uri.host with only the last two elements separated by a `.`
So it is not really a bug because it is the host name that is search but I will improve the operation.

**Comment by auanasgheps** [comment]
> What I don't really like, there may be subdomains to a website and not having the same authentication system.

In that case it should show all results matching the domain.

**Comment by J-Jamet** [comment]
Yes you are right, I implement the setting and I put it by default.

**Comment by J-Jamet** [comment]
The setting is in version 2.7
