### ISSUE TITLE
Move TOTP button to the first view level in Magikeyboard

### ISSUE THREAD

**Issue by OLLI-S** [Kunzisoft/KeePassDX#587]
**Is your feature request related to a problem? Please describe.**
In the Magikeyboard there is no button in main view to easily fills the TOTP into webforms/applications.
For increasing the security many web services and password managers recommend the usage of TOTP so I have added 2FA for many of my accounts.

**Describe the solution you'd like**
Please move the TOTP button to the first view level (I suggest a clock-icon).

**Comment by J-Jamet** [comment]
The "OTP token" button is already present in the buttons of the custom fields (it is even interpreted and updated on the fly)

The password button can be replaced by TOTP button if password is not present but it is clearly not a priority at the moment because the current OTP Token button is functional.

**Comment by OLLI-S** [comment]
I know that I can insert the TOTP with the button "Custom Fields".
All my entries that have a TOTP also have a normal password, so it would be helpful to see both buttons in the first level.
