### ISSUE TITLE
Add local network synchronization

### ISSUE THREAD

**Issue by LongJohn-Silver** [Kunzisoft/KeePassDX#597]
**Is your feature request related to a problem? Please describe.**
More or less. A big trouble I've found on every libre password manager I could find is that they work only as local databases, and I think that's really good for security, but at the same time it can be a total pain trying to move a database from one device to another. The only software I know which provides synchronization is BitWarden, but they offer this feature through a cloud based service, which raises security concerns.

**Describe the solution you'd like**
I think that the best solution to this problem would be adding a way in which you could synchronize your databases through a local network, therefore reducing the attack surface that a cloud based solution can offer.

**Describe alternatives you've considered**
N/A

**Additional context**
1Password offers this feature, if that's helpful in some way for development, although I doubt it since they are proprietary. I'll leave a video from Sun Knudsen, a content creator who talked about the benefits of this.
https://1password.com/
https://www.invidious.snopyta.org/watch?v=eu3iP1njMRI
https://www.invidio.us/watch?v=eu3iP1njMRI
https://www.youtube.com/watch?v=eu3iP1njMRI

**Comment by J-Jamet** [comment]
The main defect of 1password is that it is not open source, and synchronizing data on a server that is not open source, blindly, you have to damn trust. (Which is obviously not my case)

The purpose of KeePassDX is to stay as generic as possible to use the synchronization we want.
KeePassDX will not implement network permissions for security reasons and should be seen as an editor which connects to the desired file manager (and can be synchronized).

It is possible to improve the associated file manager to implement the desire sync, that's why I made the wiki article which references these apps.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

The easiest way is to implement file manager with WebDAV or use SyncThing. There should be tutorials on the subject, but as a developer, I clearly do not have time to manage everything. (and english is not my native language)

One other killer idea would be to make a dedicated file manager that would nest with KeePassDX but it would take an enormous amount of time.
I prefer to focus on making editor, but everyone can create a sync file manager app with whatever protocol that natively plugs into KeePassDX.

For me, the main problem is that there are not enough tutorials, but it will come gradually.

I close the issue because it does not correspond to a specific implementation case, but we can continue the conversation which is interesting.
