### ISSUE TITLE
Rename descriptions of clipboard notifications settings

### ISSUE THREAD

**Issue by Cos-mo** [Kunzisoft/KeePassDX#605]
Samsung Galaxy A71 with Android 10
KPDX version 2.7, installed from Google play store, German language
Database fresh created with KPDX, database version KPDX3.1 (KeePass 2)
Size 3.4 kb, stored locally (BTW: It would be nice, if KPDX would show the size in the app, e.g. in the settings)

For testing I have set to trust the clipboard to on
The setting to show a notification for the clipboard is set to on
The timeout for the clipboard is set to 5 seconds

Bug 1: The option to close the database when the notification gets closed (by wiping the notification) does not work.
Steps:
1. I opened a database entry
2. I tapped to copy the password to clipboard
3. I opened the notification area to show the notification
4. I wiped the notification to the right (or left): the notification vanishes (as expected), but the database stayed open and I can do inside the database what I want.
This bug 1a.

BUT:
If I tap on the notification (after step 3), than the username gets copied to the clipboard and a few seconds the database gets closed.
This gives multiple Why?
Why does something get copied at all in this situation?
Why the username? The username gets copied regardless if I copied in step 2 the password or the username. I cannot find the sense of it.
This surprising action is bug 1 b.

2. The timeout does not work at all.
In the settings a second line for this setting says (retranslated by me from my German system): Duration of the storage in the clipboard.
So I expect, that with my setting (see at the top) the clipboard content gets deleted. But this is not the case. I have checked the clipboard with the built-in tool in the sidebar to view the clipboard and so I can say for sure, that nothing get deleted..Not even after some hours, where I left the device alone.
This is bug 2.

Besides that I wonder, which benefit the possibility to set the username to the clipboard from the notification area is supposed to have. Quite obviously I can copy the username more easily from the open database entry. Making this possible from the notification area must have a reason, but I am unable to find out, what this might be.

Regards

**Comment by J-Jamet** [comment]
I just tested the settings that you describe and it works correctly and it matches your behavior, I think the problem comes from the description of the parameters.

**Bug 1**: 
It may be a bug for you if you are trying to close the notification of the clipboard but you have not yet started using it.
From a usage point of view, the setting "Clear at closing" should have as description: "Lock the database when closing the notification if you start to use the clipboard from the notification" It's a bit long
I can add the functionality to close the database at this stage if you want or improve the description

**Bug 2**:
> If I tap on the notification (after step 3), than the username gets copied to the clipboard and a few seconds the database gets closed.

It's not a bug, "The timeout for the clipboard is set to 5 seconds", so after 5 seconds of using a clipboard item from the notification, the database stops, this is normal.

> This gives multiple Why?

I see it

> Why does something get copied at all in this situation?

Because you click to use the clipboard from the notification with an entry item, so the entry item goes to the clipboard and is attempted to be deleted after 5 seconds

> Why the username?

Because it is a copyable data of your entry, if you repeatedly click on the notification, you copy the next data until there is more for the entry. If you have disabled sensitive data from the clipboard, passwords and protected custom fields will never be inserted into the clipboard.

> The username gets copied regardless if I copied in step 2 the password or the username. I cannot find the sense of it.

To compare with a text editor on PC:
If you do Ctrl + C on a text "B" and before you had done a right click -> copy on a text "A", the text "B" is accessible. It's logic.

If you clicked on the notification to put the username in the clipboard, this is what happens. The time does not run out when the notification appears the first time to have time to go on the desired form. And when you click on the notification, the time elapses and is reset for the next data if you click on the notification again.

> The timeout does not work at all.

False, you say yourself that the database is closed after a few seconds (5 seconds) when you start using the clipboard from the notification

> In the settings a second line for this setting says (retranslated by me from my German system): Duration of the storage in the clipboard.

You are right, it is not good. It should be `Duration before closing the database if "Clear at closing" is activated and before the system tries to delete the data from the clipboard` but it's too long, if you have any suggestions, please listen to them

> So I expect, that with my setting (see at the top) the clipboard content gets deleted. But this is not the case. I have checked the clipboard with the built-in tool in the sidebar to view the clipboard and so I can say for sure, that nothing get deleted..Not even after some hours, where I left the device alone.

Indeed, it is indicated in the [wiki](https://github.com/Kunzisoft/KeePassDX/wiki/Clipboard), there is no guarantee that the system will actually delete the data from the clipboard because it depends on the OS. I do not recommend using this method for form filling with sensitive data. This bug comes from the system you have and cannot be resolved in KeePassDX.

> Besides that I wonder, which benefit the possibility to set the username to the clipboard from the notification area is supposed to have.

Fill in a login form

> Quite obviously I can copy the username more easily from the open database entry.

In this case do not activate the notification in the settings

> Making this possible from the notification area must have a reason, but I am unable to find out, what this might be.

It allows, from the notifications, to copy all the copyable fields of an entry without returning to the application for each data to be copied. This is useful for example with many custom fields.

**Comment by Cos-mo** [comment]
I have learned now, that the description for the timeout setting is simply wrong and will be corrected in the next version. Very well. Nevertheless I judge this wrong description as a bug. If the program promises somethings, what it cannot do, than this is a bug and removing the bug is not an enhancement, but a correction. On the other hand: Autoclosing the database is (at least in the German version) not even mentioned for this setting inside of the app. But the most important thing is IMO that after the release of version 2.8 this will be history and how this mistake is judged today is then out of interest.

But I come back to my original question. If I have understood and found out here correctly, than the only way to make the notification about the clipboard content appear is to copy something from inside of a database entry into the clipboard. Assumed, that the trust option is set to off (I fully agree in the judgment, that this is a security risk and I activated it only for testing), there will be in many database entries only 1 field to copy: The username. If I copy the username, why should I ever wish to copy the very same content a second time into the clipboard? And that with a far more circumstantial method (open the notification area, tap the notification). I cannot see any benefit. And although it is only optional: Why is there the possibility to auto-close the database after the timeout, whereas after copying a field content with the quicker and more logical method the database stays open until the end of the general timeout? Of course I see, that I can simply leave this notification-clipboard detour. But I want to learn, why this is there at all. Which is the benefit, which I am unable to recognize?

**Comment by J-Jamet** [comment]
> Nevertheless I judge this wrong description as a bug.

For me, a description is not a bug, it's just a bad label, it doesn't affect the functionality of the feature itself. And It doesn't really matter since it's me who will correct it anyway, it makes it easier for me to see the workload.

> If I have understood and found out here correctly, than the only way to make the notification about the clipboard content appear is to copy something from inside of a database entry into the clipboard. 

No, you misunderstood, the notification is displayed when you select an entry and the setting is selected in the application.

> Assumed, that the trust option is set to off (I fully agree in the judgment, that this is a security risk and I activated it only for testing), there will be in many database entries only 1 field to copy: The username. If I copy the username, why should I ever wish to copy the very same content a second time into the clipboard? And that with a far more circumstantial method (open the notification area, tap the notification)

If this is the case for your database, do not activate the functionality in the settings.

> Why is there the possibility to auto-close the database after the timeout, whereas after copying a field content with the quicker and more logical method the database stays open until the end of the general timeout?

Because if you only opened the database to copy a single entry, you can fill out an entire form with all the fields (aas much as you want in the custom fields, for example to enter the first name, last name, address, postal code, etc.)) for that entry and close the database without going back to KeePassDX. 

> Which is the benefit, which I am unable to recognize?

Fewer steps and no need to open the entry view every time when you have many fields to copy.

Without notification (3 fields):
1. Open the database
2. Open the entry
3. Copy the field A from the main view
4. Go to the form
5. Past the field A in the form
6. Back to KeePassDX
7. Copy the field B from the main view
8. Go to the form
9. Past the field B in the form
10. Back to KeePassDX
11. Copy the field C from the main view
12. Go to the form
13. Past the field C in the form
14. Back to KeePassDX
15.Close the database

With notification (3 fields):
1. Open the database
2. Open the entry
3. Go to the form
4. Copy the field A from the notification
5. Past the field A in the form
6. Copy the field B from the notification
7. Past the field B in the form
8. Copy the field C from the notification
9. Past the field C in the form
10.Swipe the notification to close the database

**Comment by Cos-mo** [comment]
I see, that we count quite differently.

Where you count in case 2 (with notifications) the copy actions (4, 6, 8) as single actions, I come in every case to at least 2 actions: the notifications area has to get opened, and then the user has to (except for the first field) tap multiple times the notification and he has to count carefully how often he taps, otherwise he gets the wrong field. Regarding closing the database: I consider this step as something for the soul, because the content, which has been copied to the clipboard, is far easier to reach for not authorized "users". Also after the timeout as set in the general settings the database gets closed fully automatically. This means, that a not authorized user has hardly the chance to make user of the database. If there should be a spy software in the system, than there is a far bigger problem than closing the database.

At the end I judge it as different philosophies. What was important for me was to learn the idea behind the clipboard-notification settings and this is, what I have learned now.

At the end I want to note, that I respect and love your work. Even when I disagree in this point with your point of view, in general I am on the same track as you are. I do not want the different opinions in this topic stay as the last word.

**Comment by J-Jamet** [comment]
Yes I completely agree, we can detail or not each step. And unfortunately the clipboard manager is not the same on all devices. Basically, only the last element is copied to the clipboard.

The main purpose was also to keep the functionality operational as it was available in the historical code. (KeePassDX is a fork of KeePassDroid which also contained notifications.)  In all case, I do not recommend using this method for new users, the Magikeyboard is made for filling in forms (even if the workflow is still to be improved) and also autofill (with an algorithm that is constantly evolving). We have thought about removing these notifications, but they are still used by many users.

No worries about differences of opinion, that's how we advance the subjects, so it's interesting and appreciated. ;)

**Comment by Cos-mo** [comment]
The said bug - I stay with this judgment -, where the deletion of clipboard content gets promised, although the app is unable to do this, exists (again: I can only report for the German version)) also on another place: If you tapped through all the existing fields via the notification, than the notification does also give the wrong promise. The needed correction must also be done for this place.
I should note, that I know and use the original Keepass and a Linux fork since 15 years. In those systems the deletion of clipboard is indeed possible and working. So my assumption, that the equally named promise for KPDX does what it says, is very logical.

Another finding in this context: The option for the timeout in context with clipboard-notification is reachable, even if the clipboard notification is disabled in the settings. If after the timeout actually the clipboard content would get deleted (as promised), than this behavior of the settings would be correct and needed, But as I now know, that this is not the case, the timeout setting should not be reachable with the clipboard notification disabled. In this case it would be identical with the equivalent settings for the Magikeyboard, where you cannot reach the timeout setting, if the notification is disabled.

**Comment by J-Jamet** [comment]
The application does call the method to delete the clipboard in all these cases. It's your Samsung clipboard (different from AOSP Android) that prevents deletion, on other systems, deletion of items in the clipboard works. What you can do is offer alternatives to these descriptions.

**Comment by Cos-mo** [comment]
If the culprit lies at Samsung, possible also other brands, than many users are affected, because Samsung is the market leader. This means, that many users are affected and get possibly annoyed.

The easiest solution I can offer is to add a note like "if supported by your device".

**Comment by J-Jamet** [comment]
> The easiest solution I can offer is to add a note like "if supported by your device".

I agree

> Another finding in this context: The option for the timeout in context with clipboard-notification is reachable, even if the clipboard notification is disabled in the settings. If after the timeout actually the clipboard content would get deleted (as promised), than this behavior of the settings would be correct and needed, But as I now know, that this is not the case, the timeout setting should not be reachable with the clipboard notification disabled. In this case it would be identical with the equivalent settings for the Magikeyboard, where you cannot reach the timeout setting, if the notification is disabled.

The problem is that the command to delete the element in the clipboard is called. So the setting has an effect for compatible devices (the default behavior). I can't turn it off for these.
And detecting devices is not really feasible, so I must leave it accessible, it will just have no effect for non-compatible samsung devices.

**Comment by J-Jamet** [comment]
I'm replacing:

`Duration of storage in the clipboard` -> `Duration of storage in the clipboard (if supported by your device)`

`Lock the database when closing the notification` -> `Lock the database when the clipboard duration expires or the notification is closed after you start using it`

`Swipe to clear clipboard now ` ->  `Swipe to clear clipboard (if supported)`

What do you think?

**Comment by Cos-mo** [comment]
I agree with your solution.

Regarding the more general problem about not compatible devices: I am very new to smartphones and I did not know, that the differences reach into details, where I would not have expected them. Also, I have only one device and i believe, that many (most?) users also have only one; or if they have more than one, all are probably from the same manufacturer and have the same compatibility problem. That means, that from the user's point of view, things simply don't seem to work correctly or not at all.

Of course inside the GUI of an app you cannot tell long stories. But it might be a good idea, if the wiki says a little bit more about the problem. A list of not compatible devices / brands in the wiki might be useful to prevent users from blaming your app, although in reality the culprit is on another place.

**Comment by J-Jamet** [comment]
I agree, I will update the wiki to indicate the clipboard problem on Samsung OS.
