### ISSUE TITLE
Could not save the database

### ISSUE THREAD

**Issue by gtlt** [Kunzisoft/KeePassDX#615]
**Describe the bug**
I'm unable to save the database and get a message _"could not save the database"_ if db on SDCard.
I'm unable to save the database and **don't** get a message _"could not save the database"_ if db on internal storage.

db on SDCard :
Strangely, if I browser to top level group in KeepassDX before saving it, I don't have the message but nothing is saved. And the lock button doesn't work.

I found a workaround to save db :
- edit or add an entry
- valid it with the mark icon
- (the screen doesn't change)
- cancel with the X icon => discard
- the edit/new entry is visible
- save the database

db on Internal storage :
I don't have the message _"could not save the database"_ but the behavior is more or less the same.
With a new entry, I valid it with the mark icon, a phone message "Executing command..." but the screen remains. I then valid it again and Keepass lock the database (crash??).
The workaround is the same.

The behavior is identical with a fresh db.

**Expected behavior**
Save new entry, save edited entry

** Keepass Database **
 - Created with: database created more that a year ago, I'm not sure of the last successful save but it is months ago before I found the workaround today.
 - Version: ???
 - Location: SDCard / Internal storage
 - Size: 6Kb
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.7
 - Build: libre
 - Language: English

**Android (please complete the following information):**
 - Device: S4 Mini serranoltexx
 - Version: Custom Build Based on LineageOS 16.0, Android version: 9. Note that I didn't install Gapps nor Google Play so I don't have GSF installed. And no micro-g.

**Comment by J-Jamet** [comment]
This problem seems the same as # 612, can you confirm that you have disabled automatic database save in the settings?

**Comment by J-Jamet** [comment]
It's really weird, I reproduce the problem well when I launch the application normally. But when I start the debugger, the problem disappears, to tell the truth, I don't understand why it does that.
I think there must be a thread synchronization problem somewhere. Or maybe the background task management service doesn't have time to start.

**Comment by Cos-mo** [comment]
With autosave disabled I reproduced the steps as described above as "workaround" and I can confirm, that it works.

@J-Jamet 
Do I understand right, that you have autosave disabled and running KPDX via debugger allows you to close edit mode by tapping the checkmark button? Than my guess is, that without autosaving the program runs too fast. (Note, I am not a coder, I only have some ideas collected in some ten years with computers, how code runs and why it does in same cases not run.)
Perhaps it helps to insert in case of autosave disabled some "do nothing" circles in the code to give the code the needed time. It might be a matter of milliseconds. (If this is nonsense, than simply forget it. Did I say already, that I'm not a coder?)

**Comment by J-Jamet** [comment]
I just did several tests and the problem comes from listeners who are not called because they seemed not to be attached to the service.

> Do I understand right, that you have autosave disabled and running KPDX via debugger allows you to close edit mode by tapping the checkmark button?

Yes, absolutely

As you say, the service executes its action too quickly and the user interface does not have time to attach (the service is already destroyed, so there is no call to the methods in the listener), here, the closure of the current activity.

I transformed the [Asynctask](https://developer.android.com/reference/android/os/AsyncTask) by a [Coroutine](https://developer.android.com/kotlin/coroutines) in [DatabaseTaskNotificationService.kt] (#538 )(https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/notifications/DatabaseTaskNotificationService.kt#L567) and I made a conditional loop, it checks:
- the number of headphones, if there are none, it waits
- max wait of 4 seconds (in case there is no listener at all to avoid infinite loop)

And it works!
I also noticed opening problems on old devices, it seems to solve these concerns too.

 ```
    private suspend fun executeAction(progressTaskUpdater: ProgressTaskUpdater,
                                     onPreExecute: () -> Unit,
                                     onExecute: (ProgressTaskUpdater?) -> ActionRunnable?,
                                     onPostExecute: (result: ActionRunnable.Result) -> Unit) {
        onPreExecute.invoke()
        withContext(Dispatchers.Default) {
            onExecute.invoke(progressTaskUpdater)?.apply {

                val startTime = System.currentTimeMillis()
                var timesUp = false
                // Wait mActionTaskListeners attach or 4 seconds max
                while (mActionTaskListeners.size == 0 || !timesUp) {
                    if (startTime + 4000 >= System.currentTimeMillis())
                        timesUp = true
                }

                run()
                withContext(Dispatchers.Main) {
                    onPostExecute.invoke(result)
                }
            }
        }
    }
```

*Note: I am still documenting on the subtleties of coroutines, the goal is to replace all Asynctask. If an expert has technical advice, it is welcome.*

**Comment by raffaem** [comment]
> This problem seems the same as #612, can you confirm that you have disabled automatic database save in the settings?

For reference, I just had this problem and this workaround fixed the issue.

So I guess the fixes don't work?

**Comment by J-Jamet** [comment]
@raffaem I don't understand what your concern is, can you open a new issue with your precise problem. Thank you.
