### ISSUE TITLE
Check reports of "Immuniweb" Mobile Application Security Test

### ISSUE THREAD

**Issue by beerisgood** [Kunzisoft/KeePassDX#616]
**Is your feature request related to a problem? Please describe.**
KeePassDX 2.7 has some security flaws. See https://www.immuniweb.com/mobile/?id=sl7FVSce

**Describe the solution you'd like**
The app shouldn't have any "risks

**Additional context**
Immuniweb can test Apps automatically and display any founded problems:
<img width="749" alt="Immuniweb" src="https://user-images.githubusercontent.com/9625159/86499852-910fed80-bd8d-11ea-89cc-4583a0387965.png">

**Comment by J-Jamet** [comment]
It's reassuring because your automatic detection system does not detect anything very alarming. And in context, some are even false positives.

Medium risks:

- **Hardcoded Sensitive Data [M10] [CWE-200] [SAST]** : It must detect the keyword password in the constants, it is simply the name of the TAGs for the XML parser, accessible everywhere. So false positive.

- **Weak Encryption [M5] [CWE-327] [SAST]**: ECB is the the historic encryption modes compatible with other versions of KeePass, you can manually change the algorithm in the database settings.

- **Predictable Random Number Generator [M5] [CWE-338][SAST]**: Indeed perhaps improved, it is very complicated to predict a Random but a non-deterministic number is even better. I will modify it for the next version.

- **Cleartext sqlite database [M2] [CWE-312] [DAST}**:  Encryption of the SQlite database is planned but not a priority at the moment, the database does not contain very sensitive data, only utility data.

I will watch the low risks later.

**Comment by J-Jamet** [comment]
Low risks:

- **Hardcoded data [M2] [CWE-200] [SAST]**: It's XML protection and it detects protection
```
            try {
                documentBuilderFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)
            } catch (e : ParserConfigurationException) {
                Log.e(TAG, "Unable to add FEATURE_SECURE_PROCESSING to prevent XML eXternal Entity injection (XXE)", e)
            }
```
- **Enabled Application Backup [M2] [CWE-921] [SAST]**: It's normal, backups are configured -> https://github.com/Kunzisoft/KeePassDX/wiki/Backup
- **Missing tapjacking protection [M1] [CWE-451] [SAST]**: It can be interesting to put it in certain places, but there it points to all the views. There is no point in doing it for everything.
- **Exported Activities [M1] [CWE-926] [SAST]**: It indicates an exported activity for biometric recognition, it is normal and self-generated by the android API.
- **Exposure of potentially sensitive data [M2] [CWE-200]**: Indicates that Google Play modifies the program to add the services that send information from the app. It's a surprise for no one, that's why there is an F-Droid version! ;)

**Comment by beerisgood** [comment]
Guess all points are solved then?
Good work!
