### ISSUE TITLE
autofill doesn't work with patreon app

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#619]
You can get the app [here](https://play.google.com/store/apps/details?id=com.patreon.android) . Try to log in with e-mail.

**Comment by J-Jamet** [comment]
It works fine for me. No problem in the recognition algorithm with version 2.7. 
A little thing, you must select the Autofill button with a long click for the email form because the Patreon app does not automatically reload the view for the autofill service, but there is nothing I can do about it in KeePassDX.

**Comment by zveber** [comment]
Thanks for your reply. I'll try to connect with develipers of this app.
