### ISSUE TITLE
Can't type some characters such as CJK characters in protected fields

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#660]
**Describe the bug**
Since version 2.8.2, the keyboard type of protected fields has been textPassword. 
The keyboard type limits the use of multilingual keyboards, so it is difficult to write in users' native language.
I believe this feature is mainly used for secret questions and, the answer is written in users' native language.

**To Reproduce**
1. Add or Edit an entry
2. Add a field with protection
3. try to write field value
4. forced to change my native language keyboard to QWERTY Keyboard

**Expected behavior**
Same behavior in KeePassDX 2.8.1

**Comment by J-Jamet** [comment]
Well, I just saw the behavior of the tags for edittext and I will not be able to change it. I think it comes from the android conventions that prevent languages ​​with combinatorial characters.
So you will simply have to remove the protection if you want to write a message in a language with combinatorial characters. _Note: It does not change anything in the end for the encryption because the whole database is encrypted._

**Comment by hokonch** [comment]
in addition to renaming custom fields (#675), if toggling the protection is possible, it will be a workaround.

**Comment by J-Jamet** [comment]
Yes I agree, I'll do the editing.
