### ISSUE TITLE
Popup windows and KeepassDX

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#674]
It's just a question. If one of using apps has a permission to show popup windows can it get content of KeepassDX window when it visible on screen?

**Comment by J-Jamet** [comment]
Sorry but I don't understand the question. 
What do you mean by _"has a permission to show popup windows"_ ? Which app? Are you talking about permissions in MIUI?
If it's a question about MIUI permissions, this OS is made to block functionality while the internal system has apps with built-in ads (it's inconsistent). For me, it's just to restrict actions on a closed system. Because there is no method to correctly manage these permissions in the code when it is legitimate (and these permissions are not part of the AOSP source code. So, good luck seeing exactly what it exactly does as it is non-standard and part of a closed system.).
In the [AOSP code](https://source.android.com/), an Android application is normally independent from other applications, but again, it depends on the system and its operation, the OS of the manufacturers have many modifications.

And _'can it get content of KeepassDX window when it visible on screen'_? What is the purpose exactly? It is always possible to get the contents of a screen, it depends on your system. I tried to block the app screen record with `LayoutParams.FLAG_SECURE`, but there is always a way if an app or a script has root access for example.

**Comment by zveber** [comment]
Yes, my pnone runs on MIUI 11. Sorry, but I don't know if this lermissiin is specific for it.
I'm talking about `com.vkontakte.android`. It's a social app. And it has an ability to make calls. When it has a permission to show popup windows you can switch to another app keeping call. But it shows it's icon on the screen while minimized. 
So I'd like to know is it safe to open KeepassDX window while I'm talking. And is it safe at all to give such permission? 

Screenshot of permission 
![IMG_20200828_125008](https://user-images.githubusercontent.com/744888/91551356-adb24700-e932-11ea-9611-37618fa6d9e3.jpg)

**Comment by J-Jamet** [comment]
Being safe is a subjective notion. Here the permission is only used to block the opening of the other app. Traditionally, this is done with intent. 

I'm not sure of anything because neither the OS nor the social app are open source, so it is not possible to verify.

If something is in the foreground, it's technically difficult to guess what is present on the screen unless the operating system allows it, but it's likely. Again, it is not possible to verify, so it is up to you whether or not to trust these apps.

**Comment by zveber** [comment]
I got lt. Thanks for explanation.
