### ISSUE TITLE
Rename custom fields

### ISSUE THREAD

**Issue by FreddieOliveira** [Kunzisoft/KeePassDX#675]
**Describe the bug**
After upgrading to v2.8.2 it's not possible to rename a custom field anymore.

**To Reproduce**
1. Open an entry which contains a custom field or create one
2. Give it a name and click ok
3. Try to rename it
4. Cry, because you can't

**Expected behavior**
It should be able to edit both the custom field's name and data, as it was in earlier versions.

**Actual behavior**
It's only possible to edit the custom field's data.

**KeePassDX (please complete the following information):**
 - Version: 2.8.2
 - Build: Free
 - Language: Portuguese

**Additional context**
Here's a screenshot

<img src=https://user-images.githubusercontent.com/9597536/91624129-0cf17500-e98e-11ea-81c1-2d665bab085d.jpg width=50%>

**Comment by J-Jamet** [comment]
Indeed, since the new update, the order of customs fields is important. As requested by users: https://github.com/Kunzisoft/KeePassDX/issues/611
(and prepare the template feature.)

Renaming a custom field is not of much interest because the primary goal is to create new form fields so they normally remain fixed during the life of the entry. It was never possible to rename the labels of the normal fields and it never shocked anyone. Here if you want to edit the label of an entry, the easiest way is to recreate it.

It's possible to rename but will add work for not much interest in my opinion. Otherwise, give me a practical case where the input fields have to be renamed often.

**Comment by FreddieOliveira** [comment]
Yes, indeed it's not an essential feature. Since I started using the app I needed to rename a custom field only once. But the problem here is that, if I use the workaround to rebuild a custom field in order to rename it, I'll loose the order of the fields :(

For example:

```
PIN: ••••
PIN 2: ••••
PUK 1: ••••
PUK 2: ••••
```

Then, you realize you forgot the number 1 for the first PIN name. You can't rename it, so you have to create a new field with the correct name:

```
PIN 2: ••••
PUK 1: ••••
PUK 2: ••••
PIN 1: ••••
```

And now the correct order is gone, since you can't manually organize them.

A way to rename the custom fields or to manually reorder them would solve the problem.

**Comment by J-Jamet** [comment]
I understand, I also thought about it during the day. I'm going to put the feature back but I don't know in what form (maybe an edit button next to delete button or only edit button with delete button in dialog).

**Comment by FreddieOliveira** [comment]
Thanks for taking this into consideration. Maybe a long press somewhere with a further dialog window could be an option.

**Comment by FreddieOliveira** [comment]
@J-Jamet Thanks, your solution was pretty elegant. Just updated to latest version 👍
