### ISSUE TITLE
KeePassDX-2.8.2 cannot open the file of keepass kdbx 2.x.kdbx but can open 1.x.kdb 

### ISSUE THREAD

**Issue by Chilled-ops** [Kunzisoft/KeePassDX#677]
KeePassDX-2.8.2 cannot open the file of keepass kdbx 2.x.kdbx so i have to use the keepass to export the 2.x.kdbx to 1.x.kdb that can use keepass2.8.2 open successful. but some things lossing with 1.x.kdb such as icons. byw i rembered the old version 2.8 could open the 2.x.kdbx.

2.x.kdbx about 1.6 MB, export 1.x.kdb just about 800 KB, and some things lose.

**Comment by J-Jamet** [comment]
KeePassDX should be able to open all types. Please indicate the error message and send a test database that reproduces the problem.

**Comment by Chilled-ops** [comment]
> KeePassDX should be able to open all types. Please indicate the error message and send a test database that reproduces the problem.

the error message: 
could not load your database.
java.lang.lllegalArgumentException: bad base-64

i create a new empty database.kdbx in the keepass2.45 in pc, it can be opened in keepassdx, but my original database is also not can open and indicate the same error massage.

is this the problem with plugin? there are all the plugin in my keepass2.45, 
![database](https://user-images.githubusercontent.com/54822018/91865505-0b80bf00-eca4-11ea-9325-103944185f2b.png)

**Comment by J-Jamet** [comment]
It is indeed possible that it comes from a plugin, but we have to know which one. The error message indicates that a binary encoding (base 64) cannot be read because some characters are not base64. There must be incorrect formatting of your data. Try from KeePass on Windows:
- Export your database in XML
- Reimport your database from XML to generate a .kdbx
Then try to reopen the kdbx with KeePassDX

**Comment by Chilled-ops** [comment]
it works now thats totally awesome!!!! thank you to solve the problem!!!!
