### ISSUE TITLE
No warning when creating a database with an empty keyfile.

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#679]
**Describe the bug**
KeePassDX doesn't allow opening a database using an empty keyfile and shows the warning "The keyfile is empty".
I think KeePassDX should also provide the same warning when creating a database.

Note: Strangely, KeePass and KeeWeb seem to support creating a database with an empty keyfile.

**To Reproduce**
1. create a database with an empty keyfile
2. add entry and autosave
3. lock
4. non-empty database which can't open appears in the recent database list.

**Expected behavior**
prohibit creating a database with an empty database clearly.

KeePassDX Version: 2.8.2

**Comment by J-Jamet** [comment]
I don't understand the bug.

> KeePassDX doesn't allow opening a database using an empty keyfile and shows the warning "The keyfile is empty".

This behavior does not occur in my tests It is of course possible to create a database without a key file.

> create a database with an empty keyfile

How did you create your empty key file? Can you upload the empty keyfile you created to see if it contains a header or something.

> non-empty database which can't open appears in the recent database list.

The database should open with the credentials you created. It is not empty because you have an entry in it, logical.

> Expected behavior
> prohibit creating a database with an empty database clearly.

This sentence is nonsense!  In any case, verifying that a key file is not a database would be complicated to do. We should generalize the concept to check that a file will never be modified but there is no way to do that. It's up to the user not to do anything.
https://github.com/Kunzisoft/KeePassDX/wiki/Credentials

Sorry, but your bug description doesn't make sense.

**Comment by hokonch** [comment]
Empty keyfiles mean 0 byte files.
I noticed the strange behaviour when I mistakenly selected .nomedia file to create an new database. I also tested using a file generated by touch command executed on termux.

**Comment by J-Jamet** [comment]
I just retested, sorry if I didn't understand at first. It's not an intuitive bug.
If we want to improve the concept, we should check that a key file is not empty during the credential validation. 
I will try to do this for the next version. Thank you for the feedback, in fact I had not thought of this case. :/
