### ISSUE TITLE
Database file not found

### ISSUE THREAD

**Issue by ygoe** [Kunzisoft/KeePassDX#68]
I've installed NextCloud and KeePass DX from the F-Droid app store today, all the latest versions.

In the NextCloud app, I've selected my password database file and marked it for offline use. Then I opened it by tapping onto it. I could then open the database file in KeePass DX. The password is stored with a fingerprint.

I've also set up KeePass as autofill service, on Android 8.0.

But when I try to use it, either by starting the KeePass app directly or via an autofill option, it just says it can't find the database file.

I have no idea what the issue is. Is it a problem with KeePass DX or with NextCloud? I don't see enough information on the screen to analyse this any further. All I can say is that the complete solution doesn't work as expected.

**Comment by J-Jamet** [comment]
The problem comes from the implementation of the content provider, in KeePassDX 2.5.0.0beta6 and 2.5.0.0beta7, there is a small bug in default setting who don't auto-check the "File Storage Framework" option. If this option isn't activated, the app lose the link of database file if the phone is under marshmallow or newer.
The issue is solved in development but not yet in F-Droid, normally if you check the option, restart the app and reopen the file, it will work.

NOTE : F-Droid doesn't provide the latest version of KeePassDX because an issue in autoupdate of Fdroid data project (https://gitlab.com/fdroid/fdroidserver/issues/455)

**Comment by ygoe** [comment]
I'm not sure I fully understand your comment.

So you say if I enable the "File Storage Framework" option then it should work? Well, that's not the case.

And what's "marshmallow"? I believe this is the name of an Android version. Please only use numbers because I cannot remember and sort 20 funny names that don't uniquely map to numbers.

And since F-Droid doesn't have the latest version I'll better describe what I have: That's 2.5.0.0beta6-libre. Can the deployment thing be fixed so that I have access to the latest version?

**Comment by ygoe** [comment]
I've tried it with the latest release from GitHub and it also doesn't work (beta 7). I've now checked the file location with Solid Explorer. It shows that the file is actually there, but when browsing to that directory with KeePass DX, the directory is shown empty. So I'm not sure what you mean with "link", the problem seems to be that the app just doesn't see any files at all, only directories.

BTW, is it normal that I can install both the version from F-Droid and from GitHub side by side? I had to uninstall both to be sure which one I started.

**Comment by J-Jamet** [comment]
The application is configured by default to access links without file access rights. The permissions are activated if we create a base or if the link is a **_file://...._** but not with a **_content://..._** because here only the content provider is used. Try to enable permissions and then the "File Storage framework".

Marshmallow is an Android version : https://source.android.com/setup/start/build-numbers

> Can the deployment thing be fixed so that I have access to the latest version?
For sure, F-DROID tests cases must be created to validate the fix. it just have to do them...

There are two different APKs with because they are not signed in the same way and will have different features.

**Comment by ygoe** [comment]
Alright, I have manually granted the Storage permission. I had already enabled the other option.

So what should I do now? Manually select the file from where NextCloud has put it? That's not possible because the folder is shown empty. I cannot select the file because it's not offered in the UI.

**Comment by J-Jamet** [comment]
I'm not offering the file browser. KeePass DX can just read the link provide by _**new Intent(ACTION_OPEN_DOCUMENT)**_, it doesn't contains any UI to select a file. It's the purpose of your default app file picker, if you can't see your file, it's maybe an option in your app. (Generally it's an app simply called "File")

There should be more tests with many different configurations.

**Comment by ygoe** [comment]
I see. I must have misinterpreted the unlabelled UI. I took the "add" button in the bottom right corner as a file picker. Then I selected the directory where the existing database is and expected to open it from there. Now that I've used a file manager to open the file, it works as expected and I can re-open the database later.

**Comment by J-Jamet** [comment]
Ok, good. As the UI is not necessarily clear, I'll add the labels. ;)

**Comment by kangaroo72** [comment]
Can someone confirm the work of Keepass DX with Nextcloud now?

**Comment by ygoe** [comment]
Works most of the time. When it doesn't, I find a workaround and then forget the issue.

**Comment by oldenj** [comment]
@J-Jamet I have a similar problem with Nextcloud&Keepassdx.

The link to my default db is e.g. content://org.nextcloud.documents/document/12345

After a while, it tells me 'file not found, try reopening'. When i do that, it works again, but the link stays the same, which is not really logical to me...

I have the storage permission enabled for keepassdx and i am on LOS 14.1 (Android 7.1.2).

**Comment by bllngr** [comment]
Unfortunately, it still doesn't work when the Nextcloud instance is not available (due to no internet connection or Nextcloud being offline). Keepass2Android is keeping an offline copy for that reason and continues to work without interruption. That's why I still have to keep both.

**Comment by J-Jamet** [comment]
If there is no cache in Nextcloud, it can't be resolved from KeePassDX. But as I said before, I'm thinking about implementing a new file manager.
https://github.com/Kunzisoft/KeePassDX/issues/840
