### ISSUE TITLE
Problems reading attachments can cause failure to load with "bad base-64" error

### ISSUE THREAD

**Issue by t-m-w** [Kunzisoft/KeePassDX#691]
KeePassDX fails to load databases with certain types of attachments whose content contains an equals sign. For affected attachments, removing the equals sign allows the database to load, but the attachment size and content is not read or exported properly by KeePassDX.

**To Reproduce**

Steps to reproduce failed database load:
1. Extract the database from [nothing.zip](https://github.com/Kunzisoft/KeePassDX/files/5184808/nothing.zip) and attempt to open it with KeePassDX, using the master password: `nothing`.
2. Receive error: `Could not load your database. java.lang.IllegalArgumentException: bad base-64`

Steps to reproduce failed attachment handling:
1. Extract the database from [loads.zip](https://github.com/Kunzisoft/KeePassDX/files/5184830/loads.zip) and attempt to open it with KeePassDX, using master password: `nothing`. (This is the same database as from nothing.zip above, but with the filename changed to loads.kdbx and the content of the attachment changed to not include an equals sign.)
2. Open the "something" entry.
3. Observe that "broken.txt" reads as being 10 B (not correct), and when exported, will be 0 bytes.

**Expected behavior**
The database should open without issue, as happens with other KeePass clients (KeePass for Windows, KeePassXC on Linux, KeePassDroid and Keepass2Android on Android).
Not all clients support attachments at all, but for those that do (Keepass2Android, KeePassXC), there are no similar problems displaying or saving these types of attachments.

**Workaround**
Working around the problem means eliminating this type of affected attachment everywhere it's found, whether that be in a regular entry, its history, or the Recycle Bin.
Here's one possible workaround that does not require you to delete and re-attach attachments, export and re-import your database content, or re-create the entire database. It also does not seem to harm the entries or their history, but your mileage may vary! Always back up your database just in case!
1. Using KeePass for Windows, find any entries with attachments. One easy way to do this is to do a search, then use View > Grouping in Entry List > Off, and click the Attachments once or twice to sort by entries with attachments.
2. Perform the following steps for each entry with attachments:
3. Navigate to the group for the entry (you can click on the group name in the entry view), and select the entry.
4. Click the Entry menu > Data Exchange > Copy Entry (Encrypted).
5. Click the Entry menu > Data Exchange > Paste Entry (Encrypted).
6. The copied entry should be selected after pasting. This entry's attachments (including in its history) will not be affected by the problem.
7. Identify and delete the original entry, and remove it from the Recycle Bin if present.

**Keepass Database**
 - Created with: Windows KeePass 2.45
 - Version: 2
 - Location: local
 - Size: <2KB
 - Contains attachment: yes

**KeePassDX (please complete the following information):**
 - Version: 2.8.3
 - Build: F-Droid
 - Language: English

**Android (please complete the following information):**
 - Device: OnePlus 5
 - Version: 10.0

**Additional context**
My database has a few entries with key files as attachments. I added these entries about a year ago, but this issue started in the past week or two, and I have not been able to determine what changed to cause this, or what app is responsible for the change (be it KeePassDX itself or another manager). I tried downgrading from 2.8.3 to 2.8.2 and 2.8.1; I experience the problem with all of these app versions.

These text attachments end with an equals sign because they contain base64 content themselves.

So far, I have not been able to reproduce this problem by creating a new entry or a new attachment. It's as though the attachments just happen to have entered a bad state, as far as KeePassDX is concerned. So, to create these sample databases, an entry with its affected attachment needed to be carried over to another database. I made a copy of my own database, deleted all entries except one of the affected entries, and removed any private info from that entry and its attachment. Then, I imported that database into a new database, allowing KeePass to create new unique IDs. KeePass for Windows was used for all of this.

It may be a coincidence, but the affected attachments have a lock icon instead of a piece of paper icon next to them in KeePass on Windows. When re-attaching, the icon is a piece of paper. I am not sure what this icon is supposed to represent.

**Comment by J-Jamet** [comment]
Thanks for this very detailed issue, it's nice to work with someone who took the time to write a ticket correctly. :+1: 

I just ran some tests adding the [Base64.NO_PADDING](https://developer.android.com/reference/android/util/Base64) flag and catching exceptions and it looks promising.

The question is, what do I do with the corrupted data?
I managed to recover the data to a file but it is not decoded. So should I leave them as is or delete them for a save?

> My database has a few entries with key files as attachments. I added these entries about a year ago, but this issue started in the past week or two, and I have not been able to determine what changed to cause this, or what app is responsible for the change (be it KeePassDX itself or another manager). I tried downgrading from 2.8.3 to 2.8.2 and 2.8.1; I experience the problem with all of these app versions.

I failed to reproduce the data corruption in my tests, but I think it can happen if a file is no longer accessible or deleted during the backup (there is not much I can do with this case unfortunately, because I am dependent on the input stream and the binaries are already copied to internal cache). I fixed other things in version 2.8.4 which prevent deleting binaries but there is no data corruption so i don't see. Can you tell me what other apps are you using? Because I tried to manage the [ANRs](https://developer.android.com/topic/performance/vitals/anr) well and to encapsulate the uploads and downloads in separate threads, which seems not to be the case in many other applications. (You can see it when uploading large files.)

> It may be a coincidence, but the affected attachments have a lock icon instead of a piece of paper icon next to them in KeePass on Windows. When re-attaching, the icon is a piece of paper. I am not sure what this icon is supposed to represent.

That's a good question, I don't know either. I can try to apply an icon also to identify this type of data. If anyone in the information, please leave a comment.
