### ISSUE TITLE
Wrong autolink in entry fields

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#720]
https://i.imgur.com/rNmjU60.png

**Comment by J-Jamet** [comment]
I am unable to reproduce the problem with the text shown in the picture. @hokonch If you can upload a database with the relevant entry, that would be great! ;)

**Comment by hokonch** [comment]
(This issue was reported by me in an email)

This issue reproduce with SIM card inserted.
8-digit phone numbers is not exist in my country, so I don't think it's a problem specific to my SIM card.
5d7db04 is the first bad commit

**Android:**
 - Device: Google Pixel3a
 - Version: 11 (factory reset)
 - SIM: NTT DOCOMO (Japan)

**KeePass Database:**
[keepass.kdbx.zip](https://github.com/Kunzisoft/KeePassDX/files/5283879/keepass.kdbx.zip)
password : `p`

**Comment by J-Jamet** [comment]
It has nothing to do with a SIM card, it's just default patterns applied.
https://developer.android.com/reference/android/text/util/Linkify
https://developer.android.com/reference/kotlin/androidx/core/text/util/LinkifyCompat
https://stackoverflow.com/questions/40788608/androidautolink-for-phone-numbers-doesnt-always-work

I will use the masks: Linkify.WEB_URLS or Linkify.EMAIL_ADDRESSES to remove phone links (Not really useful I think)
