### ISSUE TITLE
Nextcloud Connector

### ISSUE THREAD

**Issue by lanzi69** [Kunzisoft/KeePassDX#741]
**Is your feature request related to a problem? Please describe.**
At the moment I use the Nextcloud App to sync my KeePass databases between different devices under Windows, Linux and Android. 

Recently a friend showed me KeePass2Android, that seems to have a native Nextcloud integration and with this feature it's possible to dispense with the Nextcloud App.

**Describe the solution you'd like**
Under Android I've been using KeePassDX for about two years now and I don't want to switch to another App.

There's just one feature I miss in KeePassDX: A natively included Nextcloud connector, that makes the Nextcloud App unnecessary.

**Describe alternatives you've considered**
Have a look at KeePass2Android. 

**Additional context**
none

**Comment by J-Jamet** [comment]
This is not planned because it would require the integration of all the protocols.
I know how KeePass2Android works and I specifically created KeePassDX to not have the same behavior and to respect a very clear encapsulation system. You can read the wiki on the subject.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#explanation
You can switch to KeePass2Android if you don't agree with this philosophy.
