### ISSUE TITLE
Encrypt attachments in temp folder

### ISSUE THREAD

**Issue by t-m-w** [Kunzisoft/KeePassDX#749]
**Describe the bug**
Potential security issue (see Rationale for more info): when database is unlocked, attachments are written out in plaintext to the "no backup" folder in the app's internal storage, e.g. /data/data/com.kunzisoft.keepass.libre/no_backup, as numbered files (0, 1, 2, ...). When the database is locked, the directory is emptied.

**To Reproduce**
1. Gain root access.
2. Unlock database that contains attachments.
3. Browse into /data/data/com.kunzisoft.keepass.libre/no_backup (or /data/data/com.kunzisoft.keepass.free/no_backup if installed from Play Store).
4. Open any of the files inside to see the attachments in plain text.

**Expected behavior**
Attachments are either not extracted to disk until the user needs them, or they maintain an encrypted form.

**Rationale**
Root applications can technically always access your private data if they want to, and malicious ones can abuse it. This is mostly unsolvable. The difference here has to do with ease and intent. This issue provides a window of opportunity for root apps to *trivially* read the decrypted attachments, and crucially, this may not even be intentional. For example, although the folder is called no_backup, some backup applications do include it anyway.

A more-likely scenario is one that does not involve an attacker: a user's phone crashes and reboots while their database is unlocked. They decide to boot into a recovery environment like TWRP and back up their device (unencrypted) in case they need to restore it later or start over. They are fully aware that their data is unencrypted in this backup, but they would have no reason to expect private pieces of their password database to be part of it, because there is no immediately-obvious reason why plaintext bits would be written to disk. Not knowing this, the user may not take as much care of these backup files as they should. (It is highly unlikely, but still possible, that their password database was the only valuable thing on their phone.)

I will acknowledge that most users keep their devices encrypted and do not even use root, and ext4 encryption (along with full-device encryption) would likely prevent this from being an issue for them, but there could be other unforeseen exploits, and I am not sure this behavior is justified.

** Keepass Database **
 - Created with: Windows KeePass ??
 - Version: 2, if I recall correctly
 - Location: Retrieved via Nextcloud content provider
 - Size: < 1 MB
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.8.7
 - Build: Libre (F-Droid)
 - Language: English

**Android (please complete the following information):**
 - Device: OnePlus 5
 - Version: 11 (LineageOS 18.0)

**Comment by J-Jamet** [comment]
Indeed, it is a point to improve, I had already thought about it but I have not yet had time to create the encryption method for an open database.
Storing attachments in the app's temp folder helps prevent memory overflows because the elements are retrieved one after the other from streams and remains relatively secure for devices in the first development step (are deleted in the majority of cases except in the specific root case that you mention). 

> Attachments are either not extracted to disk until the user needs them

No, because doing everything in RAM undeniably causes OOMs, which is very problematic.

> or they maintain an encrypted form

Yes this is the solution. But rather re-encrypt attachments on the fly when they are stored individually in the temporary folder. On the other hand, it is necessary to generate a random key in the opening service which will undeniably be destroyed if the service is no longer available.

For that, I had to merge the opening services to make only one, which I managed to do (not without difficulty in previous very recent app versions). The next step is to create the on-the-fly file copy encryption system to complete the process. I plan for version 9.1, unless a pull request arrives before! ;)

**Comment by J-Jamet** [comment]
I don't know why but @jenn334 is making unnecessary links to unrelated stuff...

**Comment by J-Jamet** [comment]
So, I spent a lot of time studying and trying to implement an encryption system for the temporary binary files contained in the temporary folder.
Here are the blocking points:

- I managed to implement on-the-fly binary file encryption from decrypting the primary database file to store each binary in separate files. (with this method they can be processed separately later without OOM). But the problem is that the dynamic size of each binary file is lost when it is encrypted, the size calculation no longer works and must be injected into the primary database file before it's content during a database save (so before the decryption). I haven't found a solution yet, maybe with a `CountingOutputStream`?. (The advantage of recovering the file size dynamically [so the current method] was that it adapted and corrected false size. I would not like to lose this feature.)

- On-the-fly binary encryption adds a longer global decryption time of the primary file, I used the Blowfish/CBC/PKCS5Padding algorithm which gives the best performance in terms of time but is proportional to the size of the binaries, which is problematic.

Developments are in the `feature/Encrypt_Temp_Binaries` branch.

The goal would be to call the methods for decrypting binary files only during the database save or viewing of these files and to follow the path of the streams as naturally as possible.

If you have ideas on how to solve these problems and improve performance, they are welcome.

This is not an urgent feature because the temporary folder is well purged when the database is locked, but it would be a good addition.

**Comment by J-Jamet** [comment]
OK, I just implemented CountingOutputStream to calculate the size of the files and it works great!
We still have to test the encryption time, but it seems to be working, I'm pretty happy.

**Comment by J-Jamet** [comment]
Merged in `feature/Image_Viewer`

**Comment by J-Jamet** [comment]
With the encryption of attachments in the temporary folder, the overall opening time is increased from 100% to 120%.
This is the price to pay for secure elements but it is relatively reasonable.
