### ISSUE TITLE
Should not save shared info when selecting from multiple accounts 

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#783]
**To Reproduce**
1. `Save shared info`: Enabled
2. Database includes two entries whose URL fields is `twitter.com`.
3. Share `twitter.com` URL in your browser
4. Manually select an entry and and KeePassDX try to save shared info
5. The entry has almost the same values in the URL and WebDomain field

**Expected behavior**
Try to save shared info only If the search results was none

**Comment by hokonch** [comment]
>Fix same save shared info

I think `twitter.com`, `mobile.twitter.com`, `http://twitter.com`, `https://twitter.com` should be considered as the same.

**Comment by J-Jamet** [comment]
> I think twitter.com, mobile.twitter.com, http://twitter.com, https://twitter.com should be considered as the same.

It is complicated to implement. For the Autofill workflow this cannot happen because there is an intermediate interface that displays the results obtained (popup). Here, the results obtained are in the app .

Considering items to be the same is not done in a linear fashion, it is a time consuming method and is returned in a separate thread. (Must check sub domain, etc...) and I cannot do a non-save clickable element at this level because it would be confusing for the user.

**Comment by J-Jamet** [comment]
Considering the received email, the new behavior does not allow saving for the current mode if search elements are found.
