### ISSUE TITLE
Option to autoclose the database when closing the app or all apps

### ISSUE THREAD

**Issue by tutyamxx** [Kunzisoft/KeePassDX#800]
**Is your feature request related to a problem? Please describe.**
Basically every time I force close with "close all" button, there is always a notification that shows my db is open.

**Describe the solution you'd like**
An option where I can toggle to force close. Ex: when I close all apps, automatically close my database and require the password/biometric again and make the notification go away.

**Describe alternatives you've considered**
Nothing really.

**Comment by J-Jamet** [comment]
Android's "force close", as the name suggests, attempts to force a program to close. So try to literally kill him regardless of his state.

Which means that:
If the database is closed, no worries.
If the database is open but taking no action, almost no problem but some temporary items will not be emptied/deleted.
If the database is open and trying to save, this is a big problem because it could corrupt your database in addition to the previous points.

The solution to this is to use a foreground service to prevent the program from being killed by this action, which has been implemented.
You just have to click on the notification lock to properly close the database.
If you want to remove this feature, you risk significant data loss. It's up to you, but I won't change the current behavior.

**Comment by tutyamxx** [comment]
Hey, thank you for the information. :)
