### ISSUE TITLE
Enter master key for database using Magikeyboard

### ISSUE THREAD

**Issue by andypl** [Kunzisoft/KeePassDX#813]
**Is your feature request related to a problem? Please describe.**
Right now we cant enter master key by secure keyboard. 

**Describe the solution you'd like**
Magikeyboard should be able to enter masterkey in KeePassDX. (Keepass2Android allow this by own keyboard)

**Additional context**
When we have locked database and wanted to unlock it in KeepassDX, we can do it by:  fingerprint, by a file key and password.
When we choose password unlocking, we must use another keyboard to type password and I think entering a password for a database from other keyboard rather than Magikeyboard its less secure.

**Comment by J-Jamet** [comment]
Duplicate #https://github.com/Kunzisoft/KeePassDX/issues/528

> Right now we cant enter master key by secure keyboard.

There are many open source and secure keyboards. Pick the one that's right for you if you don't trust your OS.
The issue has already been addressed and it doesn't add any security, just unnecessary maintenance.
Please read the previous thread.

**Comment by cvmocanu** [comment]
Why was this closed? It's not a duplicate of #528. That one is one way of solving this.

Another way is to have a setting to require the use of Magikeyboard when opening a database, and popping up the popup to change keyboards continuously if the current keyboard is not Magikeyboard, just like KeePassDroid Offline does it.

Opening the database with any keyboard other than Magikeyboard is a huge security risk, if the keyboard itself has spyware.

**Comment by J-Jamet** [comment]
The Magikeyboard needs an open database to work, if none is open there is no accessible password, which makes sense. So that means that the request can only be resolved in two ways:
  - Either we store in another way the master password, and the only secure way is the Keystore that needs biometrics or secure way of unlocking. But in this case there is absolutely no reason to go through the keyboard and the device unlocking is already developed.
  - Either we extend the Magikeyboard by putting a button by letter that exists and it is #528


If your keyboard is spyware of course, this is a risk. If your phone is also a spyware, this is also a problem, spoiler : This is probably the case if your OS is not open source. Just do not use a keyboard which is a spyware, I recommend you to make your choice on an open source keyboard.

**Comment by cvmocanu** [comment]
Hi @J-Jamet , sorry, I assumed (apparently incorrectly) that Magikeyboard is a full keyboard, like the one included with Keepass2Android Offline. Since I'm very security-oriented (my phone unlock method is a password, I don't use biometrics anywhere, and I avoid TPM - the convenience of not typing a password comes with too much of a risk for wrong TPM implementations or backdoors), I will stay on Keepass2Android Offline for now. It's about layering:
* a spyware keyboard + K2A steals everything I type
* a spyware keyboard + KeePassDX steals everything I type **plus hundreds of passwords in my KeePass database**

I perfectly understand you for now wanting to put effort into including a full keyboard with KeePassDX. I'm a developer myself, and I know how it is to build features for a product I'm giving away for free, features that I don't need and won't use.

Thank you for all the effort you put into this project, and making it available for free and open source.

**Comment by J-Jamet** [comment]
> I perfectly understand you for now wanting to put effort into including a full keyboard with KeePassDX.

I didn't say that, you have not read the issue #528

Including a full keyboard in KeePassDX would be like maintaining it and a lot of work is needed while perfectly secure and open source keyboards already exist.
It would be counterproductive and more dangerous, it is better to use a keyboard that has a dedicated development team that can quickly fix bugs and security concerns. This is what is most secure, no need to reinvent the wheel.

Currently the effort that was made in KeePassDX is to easily change keyboard.

> Thank you for all the effort you put into this project, and making it available for free and open source.

You're welcome

**Comment by cvmocanu** [comment]
> Currently the effort that was made in KeePassDX is to easily change keyboard.

Would it be possible to add a feature to show the keyboard change popup if the current keyboard is not a particular keyboard (configured)? Then including a full keyboard in KeePassDX would not be needed - only requiring a safe one would be.

I myself have a safe keyboard installed. But my less technical friends may not have, and if I configure their KeePassDX safely, it would help them a lot.

**Comment by J-Jamet** [comment]
> only requiring a safe one would be

It's very subjective. What criteria do you use to determine whether a keyboard is safe or not? It's not up to KeePassDX to make a block list; it's up to the user to choose. The same applies to the Android OS: Should we prevent users from using KeePassDX on a phone whose security cannot be clearly verified because it is not open source, or because there are known security vulnerabilities in the released version of Android? No, the choice should be left up to the user.
After that, we can direct users to well-known, secure solutions by including links to recommendations. I'm currently working on the onboarding process, so this could be done at that stage.

**Comment by cvmocanu** [comment]
> What criteria do you use to determine whether a keyboard is safe or not? It's not up to KeePassDX to make a block list

Agreed. I was thinking to configure the name or the package of the keyboard to be required. Me (a more technical user) could do the configuration for a less technical user.

**Comment by J-Jamet** [comment]
In this case, look at [Keyboard Switcher](https://gitlab.com/kunzisoft/Android-KeyboardSwitcher/-/tree/develop), it will be this project to modify for a request like this. But I warn you, there are technical constraints of Android if you do not use ADB.
