### ISSUE TITLE
Devices with two biometric unlock options supported?

### ISSUE THREAD

**Issue by PurifyPioneer** [Kunzisoft/KeePassDX#821]
Hello,

I was wondering if devices with two biometric unlock options (face scan, fingerprint) like the Mate 20 Pro from Huawei are supported.
This question came to my mind after reading the wiki about advanced unlocking and fiddling around with the app.
Finger print is working great but I'd like to use face scan as well because it's faster and more enjoyable to use. Maybe with finger print as the fallback (just like the normal unlock screen of the Mate 20 Pro). 

Is this possible with the app at the moment?

Thanks in advance for an answer and making this great app!

**Comment by J-Jamet** [comment]
KeePassDX only uses Google's biometric API and by extension the unlocking elements provided by your device.
If your device supports fingerprints and facial recognition as secure unlocking elements, you will be able to use them. But I don't know how your system is done internally and what it offers, you just need to test.
If facial recognition is not offered, it is simply that your device does not offer it as a secure unlocking solution or that an internal option is not activated.
Otherwise yes it is possible because some users have already used it, it is not my case because I do not have a compatible device.
