### ISSUE TITLE
Binary keyfiles of 64 bytes are not handled correctly

### ISSUE THREAD

**Issue by oilarabla** [Kunzisoft/KeePassDX#835]
**Describe the bug**
When using a binary file of 64 bytes as a keyfile, databases generated by KeePass can't be opened using KeePassDX

**To Reproduce**
1. Create a binary file (non UTF-8) of exactly 64 bytes length
2. Create a new database using the above file as a keyfile using KeePass
3. Try to open the database with KeePassDX (using the same keyfile and password, obviously)
4. The database doesn't open

**Expected behavior**
The database should open correctly

**Additional context**
The [code handling keyfiles](https://github.com/Kunzisoft/KeePassDX/blob/454561c2a1b0e0840f314e7a36344b79959763ca/app/src/main/java/com/kunzisoft/keepass/database/element/database/DatabaseVersioned.kt#L139) of 64 bytes assumes it is a UTF-8 formatted hex string.
I don't know what it is supposed to do but from my testings, using AES for encryption and key derivation, it looks like the keyfile (of 64B) is hashed using SHA2-256 like keyfiles >64B

**Comment by J-Jamet** [comment]
Thank you for your issue. Unfortunately this functionality is not yet implemented in KeePassDX. I have to take the time to do it. I will plan it for future versions.

**Comment by J-Jamet** [comment]
Sorry, I thought you were talking about something else.

I relied on the KeePass documentation, here  :  https://keepass.info/help/base/keys.html

- 32 bytes. If the key file contains exactly 32 bytes, these are used as a 256-bit cryptographic key. This format requires the least disk space.

- **Hexadecimal. If the key file contains exactly 64 hexadecimal characters (0-9 and A-F, in UTF-8/ASCII encoding, one line, no spaces), these are decoded to a 256-bit cryptographic key.**

- Hashed. If a key file does not match any of the formats above, its content is hashed using a cryptographic hash function in order to build a key (typically a 256-bit key with SHA-256). This allows to use arbitrary files as key files.

So if the key file contains something other than these characters, it is normally hashed (3rd point).

**Comment by J-Jamet** [comment]
It seems that the second point is not correct, I will recode it. We should also contact KeePassDroid because it is part of it.

**Comment by J-Jamet** [comment]
After all of my testing it looks like the second condition is not included in KeePass2, I tested with a text file containing a key as shown, but it is recognized as a binary file. And if I directly create a file with 64 hexadecimal characters, it gives me a 32 bit file, so the first condition is called.
I'm just removing the second condition from the code as it just causes bugs ...
