### ISSUE TITLE
UX 

### ISSUE THREAD

**Issue by alok121** [Kunzisoft/KeePassDX#836]
**Is your feature request related to a problem? Please describe.**

1. 

When I open a database and then after done using it when I lock it by back navigation gesture, the screen moves to same database opening screen to enter password, If I at this point I again use back navigation gesture, we reach home screen, where all database are listed.

2.

 Lock button is at strange left bottom corner place (out of focus mostly ) and shape is also different.

3. 

When I upload database on Google drive it works i.e sync but when used with OneDrive it got corrupted and it's not opening. 

4.

After corruption no way to recover data
and loss of information stored permanently.

5.

Hard to use with one hand on phones as screen size tall-ness increasing. 

Biometric logo of fingerprint when not enabled is being shown in database login screen.
It causes distraction.

**Describe the solution you'd like**

1. 

Ideally after pressing lock or back navigation gesture, the home screen should directly be shown - instead of showing database open screen waiting for putting password. 

2.

Can Lock button on left bottom be moved to right hand side and in circular shape.

3. 

A warning message should be given by App that Google drive works but other don't after installation as a training module.

4.

Can this app create auto multiple backups of database (like one in use and other backup copy) on Google cloud so that in case of corruption, other versions of database can be used.

5.

It will be great if  finger print icon is removed from database login screen since we only use password. 

And also move password typing box at bottom so that it can be reached easily by one hand - something like samsung oneui design

**Describe alternatives you've considered**

**Additional context**

**Comment by J-Jamet** [comment]
Next time, please open an issue per request.

1. It will not respect the normal connection workflow when a database file is opened from a file manager. To see if other users want this behavior, but need to define special cases of the workflow, so not at all a priority.

2. The lock button cannot be easily converted into a floating button, because on some screens, a floating button is already available. In addition, the current style can be integrated directly into the toolbar, which is practical.

3. I don't want to write messages that explain behaviors of third-party apps that are not directly related to KeePassDX. Just read and update the wiki which is made for this. https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

4. KeePassDX is only an editor, it is up to the user to manage their backups according to their wishes. https://github.com/Kunzisoft/KeePassDX/wiki/Backup

5. Simply deactivate the biometric unblocking feature in the settings. Advanced Unlocking - Biometric unlocking
