### ISSUE TITLE
Manually import / export app settings

### ISSUE THREAD

**Issue by Pranab009** [Kunzisoft/KeePassDX#839]
Sir your app is Amazing... Please add Total App Setting's Backup option.

**Comment by J-Jamet** [comment]
I don't know this option, can you provide documentation that indicates its properties.

**Comment by Ilithy** [comment]
Hi;
Here is the google doc, to give a general idea

Export settings data: https://developer.android.com/guide/topics/data/backup#SettingsData

Backup options:
https://developer.android.com/guide/topics/data/backup#Choosing

Thank.

**Comment by J-Jamet** [comment]
But this backup is already implemented, I even wrote an article on the subject. I thought you were talking about a new method with a separate application or something like that. https://github.com/Kunzisoft/KeePassDX/wiki/Backup#app-backup

Letters are uppercase in **Total App Setting's Backup**, that's why I thought a specific app.

Maybe there are bugs in the data backup, it's possible, we have to check more deeply, otherwise I don't understand the request.

**Comment by Pranab009** [comment]
![Uploading Screenshot_20210107-223009.png…]()

**Comment by Pranab009** [comment]
Sir I'm telling about app setting backup
(export setting/import setting).
not database backup.
Please implement app setting backup.

**Comment by mycal123** [comment]
how did you guys import password exported data  (from other password manager) in csv or jason format in keepassdx?

**Comment by J-Jamet** [comment]
@mycal123 https://github.com/Kunzisoft/KeePassDX/wiki/Import-and-Export
