### ISSUE TITLE
Add priority to OTP button in notification

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#845]
I would like to have a TOTP button in the entry notification (only if a TOTP is saved for the entry). Is this possible?

**Comment by tim427** [comment]
Another possibility would be; making the entry available via the Magic Keyboard. This could also help with case when only the password has been filled in automatically.

**Comment by J-Jamet** [comment]
@Offerel Yes it's possible. Just checked, and it works fine. Activate the setting in Form filling -> Clipboard notifications.
When you enter an entry, you will have the possibility to copy the TOTP token in the notification.

@tim427 Autofill, magikeyboard and notifications are 3 different methods. Only use the magikeyboard if you want the OTP in it.

**Comment by Offerel** [comment]
@J-Jamet Sorry, but i can't find anything regarding TOTP fields in Form filling -> Clipboard notifications. At least for me, it would be the best, if i could have an option, where i could manually configure up to 3 fields, which will be shown in the entry notification. For example, when i would configure it to show the fields "username", "password" and "totp". If one of the configured fields didn't exits for an entry, it should not show up in the notification. This configuration should be made globally for the whole application. 

For the actual situation, im sorry, but i cant make a screenshot. A message pops up, which mentions, that some security restriction has disabled screenshots for the app.

**Comment by J-Jamet** [comment]
> Sorry, but i can't find anything regarding TOTP fields in Form filling -> Clipboard notifications.

The recognition of the TOTP field is done automatically in the notification. You don't need to indicate it specifically, just have "Clipboard notifications" enabled.

>  At least for me, it would be the best, if i could have an option, where i could manually configure up to 3 fields, which will be shown in the entry notification. For example, when i would configure it to show the fields "username", "password" and "totp". If one of the configured fields didn't exits for an entry, it should not show up in the notification. This configuration should be made globally for the whole application.

This is already the case automatically, the notification recognizes by itself which fields are filled in the entry, and proposes to copy them one by one.

![notification_totp](https://user-images.githubusercontent.com/19224038/104310933-cfbcf800-54d4-11eb-873e-9395e40d98ed.jpg)

In the example, my entry has a username, a password and a TOTP.

- The username is proposed first and if I click on the notification, its value is populated in the clipboard.
- The password is protected (clipboard trust) so it is not proposed.
- The TOTP is offered in the clipboard next if you click on the notification again, or you can use it first if you click the "TOTP" button at the bottom of the notification.

Manually configuring the fields to be sent to the notification would be much too long to develop and there would be no added value since the notification already recognizes the fields to be populated in the clipboard.

**Comment by Offerel** [comment]
I understand, i have to click the whole notification and not only a button after expanding the notification. But if i try this, it didn't work at least for my entries. For example, i have a entry Google with the fields Username, Password, URL, E-Mail, KP2AURL_1, KP2AURL_2, KP2AURL_3, KP2AURL_4, KP2AURL_5, KP2AURL_6, KP2AURL_7, KP2AURL_8, KP2AURL_9, Password2, PIN, SyncKey, TOTP Seed, TOT Settings and Reset Code. 

When i touch the notification, it copys first username, followed by password, e-mail, KP2AURL_1 and finally KP2AURL_2. After that, it stops populating new fields. 

To my knowledge, the TOTP field is computed from field TOTP Seed which was added by the Desktop Plugin "Tray TOTP". The fields KP2AURL_1, KP2AURL_2, KP2AURL_3, KP2AURL_4, KP2AURL_5, KP2AURL_6, KP2AURL_7, KP2AURL_8 and KP2AURL_9 are from Keepass2Android. The fields E-Mail, Password2, PIN, SyncKey and Reset Code are custom fields from my side.

In most cases, i need on Android only to manually use the fields Username, Password and the computed TOTP field. Thats why, i asked for configurable fields.

BTW: If i expand the notification, before i click it the first time, i see the fields Password, E-Mail and KP2AURL_1.

**Comment by J-Jamet** [comment]
Ha okay, I see. There is a technical limitation of 5 fields (with 3 custom fields) in the notification. I didn't think anyone would have so many custom fields.
I can improve the concept to give high priority to the OTP field in the notification.
In your case, I already advise you to use the Magikeyboard, which is much more intuitive at this level.

**Comment by Offerel** [comment]
Many thanks. BTW:. Most of my entries have much more fields. I didn't use Google that often, it was only an example where I was sure, that I have a working TOTP seed inserted. Anyway many thanks.

**Comment by Offerel** [comment]
Nice. Works like a charm. Many thanks
