### ISSUE TITLE
German translation to be fixed

### ISSUE THREAD

**Issue by engelhro** [Kunzisoft/KeePassDX#85]
# Version used
Version 2.5.0.0beta7-libre

# Issue
Using German as system (and thus app) language, the settings of KeePassDX several times use the word "**Standart**" instead of "**Standard**" (like the English word, just capitalized).

This misspelling is quite common but unfortunately one of the ,,worst“ – it makes people cringe who know the slightest about orthography…

# Correction
Please globally replace every occurrence of "**Standart**" with "**Standard**" in the strings of the German translation. Thanks!

**Comment by J-Jamet** [comment]
Of course, sorry for that. I'm going to put a community translation tool for this kind of problem. If someone knows a free (libre) one that synchronizes with github, it would be perfect.

**Comment by justintime4tea** [comment]
https://poeditor.com offers unlimited translations for open source projects, hooks into GitHub and is collaborative. Didn't look too deep into it but it looks like it might work?

**Comment by J-Jamet** [comment]
I found https://translate.zanata.org/ and https://www.localize.im/ as open source projects, untested but completely open.

**Comment by justintime4tea** [comment]
The second one looks really awesome and looks like some big open source projects are using it. Nice find!

**Comment by justintime4tea** [comment]
Stumbled accross this on FDroid; translate Android apps on GitHub from an Android device:

https://github.com/LonamiWebs/Stringlate/blob/HEAD/README.md

**Comment by engelhro** [comment]
@J-Jamet: Fixed with version 2.5.0.0beta11 (and maybe earlier, but that's what I verified now). Shall I close this issue (problem resolved) or leave it open for now due to the discussion which was started here regarding the translation tool set?

And, one more question: whiy is the F-Droid version always lagging behind the Google Play store version? It would be nice to see updates happen on both, so the versions are "in sync" most of the time… Thanks!

**Comment by J-Jamet** [comment]
You can close the discussion, I'll open a new issue to manage the translation tools.

> whiy is the F-Droid version always lagging behind the Google Play store version? 

Good question, I'll add it to the FAQ. 

- The PlayStore only needs an APK generated and signed to be available on the store, it usually takes 20 minutes to be available because I go through fastlane for deployment. But I don't know how the APK is managed by google, I know they get statistics and events on each APK because I have reports. So it's fast, but I don't know how it works on the Google servers.

- F-Droid, to ensure that the code is open source, checks the sources directly on Github (by checking the presence of new tags) and builds itself the APK that the server signs during the compilation of code and dependencies.
You can force an update manually, but we must make a request on the fdroidata project to update the [metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.kunzisoft.keepass.libre.txt) of the project and generate a compilation of the server. (example of [manual request](https://gitlab.com/fdroid/fdroiddata/commit/71f1b5b9a9cbe3ebccd2bb824a8e8010fab94047))
In previous versions of F-Droid, there was an [automatic build bug](https://gitlab.com/fdroid/fdroidserver/issues/455) because it could not recognize attributes in the KeePass DX project manifest. I made a merge request (pull request) on the project fdroidserver to solve the problem, because it was very restrictive to make manual updates that take time.
With the fix that dates from a week, updating projects like KeePass DX will take 1-5 days for F-Droid to analyze all available repositories. (Which is better than before 1-3 weeks, thanks to the F-Droid devs who approved the fix.) So F-Droid is slower for deployment but it is run by volunteers and guaranteed a clean APK. :)

**Comment by J-Jamet** [comment]
https://hosted.weblate.org/projects/keepass-dx/strings/ is now active to easily translate!
