### ISSUE TITLE
Tapping Magikeyboard notification

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#857]
Currently I have 3 notifications when I have opened an entry. One is a notification for Magikeyboard with a progress bar, which shrink in time. That's nice so far, but I think it would be nice if you can tap this notification and Magikeyboard will come up.

I have no idea if this will be possible, but this would be a welcome addition. ![Screenshot_20210115-165601_Firefox.jpg](https://user-images.githubusercontent.com/14041522/104749993-c2617100-5753-11eb-8ecf-962f99a808f6.jpg)

**Comment by J-Jamet** [comment]
I can't really do that because the keyboard display is managed by the system and I can't switch to the Magikeyboard automatically if another keyboard is selected.
The only thing I can do is the same behavior as [Keyboard Switcher](https://play.google.com/store/apps/details?id=com.kunzisoft.keyboard.switcher) which allows to choose the keyboard to display.

**Comment by Offerel** [comment]
Hmmm, ok. I understand. In that case, we should close this FR. I fear bringing up the keyboard select dialog is not a good option from user point of view. At least for me, this is not what i would expect as a user. IF you want consider this as a future idea, then please feel free :-) But many thx for investigation.
