### ISSUE TITLE
Wrong pop up shown for "Biometric unlocking" + "Device credential unlocking"

### ISSUE THREAD

**Issue by Foalic** [Kunzisoft/KeePassDX#868]
When tapping "Biometric unlocking" or "Device credential unlocking" in Settings>Advanced Unlocking>General, the pop up window for the "Delete encryption keys" setting appears and asks to delete all encryption keys.
Also, the slider under "Biometric unlocking" appears on but no biometric unlocking seems to be enabled.

To reproduce:
1. Go to "Settings>Advanced Unlocking>General"
2. Tap on "Biometric unlocking" or "Device credential unlocking"
3. Wrong pop up appears

Expected to be able to enable Biometric unlocking/device credentials when tapping that setting.

**KeePass Database**
 - Created with: Windows Keepass 2.47
 - Version: 2
 - Location: File local on phone

**KeePassDX (please complete the following information):**
 - Version: 2.9.11
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: Huawei TAS-AL00
 - Version: Android version 10, EMUI version 11.0.0

**Additional context**
None

**Comment by J-Jamet** [comment]
I don't understand the bug. It is normal that the dialog box is displayed because changing mode cannot be done without deleting the keys.

> Also, the slider under "Biometric unlocking" appears on but no biometric unlocking seems to be enabled.

When this parameter is activated, the biometric unlocking mode is possible. You must of course follow the steps described in the wiki to link your password to the biometric recognition.

https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking

Again, I don't see what the bug is? Did you do all the steps correctly?

**Comment by Foalic** [comment]
Thanks for getting back so quickly. 

Sorry, it seems I messed up the sequence of the steps in the setting up of the advanced unlocking and misunderstood the pop up message because it didn't work due to the messed up sequence.

I have been able to set it up properly now and it works. 
Thanks again and very sorry for the misunderstanding. 

Great app, by the way. Really saves me a lot of hassle.
