### ISSUE TITLE
Message "The information contained in your database file has been modified outside the app." displayed in error

### ISSUE THREAD

**Issue by wzahra** [Kunzisoft/KeePassDX#875]
**Describe the bug**
The message "The information contained in your database file has been modified outside the app." displayed when the change was in fact made on the phone, inside KeePassDX. In this scenario, Google Drive on the phone and Google Backup & Sync on the computer are used to sync the database file.

**To Reproduce**
1. On the phone, decrypt the database.
2. Navigate to "+ > Add entry" and name it "phone1".
3. Tap the orange tick button to save and exit edit mode; allow the database to save and exit the entry.
4. Swipe down from the top of the screen to display the Google Drive app's upload of the file to Drive in the Android notifications panel.
5. Swipe up to hide the notifications panel and tap on entry "phone1".
6. Message is displayed "The information contained..." (see 'Describe the bug' above).

**Expected behavior**
I don't see why this message should be appearing. The only editing that occurred was steps 2-3 above, where the entry was created and saved.

**KeePass Database**
 - Created with: Windows KeePass 1 over a decade ago, but these days used with the latest KeePassXC (as a KeePass 2 .KDBX file).
 - Version: 2.6.3
 - Location: Remote file stored in Google Drive 'My Drive' folder
 - Size: 12.1MB
 - Contains attachment: The database does contain approximately 40 file attachments.

**KeePassDX (please complete the following information):**
 - Version: 2.9.12
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: Aspera Jazz 2
 - Version: Android 9

**Additional context**
Interestingly, even though the Drive app on the phone suggests the upload is complete, and if I tap 'Reload database', I see the entry 'phone1', I don't see the entry appearing on the computer (and Google Backup & Sync does not indicate the file was sync'd). Even if I navigate to the Drive website (on the computer) and download the file - supposedly the very same file that I 'reloaded' in KeePassDX - and open the file in KeePassXC, the record 'phone1' is not present. However, in KeePassDX, if I navigate to 'Menu > Save database', Google Backup & Sync promptly syncs the file and KeePassXC displays the 'phone1' entry.

**Comment by J-Jamet** [comment]
Thank you for the detailed issue.

Indeed. I've already tried to fix the bug but there's a strange behavior of the file metadata and I don't know what solution to adopt. Linked to https://github.com/Kunzisoft/KeePassDX/issues/794

The file modification time date is modified :
1. immediately when the stream is closed, which is normal here (by File app, not sure about Google Drive)
2. after the file is uploaded to the servers (by Google Drive).

The main problem is that point 2 is recognized by KeePassDX as a file update because the file modification metadata is uploaded and compared to the last saved modification time (so the real save time during the stream closure).
You can check the real updated time and the date indicated in the dialog box, you will see that there is a difference.

I already added a delta of 5 seconds (to avoid spamming) but if the metadata is modified by Google Drive after 5 seconds of the stream closure, the bug appears. 

So I don't know which solution to use to solve this problem. If anyone has an idea, it is welcome.

_Concerning the additional context, it's clearly out of the context of the application and a behavior or a bug of Google Drive, I can't do anything at this level._

**Comment by da2x** [comment]
You can use a file hash in addition to the mtime to confirm that the file has indeed changed.

**Comment by J-Jamet** [comment]
I thought about it but the problem is that the whole stream of the content resolver has to be read.
I wish it would have stayed in the metadata.
And to optimize this stream reading, the full database reload should also be included.

**Comment by J-Jamet** [comment]
I have added a larger delta and new conditions in the new version 2.9.15 of the app, let me know if you still have the problem.
