### ISSUE TITLE
Auto-Type for Magikeyboard

### ISSUE THREAD

**Issue by Xeevis** [Kunzisoft/KeePassDX#885]
I'd like to input passwords to my ShieldTV (AndroidTV) through [Nvidia Shield Remote](https://play.google.com/store/apps/details?id=com.nvidia.shield.remote), but only rarely it works with Magikeyboard. I think it's because inputs don't support pasting, as developers optimized them for TV remotes and input isn't directly focused, therefore Magikeyboard doesn't work while virtual/physical keyboard typing does. I guess there is no way to tell Magikeyboard to perform auto-type instead of paste? 

Would be probably easily solved if we could for example hold the username/password/OTP button for 2 seconds for it to be typed instead of pasted. Thoughts?

**Comment by J-Jamet** [comment]
I don't know what you mean by auto-type instead of paste? The clipboard is not used, so there is no paste.
Magikeyboard uses [InputConnection](https://developer.android.com/reference/android/view/inputmethod/InputConnection) - https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/magikeyboard/MagikeyboardService.kt

**Comment by Xeevis** [comment]
> I don't know what you mean by auto-type instead of paste? The clipboard is not used, so there is no paste. Magikeyboard uses [InputConnection](https://developer.android.com/reference/android/view/inputmethod/InputConnection) - https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/magikeyboard/MagikeyboardService.kt

It was my assumption passwords are pasted because inputs which allow for pastes work, while others that require typing don't. Thanks for the correction. Looking forward to the implementation of auto-type.
