### ISSUE TITLE
Unlock credentials settings messed up?

### ISSUE THREAD

**Issue by bushrang3r** [Kunzisoft/KeePassDX#887]
I've just moved from A10 to A11 (custom ROM).
I have an unlock pattern set on the phone (5x5 grid), but trying to use the stored credentials to unlock only displays a 3x3 grid.

**To Reproduce**
1. Enter password
2. Tap on 'Open the advanced unlock prompt to store credentials'
3. 3x3 grid is displayed
4. Any pattern attempted results in 'Wrong pattern' message.

I have tried:
1. Clearing the keys, and clearing the app storage and starting again.
2. Uninstalling and reinstalling the app.

**Expected behavior**
A 5x5 grid should be displayed just like with A10.

**KeePass Database**
 - Created with: KeepassDX
 - Version: Don't know
 - Location: Internal memory
 - Size: 19.5kb
 - Contains attachment: No

**KeePassDX**
 - Version: 2.9.12
 - Build: Libre
 - Language: Eng

**Android**
 - Device: Redmi Note 8 Pro
 - Version: A11
- Custom ROM: crDroid

**Comment by J-Jamet** [comment]
This must be a problem with your ROM because KeePassDX itself does not display the device credential screen.

It just invokes a display request and retrieves the response the system returns with [`createConfirmDeviceCredentialIntent()`](https://developer.android.com/reference/android/app/KeyguardManager#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence)).

You should report the bug to the creators of your ROM.
