### ISSUE TITLE
Making the browser autofilling process faster  ( Feature Request )

### ISSUE THREAD

**Issue by xd003** [Kunzisoft/KeePassDX#888]
When KeePassDX proceeds to use autofill in a browser ,at the very 1st screen it asks to select the database file .
In this step , if there's only a single database file ( which i beleive is the case for the almost everyone anyways ) , why not automatically have it opened to proceed further 

At the 2nd dcreen , if one is not using keyfile and biometric authentication is already enabled , why purpose does it serve for users to have to tap on that fingerprint icon ..If keyfile is not used and biometric authentication is enabled , it should automatically ask for biometric authentication once database has been opened . Only if cases where someone fails biometric authentication x no of times , it could go back to the previous screen letting user use the password authentication as last resort . 

Combining both of the above ideas , it would easily save around 3-4 seconds during autofill which would be great
Just for example , the workflow could be -
While inside browser , one opts to use KeePassDX autofill.  Since only one database file is present it would automatically open it and biometric authentication prompt would occur immediately without any user intervention

**Comment by J-Jamet** [comment]
The behaviors you describe are already available in KeePassDX, just activate them:
- Not everyone has only one database (and I need to improve the system of switching between several databases). Simply bookmark the database you want with the star and it will be selected automatically next time.
- There is no link between the key file and the biometric unlocking because only the password is linked to the biometric recognition. The automatic opening of the biometric prompt can be activated in `Settings -> Advanced unlocking -> auto-open prompt`.

**Comment by xd003** [comment]
I appreciate your prompt response . Both of the things i mentioned are already there as you told .i just needed to activate them . Probably i should have framed this as a question, my bad . Thanks again for the great work on this project

**Comment by J-Jamet** [comment]
Don't worry, changing a tag doesn't take long, and this issue can be useful for other people.
