### ISSUE TITLE
Accept otpauth URIs from binary eye

### ISSUE THREAD

**Issue by thomassth** [Kunzisoft/KeePassDX#893]
Right now there is no in built QR code scanner for setting up new 2FA codes.

A workaround is to use third-party QR code scanner Eg.  [Binary Eye](https://github.com/markusfisch/BinaryEye) to retrieve the otpauth URI from QR code.

NOTE: problem identified as something else, this quoted part is now irrelevant. See comments below

```
However there is no support for opening otpauth URI. I need to copy it manually and set up the rest in KeepassDX.

Proposed workflow:

A website presents the otpauth URI in QR code:
otpauth://totp/{WEBSITE}:{ACCOUNT}?secret={SECRET}%issuer={WEBSITE DOMAIN}

User scans and clicks the link in QR scanner app, KeepassDX opens and prompt for authentication.

(Or create an in-app QR scanner for this purpose)

After unlocking the vault, the address is parsed into an entry

Title: {WEBSITE}
Username: {ACCOUNT}
otp: (directly copy the entire otpauth address)

User confirms the entry and saves it.
```

**Comment by J-Jamet** [comment]
> Right now there is no in built QR code scanner for setting up new 2FA codes.

This is normal, because it would be necessary to include a library and it is one format among others, I prefer that KeePassDX only manages the links shared by the dedicated applications, which manage coded images much better.

> A workaround is to use third-party QR code scanner Eg. Binary Eye to retrieve the otpauth URI from QR code.
However there is no support for opening otpauth URI. I need to copy it manually and set up the rest in KeepassDX.

This functionality is normally already included. Otpauth URIs are already managed in KeePassDX when sharing a link from another application.

I tested with [QR & Barcode scanner](https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner) and it works. Not sure with [Binary Eye](https://github.com/markusfisch/BinaryEye), to be checked.

**Comment by thomassth** [comment]
After some tests, I found that binary eye had a different way to parse otpauth.
Should be related to this file, but I don't understand much:
[BinaryEye/app/src/main/kotlin/de/markusfisch/android/binaryeye/actions/otpauth/OtpauthAction.kt](https://github.com/markusfisch/BinaryEye/blob/56237c43cdd4d1d1da6417d107c297f33a883bb0/app/src/main/kotlin/de/markusfisch/android/binaryeye/actions/otpauth/OtpauthAction.kt)
If you share the otpauth as plain text over to KeePassDX, the function works just fine.

**Comment by thomassth** [comment]
Apparently, after an update at Binary Eye, the function works as intended. I'll close the issue here.
