### ISSUE TITLE
Auto fill option not visible while using Keyboard-Dock with Samsung Galaxy Tab S7+

### ISSUE THREAD

**Issue by eRaz3r** [Kunzisoft/KeePassDX#894]
**Describe the bug**
Since the Update on Android 11/One UI 3.1 the autofill prompt isn't shown on scree while using a keyboard dock without on screen keyboard. I think the problem ist the new way of including the autofill option directly in the onscreen keyboard.

**To Reproduce**
1. Use a keyboard dock (or a bluetooth keyboard maybe too)
2. Open a site where you want to log in
3. Try to trigger autofill

**Expected behavior**
The autofill prompt should work again. Maybe it is possible to use the old way of autofill directly at the username and password field.

**KeePass Database**
 - Created with: latest Windows KeePass
 - Version: 2

**KeePassDX (please complete the following information):**
 - Version: 2.9.12
 - Build: F-Droid and PlayStore
 - Language: German

**Android (please complete the following information):**
 - Device: Galaxy Tab S7+
 - Version: 11

**Comment by J-Jamet** [comment]
I can't test on my side because I don't have your keyboard dock. Is there an application crash?

Normally the inline autofill placed in the keyboard is activated because the keyboard indicates that it is compatible with this mode. If the keyboard is not compatible but indicates that it is, I can't do anything from KeePassDX.

The only thing you need to do is to disable this option in the settings `Settings -> Form filling -> Autofill settings -> Inline suggestions`

**Comment by eRaz3r** [comment]
Thank you very much. I don't even think about this option. After I deactivated it, the prompt is shown again and I can use KeePassDX again even with my samsung keyboard.

And to answer your question, there wasn't any crash.
