### ISSUE TITLE
[2.9.14_Beta] DB file corrupts when you try to add a new entry

### ISSUE THREAD

**Issue by zveber** [Kunzisoft/KeePassDX#924]
Open some DB and add a new entry. Fill in it's fields and press the check mark. You'll see an error message, saying the file is cannot be saved. After it you can't open the DB again (password doesn't fit) and DB file size becomes much lighter (though linux `file` utility still says it's a keepass file.

App version: 2.9.14 pro.
Device: Xiaomi Redmi Note 8T.

**Comment by J-Jamet** [comment]
I can't reproduce the problem on my side, can you upload a database that reproduces this behavior? Also, what file manager are you using?

**Comment by zveber** [comment]
I'm talking about built-in file choose dialog. You see it when you hit "add an existing DB" in the app. It shows file size. My DB's size is 1.3 MB before and 238 bytes after.

[Before](https://drive.google.com/file/d/1BOGULu5RZauBXjiUBYxoqwtNFj6zC0tx/view?usp=drivesdk)
[After](https://drive.google.com/file/d/1BQGE62JsvFTiGcxHCmWMXsJACXiUkEEs/view?usp=drivesdk)

**Comment by J-Jamet** [comment]
I understand that your database is smaller, but which file manager is your URI associated with?
The goal is to understand why there was an error during the backup, but if I can't reproduce it, I can't help much.

If the file can't be saved, we have to know if it comes from the file manager itself or from the application, that's why I'm asking you to upload a data base with which I can reproduce the problem.
I can't access your drive

**Comment by zveber** [comment]
I uploaded files to Dropbox: [before saving](https://www.dropbox.com/s/pysyuo5efk98d8p/passwords.kdbx?dl=0) and [after](https://www.dropbox.com/s/6goo88sh9iv9kx4/corrupted.kdbx?dl=0). As I see you don't have to modify the DB somehow, just tap "Save DB" in the menu.

By the way. I tried to create a new DB with the app and it doesn't have such problem. And I just tried to open, modify and save the DB with Keepass2Android with no problem. Then I opened the DB in KeepassDX again and the problem still exists.

To modify a DB I don't use any managers. I just start the app and choose a DB on the start screen.

**Comment by J-Jamet** [comment]
OK, so there must be a parameter in the database that makes a bad save that interrupts it.

But I must be able to open the fault database to retrieve the exception and debug the code, otherwise you can give me the exception directly if you know how to retrieve the logs. (you can provide a password for a fault database without sensitive data)

You must use a file manager, otherwise you can't even open a database (maybe the default one built into the system).

**Comment by Vstory** [comment]
#925 When the database changes, please consider adding backups.

**Comment by zveber** [comment]
Ok, I'll upload the DB with simple password later as soon as I hide all sensitive information.

**Comment by zveber** [comment]
Tell me, can I get some logs using just ny phone? For some reson I can use my PC only through an SSH session using my phone and it's not very comfortable.

**Comment by J-Jamet** [comment]
Normally you have to use ADB but you can use other ways.
https://www.xda-developers.com/how-to-take-logs-in-android/

**Comment by zveber** [comment]
It looks like I've found the entries causing the problem. The file is [here](https://www.dropbox.com/s/15bcpc6d12jc0eh/cause-error.kdbx?dl=0) and its password is `123`. I created those wallets just for fun, so don't worry.

**Comment by J-Jamet** [comment]
OK, thank you! :)
I just fixed the problem, it's because a MD5 check is performed on an empty binary.
I make some corrections and I upload the new version 2.9.14 beta code 61 on the store.
