### ISSUE TITLE
New entry discarded when app not active

### ISSUE THREAD

**Issue by mwip** [Kunzisoft/KeePassDX#93]
Whenever I create a new entry and move to another app or lock the phone, the entry is deleted. This might probably happen because the database is locked. However, this might cause problems, if you have to insert some information to the data base entry.

**Comment by J-Jamet** [comment]
The read-only mode is not yet active in the application, a new entry is saved immediately after it is created and the save button is clicked. If the entry can not be retrieved, maybe your database file itself is read-only. Do you open your file from a cloud? What happens when you save a new entry, close the database and open it again with the application, the entry is still present ?

**Comment by J-Jamet** [comment]
No answer, I close the issue.
