### ISSUE TITLE
Select different entry from autofill

### ISSUE THREAD

**Issue by chaptergy** [Kunzisoft/KeePassDX#943]
Sometimes the autofill data is incomplete, e.g. in the mail app. I have multiple email credentials in my database, and first I would have none associated with my email app, so I would be prompted to select an entry. This entry will then be associated with my mail app. However for any subsequent mail accounts, only this one entry will show up in autofill, with no way to fill other credentials via the autofill. I would have either add the package name to each entry I would like to have suggested, or copy paste them.

![signal-2021-03-30-161449](https://user-images.githubusercontent.com/26956711/113003548-5b543580-9162-11eb-8366-e0cd608bc8e7.jpeg)

A solution would be to just add an option to the autofill to select a different entry.

**Comment by uduerholz** [comment]
As you said, in order to associate an entry with an app you can add a custom entry with name "AndroidApp" and set the value to your app package name, e.g. "eu.faircode.email". You can do this for up to 10 entries. They should all show up in the selection list.

But I also added an option to manually select any entry from the database:
![issue_943](https://user-images.githubusercontent.com/81411344/117461772-3bc4df80-af4e-11eb-94ed-9334e142e2f2.png)

**Comment by uduerholz** [comment]
It's not a big change and "works for me". @J-Jamet: I can create a pull request if you like.

**Comment by Ilithy** [comment]
@uduerholz: I hope you will propose this in PR, because it is a very good thing.

Is it possible to make the display of the manual search field optional via an option in the settings? Or would that be too complicated.

Have a nice day

**Comment by uduerholz** [comment]
I also made the change configurable in the settings. That is not complicated, only most translations are missing.

**Comment by Ilithy** [comment]
@uduerholz Thank you very much
