### ISSUE TITLE
BadPaddingException with Keepass2 Twofish deprecated plugin since 2.9.15

### ISSUE THREAD

**Issue by dr4go** [Kunzisoft/KeePassDX#955]
**Describe the bug**
When opening my kdbx database, a BadPaddingException occurs since version 2.9.15, whereas the same kdbx file works fine on 2.9.14.

**To Reproduce**
1. Open KeepassDX 2.9.15 or 2.9.16
2. Click on Open DB (using TwoFish)
3. Select keyfile
4. Typing password
5. The crash occurs

**Expected behavior**
The db should be opened and be usable.

**KeePass Database**
 - Created with: either KeepassDX or Windows KeePass 2.47
 - Version: 2
 - Location: Remote file retrieved with Dropbox app
 - Size: 75kb
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.9.15 or 2.9.16
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: Galaxy S10 G973F
 - Version: 11

**Additional context**
[logcat_04-07-2021_04-47-24.txt](https://github.com/Kunzisoft/KeePassDX/files/6268674/logcat_04-07-2021_04-47-24.txt)

**Comment by J-Jamet** [comment]
This should only happen if you use a Twofish plugin on KeePass2 that was buggy because it provided bad padding and even no longer available.
https://keepass.info/plugins.html
http://gogogadgetscott.info/keepass/twofishcipher/

The encryption system has been redesigned and the unnecessary code has been removed, as the workaround is no longer needed, the standard PKCS7PADDING padding is now used for encryption and decryption.

Register your database with KeePass2 using another available encryption and remove your deprecated plugin. You can use Twofish with the right padding (works correctly with KeePassXC)

**Comment by dr4go** [comment]
Thanks for the information. But are you really sure about that? According to
https://sourceforge.net/p/keepass/discussion/329220/thread/e7599abb0a/
the issue had been solved in v1.4. While it's true, that I still had installed v1.3, because of Keepass2Android, it also does not work when using v1.4 of the plugin. To test that I had exported it with v1.3 and re-imported it with v1.4 as stated here:
https://sourceforge.net/p/keepass/discussion/329221/thread/b8d76c5390/

**Comment by J-Jamet** [comment]
I know I am now using the correct padding.
But I don't know about the plugin, I can't look at the source code, the links are no longer accessible.

**Comment by dr4go** [comment]
Thank you for double-checking. I can confirm, that an exported and re-imported kdbx file using TwoFish works fine when using KeepassXC and then re-opening that in KeepassDX. I guess I'm buying KeepassDX pretty soon, but am currently testing it for another bit - it's always a bit "clumsy" to change the usual habbits / the known app(lication)s.

**Comment by J-Jamet** [comment]
I understand, take your time and use the tools that are appropriate for your use. Glad to have helped.

**Comment by Daniellameira2021** [comment]
Depois das últimas atualizações ao tentar abrir meu banco de dados comecei a receber o erro:

falha ao carregar o banco.java.io.IOException:Javax.crypto.BadPaddingException: pad block corrupted

Solucionei o problema abrindo meu banco de dados no aplicativo KeePassDx em uma versão antiga onde meu banco de dados abria sem problemas e troquei a encriptação de Twofish para Rijndael(AES) e salvei o banco de dados. Depois tualizei o KeePassDx que estava na versão antiga e consegui abrir meu banco de dados normalmente.

**Comment by J-Jamet** [comment]
@Daniellameira2021 Please write in English for a better coherence of the conversation. Also, do not spam the Play Store comments by writing the same negative comment with multiple accounts.

**Comment by J-Jamet** [comment]
I improved the code to add the workaround at the opening and saving the base with the right padding.

**Comment by AreYouLoco** [comment]
Please push the version tag so its picked by fdroid.

**Comment by J-Jamet** [comment]
@AreYouLoco You mean I don't have to test the code made in development to make the TAG? I think that in any case it is necessary to do these tests.
Unless you think I don't know how to make a TAG anymore (after having already created 60 only for this application).

**Comment by J-Jamet** [comment]
I did the release branch. I'm checking if there are no big bugs and it will be OK, in one or two days.

**Comment by dr4go** [comment]
Sorry to "re-use" this issue... one thing that I just find interesting... and am asking out of curiosity / not being worried: The file being saved from KeepassDX has a size of about 62kb - when I edit this file with KeepassXC it has a size of about 72kb. Do you or KeepassXC save it differently somehow? I didn't experience any problems so far... that I want to clarify - it's just a question, because of data safety... I hope you understand....

**Comment by J-Jamet** [comment]
>  Do you or KeepassXC save it differently somehow? 

Yes surely, the most important thing is to respect a data formatting, for KDBX 4 databases, it is a specific header an an XML format for data. If the data is ordered differently from one application to another, it doesn't matter, because the parsers can still read it. But as there is underlying compression and loop encryption, the data will take up more or less space depending on their order because the algorithms will use more or less appropriate techniques depending on the blocks of data to be converted, so the size of the data in the final file may vary.

Don't be embarrassed to ask the question, it is legitimate even if it is not in the right section. :D

**Comment by J-Jamet** [comment]
If it is related to the question, there is a padding at the end of the encryption algorithms that allow to respect a specific block size. If this padding is not the same in encryption and decryption, there may be an error because data may be attempted to be read when it is only padding data. (This is what caused the error of the plugin that does not use padding by default). The use of padding is recommended as it allows to drown the data to prevent prediction. https://en.wikipedia.org/wiki/Padding_(cryptography)
