### ISSUE TITLE
Modifications are discarded without prompt when Autosave is disabled

### ISSUE THREAD

**Issue by vetko** [Kunzisoft/KeePassDX#970]
**The bug**
When Autosave is disabled and the database is closed manually then the modifications are discarded without any notification that there are unsaved changes. This can cause severe data loss, as it is an unexpected behavior.

**To Reproduce**
1. Open any database.
2. Do some modifications (e.g. add a new entry).
3. Lock the database.
4. Database is locked, no notification about the unsaved changes.
5. Changes are lost.

**To Reproduce (2nd scenario)**
1. Open any database.
2. Do some modifications (e.g. add a new entry).
3. Select "Reload database".
4. Database is reloaded, no notification about the unsaved changes.
5. Changes are lost.

**To Reproduce (3rd scenario)**
In the previous 2nd scenario, step 3. can also happen when the app detects an external change in the DB file and the user selects the Reload option. Although solving this would probably require a working "merge" implementation, which is under development at the moment. In any case, at least an additional prompt saying that "Warning! Your unsaved modifications will be lost!" would be helpful. Maybe offering a "Save as" possibility in this case would also help.

**Expected behavior**
The app notifies the user about the unsaved changes, and offers two options in a dialog:
1. Save changes before closing.
2. Discard changes and close.

This should happen in **any** scenario when a database can be closed, **except** for close because of timeout, which is a separate (more complicated) topic.

**KeePassDX:**
 - Version: 2.9.18
 - Build: Free
 - Language: English

**Android:**
 - Version: 10

**Comment by vetko** [comment]
To be honest, I don't consider this a "feature", but rather a quite important bug.   
Basically every application in the world is showing a dialog if the file is being closed but there are unsaved changes in it.

**Comment by J-Jamet** [comment]
It's not an existing behavior that doesn't behave as it should. It's a not yet implemented behavior that you want to add because you use it somewhere else, so a feature. Bug or feature is not about user consideration or honesty.

I'm not saying it's not important, but I have to study the feasibility to avoid bugs.  For example, if I implement it quickly and the dialog is displayed while the database is open in read-only mode, there will be a real bug because the functionality will be present.

In KeePassDX, the default behavior saves the database after every important action. You have changed the setting to not  happening anymore, so it's knowingly to save manually.
So I put this feature to study depending on the other work to be done.
