### ISSUE TITLE
Reverse See Password Eye Icon

### ISSUE THREAD

**Issue by seniorm0ment** [Kunzisoft/KeePassDX#980]
Suggesting reversal of the see password eye icon at the password prompt.
Currently if the eye is not crossed out, it does not show the password, if it is crossed out, it does. This logically does not make sense.
Also this is the opposite of how KeepassXC does it.

I suggest making it so when there is a cross in the eye, it hides the password, no cross mens you can see the password.

**Comment by J-Jamet** [comment]
I agree it's not consistent, but I can't do like KeePassXC because the master password and edit input fields are [TextInputLayout](https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout#setEndIconMode(int)) with a end icon mode password toggle which is an Android standard. So the button that will be changed will be the one in the entry visibility screen (which is statically manually created). It's a button that allows to activate the visible state when you click on it so it will be consistent with all other Android applications (but not with KeePassXC)

**Comment by goputtanz** [comment]
It is by default reversed, and there's **no official deprecation** of the following error, but we can fix this by **setting end Icon drawable**  as **custom** . I am using **TextInputLayout**

<com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:id="@+id/editTextLayoutPassword"
        android:layout_width="300dp"
        android:layout_height="match_parent"
        android:hint="Password"
        app:endIconMode="password_toggle">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/editTextPassword"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPassword"
            android:maxLength="20" />
    </com.google.android.material.textfield.TextInputLayout>


And Adding a **Drawable File to change the password toggle icon**

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
<item android:drawable="@drawable/ic_opened_eye"
    android:state_checked="true"/>
<item android:drawable="@drawable/ic_closed_eye"/>
</selector>

_This worked for me_

**Comment by goputtanz** [comment]
The issue is the **outdated functionality of password toggle enabled**, It is **not officially removed**, but we can fix this by adding **custom end icon drawable**

<com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:id="@+id/editTextLayoutPassword"
        android:layout_width="300dp"
        android:layout_height="match_parent"
        android:hint="Password"
        app:endIconMode="password_toggle">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/editTextPassword"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPassword"
            android:maxLength="20" />
    </com.google.android.material.textfield.TextInputLayout>

**And the drawable file as**
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
<item android:drawable="@drawable/ic_opened_eye"
    android:state_checked="true"/>
<item android:drawable="@drawable/ic_closed_eye"/>
</selector>

_this worked for me_
